import { Monster, MonsterType } from '../types';

export const beasts: Monster[] = [
    {
        id: 'giant_rat', name: 'Giant Rat', level: 1, maxHp: 5, attack: 1,
        stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 0,
        iconUrl: '/assets/npcChatHeads/giant_rat.png',
        drops: [ { itemId: 'rat_tail', chance: 1, minQuantity: 1, maxQuantity: 1 }, { itemId: 'bones', chance: 1, minQuantity: 1, maxQuantity: 1 }, ],
        monsterType: MonsterType.Standard, attackSpeed: 4, respawnTime: 20000, aggressive: false, attackStyle: 'stab',
    },
    {
        id: 'giant_spider', name: 'Giant Spider', level: 4, maxHp: 15, attack: 3,
        stabDefence: 2, slashDefence: 2, crushDefence: 2, rangedDefence: 4, magicDefence: 0,
        iconUrl: '/assets/npcChatHeads/giant_spider.png',
        drops: [ { itemId: 'spider_silk', chance: 1, minQuantity: 1, maxQuantity: 1 }, { itemId: 'spider_eggs', chance: 0.5, minQuantity: 1, maxQuantity: 3 }, ],
        monsterType: MonsterType.Standard, attackSpeed: 4, respawnTime: 30000, aggressive: false, attackStyle: 'stab',
    },
    {
        id: 'cow', name: 'Cow', level: 2, maxHp: 10, attack: 1,
        stabDefence: 1, slashDefence: 1, crushDefence: 1, rangedDefence: 1, magicDefence: 0,
        iconUrl: '/assets/npcChatHeads/cow.png',
        drops: [ { itemId: 'raw_beef', chance: 1, minQuantity: 1, maxQuantity: 1 }, { itemId: 'bones', chance: 1, minQuantity: 1, maxQuantity: 1 }, { itemId: 'cowhide', chance: 1, minQuantity: 1, maxQuantity: 1 }, ],
        monsterType: MonsterType.Standard, attackSpeed: 5, respawnTime: 15000, aggressive: false, attackStyle: 'crush',
    },
    {
        id: 'chicken', name: 'Chicken', level: 1, maxHp: 4, attack: 1,
        stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 0,
        iconUrl: '/assets/npcChatHeads/chicken.png',
        drops: [ { itemId: 'raw_chicken', chance: 1, minQuantity: 1, maxQuantity: 1 }, { itemId: 'bones', chance: 1, minQuantity: 1, maxQuantity: 1 }, { itemId: 'feathers', chance: 1, minQuantity: 1, maxQuantity: 20 }, ],
        monsterType: MonsterType.Standard, attackSpeed: 4, respawnTime: 10000, aggressive: false, attackStyle: 'stab',
        customMaxHit: 0,
    },
    {
        id: 'wild_boar', name: 'Wild Boar', level: 6, maxHp: 22, attack: 7,
        stabDefence: 4, slashDefence: 4, crushDefence: 6, rangedDefence: 2, magicDefence: 0,
        iconUrl: '/assets/npcChatHeads/wild_boar.png',
        drops: [ { itemId: 'raw_boar_meat', chance: 1, minQuantity: 1, maxQuantity: 1 }, { itemId: 'boar_hide', chance: 1, minQuantity: 1, maxQuantity: 1 }, { itemId: 'bones', chance: 1, minQuantity: 1, maxQuantity: 1 }, { itemId: 'boar_tusk', chance: 0.3, minQuantity: 1, maxQuantity: 1 } ],
        monsterType: MonsterType.Standard, attackSpeed: 4, respawnTime: 30000, aggressive: true, alwaysAggressive: true, attackStyle: 'crush',
    },
    {
        id: 'mountain_goat', name: 'Mountain Goat', level: 18, maxHp: 30, attack: 15,
        stabDefence: 10, slashDefence: 10, crushDefence: 12, rangedDefence: 8, magicDefence: 5,
        iconUrl: '/assets/npcChatHeads/mountain_goat.png',
        drops: [ { itemId: 'raw_beef', chance: 1, minQuantity: 1, maxQuantity: 1 }, { itemId: 'big_bones', chance: 1, minQuantity: 1, maxQuantity: 1 }, { itemId: 'unicorn_horn_dust', chance: 0.1, minQuantity: 1, maxQuantity: 1 }, ],
        monsterType: MonsterType.Standard, attackSpeed: 4, respawnTime: 30000, aggressive: true, attackStyle: 'crush',
    },
    {
        id: 'bog_serpent', name: 'Bog Serpent', level: 40, maxHp: 120, attack: 35,
        stabDefence: 25, slashDefence: 30, crushDefence: 28, rangedDefence: 20, magicDefence: 15,
        iconUrl: '/assets/npcChatHeads/bog_serpent.png',
        drops: [ { itemId: 'serpent_scale_dust', chance: 1, minQuantity: 1, maxQuantity: 3 }, { itemId: 'big_bones', chance: 1, minQuantity: 1, maxQuantity: 2 }, { itemId: 'steel_bar', chance: 0.1, minQuantity: 1, maxQuantity: 2 }, { itemId: 'slimy_egg_shells', chance: 0.9, minQuantity: 1, maxQuantity: 2 }, { itemId: 'serpents_egg', chance: 0.1, minQuantity: 1, maxQuantity: 1 } ],
        monsterType: MonsterType.Standard, attackSpeed: 4, respawnTime: 90000, aggressive: true, alwaysAggressive: true,
        specialAttacks: [{ name: 'Venom Spit', chance: 0.25, effect: 'damage_multiplier', value: 1.2 }], attackStyle: 'slash',
    },
    {
        id: 'giant_toad', name: 'Giant Toad', level: 15, maxHp: 28, attack: 12,
        stabDefence: 8, slashDefence: 8, crushDefence: 10, rangedDefence: 5, magicDefence: 5,
        iconUrl: '/assets/npcChatHeads/giant_toad.png',
        drops: [ { itemId: 'bones', chance: 1, minQuantity: 1, maxQuantity: 1 }, { itemId: 'spiked_toad_skin', chance: 0.2, minQuantity: 1, maxQuantity: 1 }, ],
        monsterType: MonsterType.Standard, attackSpeed: 4, respawnTime: 30000, aggressive: true, attackStyle: 'crush',
    },
    {
        id: 'giant_crab', name: 'Giant Crab', level: 9, maxHp: 25, attack: 8,
        stabDefence: 15, slashDefence: 15, crushDefence: 12, rangedDefence: 10, magicDefence: 0,
        iconUrl: '/assets/npcChatHeads/giant_crab.png',
        drops: [ { itemId: 'giant_crab_meat', chance: 1, minQuantity: 1, maxQuantity: 1 }, { itemId: 'giant_crab_claw', chance: 0.2, minQuantity: 1, maxQuantity: 1 } ],
        monsterType: MonsterType.Armored, attackSpeed: 4, respawnTime: 30000, aggressive: true, alwaysAggressive: true, attackStyle: 'crush',
    },
    {
        id: 'tidal_crawler', name: 'Tidal Crawler', level: 38, maxHp: 80, attack: 30,
        stabDefence: 45, slashDefence: 45, crushDefence: 40, rangedDefence: 30, magicDefence: 10,
        iconUrl: '/assets/npcChatHeads/tidal_crawler.png',
        drops: [ { itemId: 'raw_eel', chance: 0.1, minQuantity: 1, maxQuantity: 1 } ],
        monsterType: MonsterType.Armored, attackSpeed: 5, respawnTime: 70000, aggressive: true, attackStyle: 'crush',
    },
    {
        id: 'jungle_stalker', name: 'Jungle Stalker', level: 41, maxHp: 80, attack: 42,
        stabDefence: 35, slashDefence: 40, crushDefence: 30, rangedDefence: 25, magicDefence: 15,
        iconUrl: '/assets/npcChatHeads/jungle_stalker.png',
        drops: [ { itemId: 'big_bones', chance: 1, minQuantity: 1, maxQuantity: 1 } ],
        monsterType: MonsterType.Standard, attackSpeed: 3, respawnTime: 100000, aggressive: true, alwaysAggressive: true, attackStyle: 'slash',
    },
];