import { RepeatableQuest, SkillName } from '../types';

export const REPEATABLE_QUEST_POOL: RepeatableQuest[] = [
    // --- TUTORIAL ---
    { id: 'tutorial_magic_rat', type: 'kill', title: 'Magical Pest Control', description: "A rat in the tavern has been chewing on spellbooks. The manager wants it gone, and the Magic Guide suggests using magic.", location: 'general', target: { monsterId: 'tutorial_rat' }, baseCoinReward: 250, xpReward: { skill: SkillName.Magic, amount: 50 } },
    
    // --- MEADOWDALE: GATHER ---
    { id: 'gather_logs_meadowdale', type: 'gather', title: 'Restock the Woodpile', description: "The innkeeper needs more logs for the fire. Bring him a bundle of standard logs.", location: 'meadowdale', target: { itemId: 'logs' }, baseCoinReward: 5, xpReward: { skill: SkillName.Woodcutting, amount: 5 } },
    { id: 'gather_copper_ore_meadowdale', type: 'gather', title: 'Ore for the Smithy', description: "The smithy is running low on basic ore for training new apprentices. Provide some copper ore.", location: 'meadowdale', target: { itemId: 'copper_ore' }, baseCoinReward: 8, xpReward: { skill: SkillName.Mining, amount: 4 } },
    { id: 'gather_tin_ore_meadowdale', type: 'gather', title: 'Tin for the Tinsmith', description: "A local tinsmith needs a fresh supply of tin ore for their wares.", location: 'meadowdale', target: { itemId: 'tin_ore' }, baseCoinReward: 8, xpReward: { skill: SkillName.Mining, amount: 4 } },
    { id: 'gather_iron_ore_meadowdale', type: 'gather', title: 'Iron for Valerius', description: "Valerius the smith needs iron ore for a special commission.", location: 'meadowdale', target: { itemId: 'iron_ore' }, baseCoinReward: 15, xpReward: { skill: SkillName.Mining, amount: 8 } },
    { id: 'gather_coal_meadowdale', type: 'gather', title: 'Coal for the Forge', description: "The smithy's forge is running low on coal, needed to smelt steel.", location: 'meadowdale', target: { itemId: 'coal' }, baseCoinReward: 30, xpReward: { skill: SkillName.Mining, amount: 50 } },
    { id: 'gather_shrimp_meadowdale', type: 'gather', title: "Chef's Request: Shrimp", description: "The local chef needs fresh shrimp for a new recipe. They'll pay for any you can bring.", location: 'meadowdale', target: { itemId: 'raw_shrimp' }, baseCoinReward: 5, xpReward: { skill: SkillName.Fishing, amount: 3 } },
    { id: 'gather_raw_beef_meadowdale', type: 'gather', title: 'Beef for the Butcher', description: "The town butcher is preparing for a feast and needs more raw beef.", location: 'meadowdale', target: { itemId: 'raw_beef' }, baseCoinReward: 7, xpReward: { skill: SkillName.Cooking, amount: 2 } },
    { id: 'gather_raw_chicken_meadowdale', type: 'gather', title: 'Poultry Procurement', description: "The tavern needs more chicken for their pies.", location: 'meadowdale', target: { itemId: 'raw_chicken' }, baseCoinReward: 5, xpReward: { skill: SkillName.Cooking, amount: 2 } },
    { id: 'gather_eggs_meadowdale', type: 'gather', title: "Baker's Dozen", description: "The baker is short on eggs for today's cakes. Collect some from the chicken coop.", location: 'meadowdale', target: { itemId: 'eggs' }, baseCoinReward: 3, xpReward: { skill: SkillName.Cooking, amount: 1 } },
    { id: 'gather_bones_meadowdale', type: 'gather', title: 'Respect for the Dead', description: "The chapel groundskeeper needs more bones for... reasons. It's best not to ask.", location: 'meadowdale', target: { itemId: 'bones' }, baseCoinReward: 5, xpReward: { skill: SkillName.Prayer, amount: 1 } },
    { id: 'gather_feathers_meadowdale', type: 'gather', title: "Fletcher's Stock", description: "The local fletcher is buying feathers in bulk for arrow production.", location: 'meadowdale', target: { itemId: 'feathers' }, baseCoinReward: 2, xpReward: { skill: SkillName.Fletching, amount: 1 }, minQuantity: 100, maxQuantity: 250 },
    { id: 'gather_flax_meadowdale', type: 'gather', title: 'Flax for the Spinner', description: "A local spinner needs flax to create bowstrings for the town guard.", location: 'meadowdale', target: { itemId: 'flax' }, baseCoinReward: 3, xpReward: { skill: SkillName.Crafting, amount: 1 } },
    { id: 'gather_oak_logs_meadowdale', type: 'gather', title: 'Sturdy Oak Needed', description: "A carpenter requires oak logs for a more resilient piece of furniture.", location: 'meadowdale', target: { itemId: 'oak_logs' }, baseCoinReward: 19, xpReward: { skill: SkillName.Woodcutting, amount: 15 } },
    { id: 'gather_goblin_hide_meadowdale', type: 'gather', title: 'Goblin Hide Bounty', description: "A local crafter is experimenting with goblin hide and will pay for any you bring them.", location: 'meadowdale', target: { itemId: 'goblin_hide' }, baseCoinReward: 15, xpReward: { skill: SkillName.Crafting, amount: 3 } },
    { id: 'gather_spider_silk_meadowdale', type: 'gather', title: 'Silky Smooth', description: "The tailor needs spider silk for a special order. Be careful collecting it.", location: 'meadowdale', target: { itemId: 'spider_silk' }, baseCoinReward: 15, xpReward: { skill: SkillName.Crafting, amount: 4 } },
    { id: 'gather_wheat_meadowdale', type: 'gather', title: 'Wheat for the Mill', description: "The windmill operator needs more wheat to mill into flour for the town.", location: 'meadowdale', target: { itemId: 'wheat' }, baseCoinReward: 3, xpReward: { skill: SkillName.Cooking, amount: 1 } },
    { id: 'gather_flour_meadowdale', type: 'gather', title: "Baker's Emergency", description: "The baker has run out of flour and needs some urgently.", location: 'meadowdale', target: { itemId: 'flour' }, baseCoinReward: 7, xpReward: { skill: SkillName.Cooking, amount: 1 } },
    { id: 'gather_rat_tails_meadowdale', type: 'gather', title: 'A Strange Request', description: "An eccentric alchemist in town is paying for rat tails for a... 'special' brew.", location: 'meadowdale', target: { itemId: 'rat_tail' }, baseCoinReward: 5, xpReward: { skill: SkillName.Herblore, amount: 1 } },

    // --- MEADOWDALE: KILL ---
    { id: 'kill_rats_meadowdale', type: 'kill', title: 'Cellar Infestation', description: "Giant rats have infested the tavern's cellar. Clear them out.", location: 'meadowdale', target: { monsterId: 'tavern_rat' }, baseCoinReward: 8, xpReward: { skill: SkillName.Attack, amount: 20 }, isInstance: true, instancePoiId: 'tavern_cellar' },
    { id: 'kill_goblins_meadowdale', type: 'kill', title: 'Mine Mischief', description: 'Goblins are causing trouble in the Stonebreak Mine again. Thin their numbers.', location: 'meadowdale', target: { monsterId: 'goblin' }, baseCoinReward: 10, xpReward: { skill: SkillName.Strength, amount: 15 } },
    { id: 'kill_cows_meadowdale', type: 'kill', title: 'Mad Cow Problem', description: "A strange sickness is making McGregor's cows aggressive. They need to be put down.", location: 'meadowdale', target: { monsterId: 'cow' }, baseCoinReward: 8, xpReward: { skill: SkillName.Attack, amount: 10 }, aggressionToggle: { poiId: 'cow_pasture', monsterId: 'cow' } },
    { id: 'kill_chickens_meadowdale', type: 'kill', title: 'Fowl Play', description: "Something's not right with the chickens at the ranch. They're attacking people on sight!", location: 'meadowdale', target: { monsterId: 'chicken' }, baseCoinReward: 5, xpReward: { skill: SkillName.Attack, amount: 10 }, aggressionToggle: { poiId: 'chicken_coop', monsterId: 'chicken' } },
    { id: 'kill_goblin_scouts_meadowdale', type: 'kill', title: 'Deeper Threats', description: "Goblin scouts have been spotted deeper in the mines, suggesting a larger presence. Take them out.", location: 'meadowdale', target: { monsterId: 'goblin_scout' }, baseCoinReward: 14, xpReward: { skill: SkillName.Defence, amount: 45 } },
    { id: 'kill_spiders_meadowdale', type: 'kill', title: 'Web of Trouble', description: "Giant spiders are nesting too close to the southern road. Clear them out before someone gets hurt.", location: 'meadowdale', target: { monsterId: 'giant_spider' }, baseCoinReward: 10, xpReward: { skill: SkillName.Defence, amount: 20 } },
    { id: 'kill_bandits_meadowdale', type: 'kill', title: 'Roadside Robbery', description: "Cloaked bandits are still a problem on the southern road. The town guard will pay for every one you dispatch.", location: 'meadowdale', target: { monsterId: 'cloaked_bandit' }, baseCoinReward: 14, xpReward: { skill: SkillName.Strength, amount: 20 } },
    { id: 'kill_boars_meadowdale', type: 'kill', title: 'Boarish Behavior', description: "Wild boars from the fields are becoming a nuisance to local travelers and farmers. Cull their numbers.", location: 'meadowdale', target: { monsterId: 'wild_boar' }, baseCoinReward: 12, xpReward: { skill: SkillName.Attack, amount: 40 } },
    { id: 'kill_wolves_meadowdale', type: 'kill', title: 'A Wolf at the Door', description: "Wolves from the highlands are preying on McGregor's livestock. He's offering a reward.", location: 'meadowdale', target: { monsterId: 'wolf' }, baseCoinReward: 18, xpReward: { skill: SkillName.Strength, amount: 70 } },
    { id: 'kill_slimes_meadowdale', type: 'kill', title: 'Slimy Situation', description: "The deeper parts of the mine are getting clogged with cave slimes. Clean up the mess.", location: 'meadowdale', target: { monsterId: 'cave_slime' }, baseCoinReward: 35, xpReward: { skill: SkillName.Defence, amount: 30 } },
    
    // --- MEADOWDALE: INTERACT ---
    { id: 'interact_clean_tavern_meadowdale', type: 'interact', title: 'Tidy the Tavern', description: "The Rusty Flagon is a mess after a busy night. Help the barkeep clean up.", location: 'meadowdale', locationPoiId: 'the_rusty_flagon', target: { name: 'Tidy the Tavern' }, baseCoinReward: 100, xpReward: { skill: SkillName.Strength, amount: 150 } },
    { id: 'interact_deliver_mail_meadowdale', type: 'interact', title: 'Postal Service', description: "The town clerk needs some letters delivered around Meadowdale.", location: 'meadowdale', locationPoiId: 'town_hall', target: { name: 'Deliver Mail' }, baseCoinReward: 120, xpReward: { skill: SkillName.Hitpoints, amount: 10 } },
    { id: 'interact_restock_shelves_meadowdale', type: 'interact', title: 'Restock the General Store', description: "Help the general store owner organize and restock the shelves.", location: 'meadowdale', locationPoiId: 'meadowdale_square', target: { name: 'Restock Shelves' }, baseCoinReward: 150, xpReward: { skill: SkillName.Crafting, amount: 20 } },
    { id: 'interact_repair_fence_meadowdale', type: 'interact', title: 'Fence Mending', description: "A section of fence at McGregor's Ranch has been damaged. Help him repair it.", location: 'meadowdale', locationPoiId: 'mcgregors_ranch', target: { name: 'Repair Fence' }, baseCoinReward: 200, xpReward: { skill: SkillName.Woodcutting, amount: 240 } },
    { id: 'interact_sort_books_meadowdale', type: 'interact', title: 'Library Assistance', description: "Librarian Elara needs help sorting and re-shelving returned books.", location: 'meadowdale', locationPoiId: 'meadowdale_library', target: { name: 'Sort Books' }, baseCoinReward: 220, xpReward: { skill: SkillName.Magic, amount: 300 } },
    
    // --- OAKHAVEN: GATHER ---
    { id: 'gather_oak_logs_oakhaven', type: 'gather', title: 'Oak for Oakhaven', description: 'A local carpenter needs oak logs for a sturdy commission.', location: 'oakhaven', target: { itemId: 'oak_logs' }, baseCoinReward: 19, xpReward: { skill: SkillName.Woodcutting, amount: 30 } },
    { id: 'gather_willow_logs_oakhaven', type: 'gather', title: 'Willow for Bows', description: "The fletcher is buying willow logs for lightweight bows.", location: 'oakhaven', target: { itemId: 'willow_logs' }, baseCoinReward: 35, xpReward: { skill: SkillName.Woodcutting, amount: 60 } },
    { id: 'gather_raw_trout_oakhaven', type: 'gather', title: 'Trout for the Tavern', description: "The Carved Mug is famous for its trout, and they're running low.", location: 'oakhaven', target: { itemId: 'raw_trout' }, baseCoinReward: 20, xpReward: { skill: SkillName.Fishing, amount: 30 } },
    { id: 'gather_raw_pike_oakhaven', type: 'gather', title: 'A Noble Order', description: 'A noble from Silverhaven has ordered pike, and the tavern needs to fulfill it.', location: 'oakhaven', target: { itemId: 'raw_pike' }, baseCoinReward: 25, xpReward: { skill: SkillName.Fishing, amount: 40 } },
    { id: 'gather_raw_eel_oakhaven', type: 'gather', title: 'Swamp Delicacy', description: "A chef will pay well for raw eels from the swamp. Watch out for what lurks in the water.", location: 'oakhaven', target: { itemId: 'raw_eel' }, baseCoinReward: 35, xpReward: { skill: SkillName.Fishing, amount: 50 } },
    { id: 'gather_iron_ore_oakhaven', type: 'gather', title: 'Iron Supply Run', description: 'The blacksmiths of Oakhaven need a steady supply of iron for their tools.', location: 'oakhaven', target: { itemId: 'iron_ore' }, baseCoinReward: 15, xpReward: { skill: SkillName.Mining, amount: 20 } },
    { id: 'gather_coal_oakhaven', type: 'gather', title: 'Fueling the Forges', description: 'Coal is needed to fuel the forges for high-temperature smelting. The demand is high.', location: 'oakhaven', target: { itemId: 'coal' }, baseCoinReward: 30, xpReward: { skill: SkillName.Mining, amount: 50 } },
    { id: 'gather_silver_ore_oakhaven', type: 'gather', title: 'Silver for the Smiths', description: 'A silversmith is paying a premium for raw silver ore to craft fine jewelry.', location: 'oakhaven', target: { itemId: 'silver_ore' }, baseCoinReward: 35, xpReward: { skill: SkillName.Mining, amount: 30 } },
    { id: 'gather_wolf_pelt_oakhaven', type: 'gather', title: 'Warm Winter Cloaks', description: 'Tanner Sven needs wolf pelts for a set of warm cloaks before winter sets in.', location: 'oakhaven', target: { itemId: 'wolf_pelt' }, baseCoinReward: 20, xpReward: { skill: SkillName.Crafting, amount: 40 } },
    { id: 'gather_glimmer_thread_oakhaven', type: 'gather', title: 'Shimmering Threads', description: "The weavers are trying to replicate the shimmer of Glimmerhorn Stag manes. They need fibers.", location: 'oakhaven', target: { itemId: 'glimmer_thread_fiber' }, baseCoinReward: 15, xpReward: { skill: SkillName.Crafting, amount: 50 } },
    
    // --- OAKHAVEN: KILL ---
    { id: 'kill_highwaymen_oakhaven', type: 'kill', title: "King's Road Patrol", description: "Highwaymen are making a nuisance of themselves on the old King's Road. Clear them out.", location: 'oakhaven', target: { monsterId: 'highwayman' }, baseCoinReward: 17, xpReward: { skill: SkillName.Strength, amount: 80 } },
    { id: 'kill_wild_boars_oakhaven', type: 'kill', title: 'Boar Hunt', description: 'Wild boars are becoming aggressive and trampling the fields west of the ranch.', location: 'oakhaven', target: { monsterId: 'wild_boar' }, baseCoinReward: 12, xpReward: { skill: SkillName.Attack, amount: 45 } },
    { id: 'kill_wolves_oakhaven', type: 'kill', title: 'Wolf Pack Problem', description: 'A wolf pack in the Tanglewood has grown bold, threatening travelers.', location: 'oakhaven', target: { monsterId: 'wolf' }, baseCoinReward: 18, xpReward: { skill: SkillName.Strength, amount: 75 } },
    { id: 'kill_bears_oakhaven', type: 'kill', title: 'Bear Necessities', description: "Bears have been wandering out of their caves, scaring locals. Thin their numbers.", location: 'oakhaven', target: { monsterId: 'bear' }, baseCoinReward: 20, xpReward: { skill: SkillName.Defence, amount: 80 } },
    { id: 'kill_glimmerhorn_stags_oakhaven', type: 'kill', title: 'Antler Collection', description: "A collector wants the antlers of the mystical Glimmerhorn Stags. The pay is good.", location: 'oakhaven', target: { monsterId: 'glimmerhorn_stag' }, baseCoinReward: 18, xpReward: { skill: SkillName.Ranged, amount: 70 } },
    { id: 'kill_forest_spirits_oakhaven', type: 'kill', title: 'Restless Spirits', description: 'The Forest Spirits near the ancient stones have become agitated. Quell their anger.', location: 'oakhaven', target: { monsterId: 'forest_spirit' }, baseCoinReward: 22, xpReward: { skill: SkillName.Magic, amount: 65 } },
    { id: 'kill_treant_saplings_oakhaven', type: 'kill', title: 'Pruning the Overgrowth', description: 'Young Treants are overrunning the western ruins, making the area impassable.', location: 'oakhaven', target: { monsterId: 'treant_sapling' }, baseCoinReward: 24, xpReward: { skill: SkillName.Woodcutting, amount: 80 } },
    { id: 'kill_young_hill_giants_oakhaven', type: 'kill', title: 'Giant Problems', description: "Young Hill Giants are causing tremors on the plateau. Put a stop to their roughhousing.", location: 'oakhaven', target: { monsterId: 'young_hill_giant' }, baseCoinReward: 20, xpReward: { skill: SkillName.Strength, amount: 90 } },
    { id: 'kill_giant_toads_oakhaven', type: 'kill', title: 'Toad Trouble', description: 'The giant toads in the Sunken Lands are a noisy, slimy nuisance. Reduce their population.', location: 'oakhaven', target: { monsterId: 'giant_toad' }, baseCoinReward: 15, xpReward: { skill: SkillName.Attack, amount: 60 } },
    { id: 'kill_bog_mites_oakhaven', type: 'kill', title: 'Mire Extermination', description: 'Swarms of Bog Mites are making the Mire of Sorrow even more unpleasant. Clear them out.', location: 'oakhaven', target: { monsterId: 'bog_mite' }, baseCoinReward: 25, xpReward: { skill: SkillName.Defence, amount: 95 } },
    { id: 'kill_swamp_horrors_oakhaven', type: 'kill', title: 'Horrors of the Swamp', description: 'Terrifying Swamp Horrors have emerged from the sunken ruins. They must be destroyed.', location: 'oakhaven', target: { monsterId: 'swamp_horror' }, baseCoinReward: 30, xpReward: { skill: SkillName.Strength, amount: 110 } },
    { id: 'kill_mountain_goats_oakhaven', type: 'kill', title: 'Aggressive Goats', description: 'The mountain goats in the Gale-Swept Peaks are unusually aggressive, knocking travelers from the paths.', location: 'oakhaven', target: { monsterId: 'mountain_goat' }, baseCoinReward: 15, xpReward: { skill: SkillName.Attack, amount: 75 } },
    { id: 'kill_harpies_oakhaven', type: 'kill', title: 'Harpy Hunt', description: "Harpies from the roost are preying on travelers in the mountain pass. A bounty has been posted.", location: 'oakhaven', target: { monsterId: 'harpy' }, baseCoinReward: 27, xpReward: { skill: SkillName.Ranged, amount: 85 } },
    { id: 'kill_goblin_brutes_oakhaven', type: 'kill', title: 'Brute Force', description: 'Goblin Brutes have been seen guarding key passages in the warrens. Eliminate the threat.', location: 'oakhaven', target: { monsterId: 'goblin_brute' }, baseCoinReward: 35, xpReward: { skill: SkillName.Strength, amount: 100 } },
    { id: 'bounty_grumlok_oakhaven', type: 'kill', title: 'Bounty: Grumlok the Goblin King', description: "A bounty has been posted for the head of Grumlok. He is a formidable foe in the Goblin Warrens. Combat level 30+ is strongly recommended.", location: 'oakhaven', target: { monsterId: 'grumlok_goblin_king' }, baseCoinReward: 1000, xpReward: { skill: SkillName.Slayer, amount: 250 }, minQuantity: 1, maxQuantity: 1 },
    
    // --- OAKHAVEN: INTERACT ---
    { id: 'interact_clean_carved_mug_oakhaven', type: 'interact', title: 'Tavern Cleanup', description: "The Carved Mug is in disarray after a rowdy night. Help Freya clean up the mess.", location: 'oakhaven', locationPoiId: 'the_carved_mug', target: { name: 'Clean Tavern' }, baseCoinReward: 200, xpReward: { skill: SkillName.Strength, amount: 80 } },
    { id: 'interact_restock_artisan_supplies_oakhaven', type: 'interact', title: 'Restock Supplies', description: 'The Artisan Supplies shop needs help restocking shelves with heavy goods.', location: 'oakhaven', locationPoiId: 'oakhaven_crafting_supplies', target: { name: 'Restock Shelves' }, baseCoinReward: 220, xpReward: { skill: SkillName.Crafting, amount: 90 } },
    { id: 'interact_prepare_hides_oakhaven', type: 'interact', title: "Tanner's Assistant", description: "Tanner Sven needs help preparing raw hides for the tanning process. It's smelly work.", location: 'oakhaven', locationPoiId: 'tanner_svens_shop', target: { name: 'Prepare Hides' }, baseCoinReward: 240, xpReward: { skill: SkillName.Crafting, amount: 100 } },
    { id: 'interact_organize_apothecary_oakhaven', type: 'interact', title: 'Apothecary Aid', description: "Herbalist Anise's shop is a mess of vials and herbs. She needs a hand organizing it.", location: 'oakhaven', locationPoiId: 'oakhaven_herblore_shop', target: { name: 'Organize Vials' }, baseCoinReward: 260, xpReward: { skill: SkillName.Herblore, amount: 110 } },
    { id: 'interact_deliver_wood_oakhaven', type: 'interact', title: 'Lumber Delivery', description: "Deliver a cart of freshly cut lumber from Alaric's workshop to the market.", location: 'oakhaven', locationPoiId: 'oakhaven_woodworkers_shop', target: { name: 'Deliver Lumber' }, baseCoinReward: 280, xpReward: { skill: SkillName.Woodcutting, amount: 120 } },

    // --- ISLE OF WHISPERS ---
    { id: 'kill_crabs_isle', type: 'kill', title: 'Crab Cull', description: "The giant crab population is out of control and threatening the docks. Thin their numbers.", location: 'isle_of_whispers', target: { monsterId: 'giant_crab' }, baseCoinReward: 20, xpReward: { skill: SkillName.Attack, amount: 50 } },
    { id: 'gather_driftwood_isle', type: 'gather', title: 'Salvage Operation', description: "The settlers need driftwood to reinforce their shacks before the next storm. Gather some from the beaches.", location: 'isle_of_whispers', target: { itemId: 'driftwood_logs' }, baseCoinReward: 10, xpReward: { skill: SkillName.Woodcutting, amount: 40 } },
    { id: 'kill_specters_isle', type: 'kill', title: 'Ghost Busting', description: "The shipwreck specters are becoming more aggressive. Put them to rest.", location: 'isle_of_whispers', target: { monsterId: 'shipwreck_specter' }, baseCoinReward: 80, xpReward: { skill: SkillName.Ranged, amount: 100 } },
    { id: 'interact_sort_salvage_isle', type: 'interact', title: 'Sort the Salvage', description: "Help Salty Sam sort through the latest haul of shipwreck salvage at The Barnacle's Bite.", location: 'isle_of_whispers', locationPoiId: 'the_barnacles_bite', target: { name: 'Sort Salvage' }, baseCoinReward: 300, xpReward: { skill: SkillName.Crafting, amount: 120 } },

    // --- SILVERHAVEN: GATHER ---
    { id: 'gather_yew_logs_silverhaven', type: 'gather', title: 'Yew for the Shipwrights', description: 'The shipwrights at the docks require yew logs for a new vessel.', location: 'silverhaven', target: { itemId: 'yew_logs' }, baseCoinReward: 65, xpReward: { skill: SkillName.Woodcutting, amount: 180 } },
    { id: 'gather_mithril_ore_silverhaven', type: 'gather', title: 'Mithril for the Armory', description: 'The Gilded Hammer Armory has a large order for mithril equipment.', location: 'silverhaven', target: { itemId: 'mithril_ore' }, baseCoinReward: 55, xpReward: { skill: SkillName.Mining, amount: 85 } },
    { id: 'gather_adamantite_ore_silverhaven', type: 'gather', title: 'Adamantite Stockpile', description: 'The city guard is stockpiling adamantite for emergencies. They pay well.', location: 'silverhaven', target: { itemId: 'adamantite_ore' }, baseCoinReward: 60, xpReward: { skill: SkillName.Mining, amount: 125 } },
    { id: 'gather_raw_swordfish_silverhaven', type: 'gather', title: 'Banquet Supplies: Swordfish', description: 'The castle chef is preparing a banquet and needs fresh swordfish.', location: 'silverhaven', target: { itemId: 'raw_swordfish' }, baseCoinReward: 50, xpReward: { skill: SkillName.Fishing, amount: 145 } },
    { id: 'gather_raw_shark_silverhaven', type: 'gather', title: 'An Exotic Order', description: 'A noble has requested a fresh shark for a... display piece. The fish market will buy any you catch.', location: 'silverhaven', target: { itemId: 'raw_shark' }, baseCoinReward: 80, xpReward: { skill: SkillName.Fishing, amount: 215 } },
    { id: 'gather_mahogany_logs_silverhaven', type: 'gather', title: 'Furniture for a Noble', description: 'A wealthy noble is commissioning furniture and requires mahogany logs.', location: 'silverhaven', target: { itemId: 'mahogany_logs' }, baseCoinReward: 50, xpReward: { skill: SkillName.Woodcutting, amount: 130 } },
    { id: 'gather_uncut_diamonds_silverhaven', type: 'gather', title: 'Jeweler\'s Demand', description: 'The city jewelers are in desperate need of uncut diamonds for a royal commission.', location: 'silverhaven', target: { itemId: 'uncut_diamond' }, baseCoinReward: 210, xpReward: { skill: SkillName.Crafting, amount: 360 } },
    
    // --- SILVERHAVEN: CRAFTING (GATHER) ---
    { id: 'craft_yew_longbows_silverhaven', type: 'gather', title: 'Bows for the Guard', description: "The city guard's archer division needs a new supply of Yew Longbows.", location: 'silverhaven', target: { itemId: 'yew_longbow' }, baseCoinReward: 150, xpReward: { skill: SkillName.Fletching, amount: 80 } },
    { id: 'craft_adamantite_platelegs_silverhaven', type: 'gather', title: 'Leg Day', description: "The Gilded Hammer needs help fulfilling an order for Adamantite Platelegs.", location: 'silverhaven', target: { itemId: 'adamantite_platelegs' }, baseCoinReward: 420, xpReward: { skill: SkillName.Smithing, amount: 200 } },
    { id: 'craft_super_attack_potions_silverhaven', type: 'gather', title: 'Alchemical Supply', description: 'The Slayer Master requires Super Attack Potions for their new recruits.', location: 'silverhaven', target: { itemId: 'super_attack_potion' }, baseCoinReward: 500, xpReward: { skill: SkillName.Herblore, amount: 105 } },
    { id: 'craft_diamond_amulets_silverhaven', type: 'gather', title: 'Amulets of Power', description: 'A merchant wants to export a crate of enchanted Diamond Amulets.', location: 'silverhaven', target: { itemId: 'amulet_of_power' }, baseCoinReward: 1500, xpReward: { skill: SkillName.Crafting, amount: 200 } },
    
    // --- SILVERHAVEN: RUNECRAFTING (GATHER) ---
    { id: 'gather_verdant_runes_silverhaven', type: 'gather', title: 'Verdant Runes for the Mages', description: 'The mages in the Arcane Wares shop need a large supply of Verdant Runes.', location: 'silverhaven', target: { itemId: 'verdant_rune' }, baseCoinReward: 6, xpReward: { skill: SkillName.Runecrafting, amount: 1 }, minQuantity: 100, maxQuantity: 500 },
    { id: 'gather_nexus_runes_silverhaven', type: 'gather', title: 'Nexus Rune Research', description: 'Archmage Theron is conducting research and requires Nexus Runes.', location: 'silverhaven', target: { itemId: 'nexus_rune' }, baseCoinReward: 13, xpReward: { skill: SkillName.Runecrafting, amount: 1 }, minQuantity: 100, maxQuantity: 500 },
    { id: 'gather_hex_runes_silverhaven', type: 'gather', title: 'Hexes for the Guard', description: 'The city guard is enchanting their bolts with minor hexes and need the runes.', location: 'silverhaven', target: { itemId: 'hex_rune' }, baseCoinReward: 3, xpReward: { skill: SkillName.Runecrafting, amount: 1 }, minQuantity: 100, maxQuantity: 500 },
    
    // --- SILVERHAVEN: KILL ---
    { id: 'kill_sirens_silverhaven', type: 'kill', title: 'Siren Song', description: 'The sirens on the Isle of Whispers are luring too many ships to their doom. Put an end to their song.', location: 'silverhaven', target: { monsterId: 'siren' }, baseCoinReward: 120, xpReward: { skill: SkillName.Ranged, amount: 120 } },
    { id: 'kill_abyssal_knights_silverhaven', type: 'kill', title: 'Knight Eradication', description: 'The Abyssal Knights in the Sunken Labyrinth pose a significant threat. They must be eliminated.', location: 'silverhaven', target: { monsterId: 'abyssal_knight' }, baseCoinReward: 240, xpReward: { skill: SkillName.Defence, amount: 150 } },
    { id: 'kill_grave_revenants_silverhaven', type: 'kill', title: 'Rest for the Dead', description: 'Grave Revenants haunt the Sunken Labyrinth. Grant them final rest.', location: 'silverhaven', target: { monsterId: 'grave_revenant' }, baseCoinReward: 210, xpReward: { skill: SkillName.Prayer, amount: 140 } },
    { id: 'kill_coral_golems_silverhaven', type: 'kill', title: 'Reef Clearing', description: 'Coral Golems are blocking ancient waterways in the labyrinth. Clear them out.', location: 'silverhaven', target: { monsterId: 'coral_golem' }, baseCoinReward: 180, xpReward: { skill: SkillName.Strength, amount: 145 } },
    //{ id: 'kill_grove_dragons_silverhaven', type: 'kill', title: 'Dragon Hunt', description: 'A bounty has been placed on Grove Dragons. Hunt them for a substantial reward.', location: 'silverhaven', target: { monsterId: 'grove_dragon' }, baseCoinReward: 1200, xpReward: { skill: SkillName.Slayer, amount: 200 } },
    { id: 'bounty_abyssal_warden_silverhaven', type: 'kill', title: 'Bounty: The Abyssal Warden', description: 'A large bounty has been placed on the head of The Abyssal Warden, guardian of the Sunken Labyrinth. Combat level 70+ recommended.', location: 'silverhaven', target: { monsterId: 'the_abyssal_warden' }, baseCoinReward: 15000, xpReward: { skill: SkillName.Slayer, amount: 1000 }, minQuantity: 1, maxQuantity: 1 },

    // --- SILVERHAVEN: INTERACT ---
    { id: 'interact_polish_fountain_silverhaven', type: 'interact', title: 'Polish the Fountain', description: 'The great silver dragon fountain in the square is looking a bit tarnished. Polish it up.', location: 'silverhaven', locationPoiId: 'silverhaven_square', target: { name: 'Polish Fountain' }, baseCoinReward: 400, xpReward: { skill: SkillName.Crafting, amount: 150 } },
    { id: 'interact_sort_cargo_silverhaven', type: 'interact', title: 'Sort the Cargo', description: 'The harbormaster at the docks needs help sorting and cataloging incoming cargo.', location: 'silverhaven', locationPoiId: 'silverhaven_docks', target: { name: 'Sort Cargo' }, baseCoinReward: 450, xpReward: { skill: SkillName.Strength, amount: 160 } },
    { id: 'interact_clean_spire_silverhaven', type: 'interact', title: 'Spire Maintenance', description: "The Slayer's Spire needs a good cleaning. Kaelen is too busy to do it himself.", location: 'silverhaven', locationPoiId: 'silverhaven_slayers_spire', target: { name: 'Clean the Spire' }, baseCoinReward: 500, xpReward: { skill: SkillName.Strength, amount: 180 } }, // Agility is not a skill, using Strength as a placeholder
    { id: 'interact_organize_armory_silverhaven', type: 'interact', title: 'Organize the Armory', description: 'Help Master Smith Gideon organize the vast stores of armor and weapons in The Gilded Hammer.', location: 'silverhaven', locationPoiId: 'silverhaven_smithy', target: { name: 'Organize Armory' }, baseCoinReward: 550, xpReward: { skill: SkillName.Smithing, amount: 200 } },

];