import { SkillName, SkillGuideEntry } from '../types';
import { HOUSE_TIERS, THIEVING_CONTAINER_TARGETS, THIEVING_POCKET_TARGETS, THIEVING_STALL_TARGETS } from './';

export const SKILL_GUIDES: Record<SkillName, SkillGuideEntry[]> = {
    [SkillName.Attack]: [
        { level: 1, description: 'Increases your chance to hit with melee.' },
        { level: 1, description: 'Wield Bronze weapons.', itemId: 'bronze_sword' },
        { level: 5, description: 'Wield Iron weapons.', itemId: 'iron_sword' },
        { level: 10, description: 'Wield Steel weapons.', itemId: 'steel_sword' },
        { level: 20, description: 'Wield Mithril weapons.', itemId: 'mithril_sword' },
        { level: 30, description: 'Wield Adamantite weapons.', itemId: 'adamantite_sword' },
        { level: 40, description: 'Wield Runic weapons.', itemId: 'runic_sword' },
        { level: 60, description: 'Wield Aquatite weapons.', itemId: 'aquatite_sword' },
    ],
    [SkillName.Strength]: [
        { level: 1, description: 'Increases your maximum melee hit.' },
        { level: 1, description: 'Wield Bronze Warhammers.', itemId: 'bronze_warhammer'},
        { level: 5, description: 'Wield Iron Warhammers.', itemId: 'iron_warhammer'},
        { level: 10, description: 'Wield Steel Warhammers.', itemId: 'steel_warhammer'},
        { level: 20, description: 'Wield Mithril Warhammers.', itemId: 'mithril_warhammer'},
        { level: 30, description: 'Wield Adamantite Warhammers.', itemId: 'adamantite_warhammer'},
        { level: 40, description: 'Wield Runic Warhammers.', itemId: 'runic_warhammer'},
    ],
    [SkillName.Defence]: [
        { level: 1, description: 'Decrease the chance to be hit by physical attack.' },
        { level: 1, description: 'Wear Leather and Bronze armour.', itemId: 'bronze_platebody' },
        { level: 5, description: 'Wear Iron armour.', itemId: 'iron_platebody' },
        { level: 10, description: 'Wear Steel armour.', itemId: 'steel_platebody' },
        { level: 20, description: 'Wear Mithril armour.', itemId: 'mithril_platebody' },
        { level: 30, description: 'Wear Adamantite armour.', itemId: 'adamantite_platebody' },
        { level: 40, description: 'Wear Runic armour.', itemId: 'runic_platebody' },
        { level: 60, description: 'Wear Aquatite armour.', itemId: 'aquatite_platebody' },
    ],
    [SkillName.Ranged]: [
        { level: 1, description: 'Increases your accuracy and damage of ranged attacks' },
        { level: 1, description: 'Wield a Shortbow or Longbow.', itemId: 'shortbow' },
        { level: 1, description: 'Wield a Bronze Crossbow.', itemId: 'bronze_crossbow' },
        { level: 5, description: 'Wear Boar Hide armour.', itemId: 'boar_hide_body' },
        { level: 10, description: 'Wield an Oak Shortbow or Longbow.', itemId: 'oak_shortbow' },
        { level: 10, description: 'Wear Wolf Pelt armour.', itemId: 'wolf_pelt_body' },
        { level: 20, description: 'Wear Bear Hide armour.', itemId: 'bear_hide_body' },
        { level: 20, description: 'Wield a Willow Shortbow or Longbow.', itemId: 'willow_shortbow' },
        { level: 26, description: 'Wield an Iron Crossbow.', itemId: 'iron_crossbow' },
        { level: 30, description: 'Wield a Feywood Shortbow or Longbow.', itemId: 'feywood_shortbow' },
        { level: 31, description: 'Wield a Steel Crossbow.', itemId: 'steel_crossbow' },
        { level: 40, description: 'Wield a Yew Shortbow or Longbow.', itemId: 'yew_shortbow' },
        { level: 40, description: 'Wear Grove Hide armour.', itemId: 'grovehide_body' },
        { level: 41, description: 'Wield a Mithril Crossbow.', itemId: 'mithril_crossbow' },
        { level: 50, description: 'Wear Frost Hide armour.', itemId: 'frosthide_body' },
        { level: 51, description: 'Wield an Adamantite Crossbow.', itemId: 'adamantite_crossbow' },
        { level: 60, description: 'Wear Emberscale armour.', itemId: 'emberscale_body' },
        { level: 61, description: 'Wield a Runic Crossbow.', itemId: 'runic_crossbow' },
        { level: 70, description: 'Wear Deathscythe armour.', itemId: 'deathscythe_body' },
    ].sort((a, b) => a.level - b.level),
    [SkillName.Magic]: [
        { level: 1, description: 'Increases your chance to hit with magic, and defend against it.' },
        { level: 1, description: 'Wear Wizard robes. Cast Gust Dart.', itemId: 'wizard_robe_top' },
        { level: 3, description: 'Cast Weaken curse.', itemId: 'binding_rune' },
        { level: 5, description: 'Cast Aqua Dart.', itemId: 'aqua_rune' },
        { level: 7, description: 'Cast Enchant Sapphire.', itemId: 'sapphire_amulet' },
        { level: 9, description: 'Cast Stone Dart.', itemId: 'stone_rune' },
        { level: 13, description: 'Cast Ember Dart.', itemId: 'ember_rune' },
        { level: 17, description: 'Cast Gust Bolt.', itemId: 'gust_rune' },
        { level: 23, description: 'Cast Clarity of Thought.', itemId: 'flux_rune' },
        { level: 24, description: 'Cast Aqua Bolt.', itemId: 'aqua_rune' },
        { level: 25, description: 'Cast Meadowdale Teleport.', itemId: 'passage_rune' },
        { level: 27, description: 'Cast Enchant Emerald.', itemId: 'emerald_amulet' },
        { level: 31, description: 'Cast Stone Bolt.', itemId: 'stone_rune' },
        { level: 31, description: 'Cast Oakhaven Teleport.', itemId: 'passage_rune' },
        { level: 33, description: 'Cast Lesser Transmutation.', itemId: 'flux_rune' },
        { level: 37, description: 'Cast Silverhaven Teleport.', itemId: 'passage_rune' },
        { level: 38, description: 'Cast Ember Bolt.', itemId: 'ember_rune' },
        { level: 41, description: 'Cast Vulnerability.', itemId: 'nexus_rune' },
        { level: 42, description: 'Cast Gust Blast.', itemId: 'gust_rune' },
        { level: 43, description: 'Cast Superheat Ore.', itemId: 'ember_rune' },
        { level: 49, description: 'Cast Enchant Ruby.', itemId: 'ruby_amulet' },
        { level: 49, description: 'Cast Aqua Blast.', itemId: 'aqua_rune' },
        { level: 54, description: 'Cast Stone Blast.', itemId: 'stone_rune' },
        { level: 57, description: 'Cast Enchant Diamond.', itemId: 'diamond_amulet' },
        { level: 59, description: 'Cast Ember Blast.', itemId: 'ember_rune' },
        { level: 62, description: 'Cast Greater Transmutation.', itemId: 'anima_rune' },
        { level: 66, description: 'Cast Gust Wave.', itemId: 'gust_rune' },
        { level: 66, description: 'Cast Arcane Strength.', itemId: 'anima_rune' },
        { level: 68, description: 'Cast Enchant Sunstone.', itemId: 'sunstone_amulet' },
        { level: 73, description: 'Cast Aqua Wave.', itemId: 'aqua_rune' },
        { level: 77, description: 'Cast Stone Wave.', itemId: 'stone_rune' },
        { level: 81, description: 'Cast Ember Wave.', itemId: 'ember_rune' },
        { level: 82, description: 'Cast Enfeeble.', itemId: 'anima_rune' },
        { level: 85, description: 'Cast Gust Storm.', itemId: 'aether_rune' },
        { level: 89, description: 'Cast Aqua Storm.', itemId: 'aether_rune' },
        { level: 92, description: 'Cast Stone Storm.', itemId: 'aether_rune' },
        { level: 95, description: 'Cast Ember Storm.', itemId: 'aether_rune' },
    ],
    [SkillName.Hitpoints]: [
        { level: 1, description: 'Increases your maximum health.' },
    ],
    [SkillName.Prayer]: [
        { level: 1, description: 'Unlock Iron Will.' },
        { level: 4, description: 'Unlock Rising Power.' },
        { level: 7, description: 'Unlock Focused Strike.' },
        { level: 10, description: 'Unlock Steady Aim.' },
        { level: 13, description: 'Unlock Arcane Intent.' },
        { level: 16, description: 'Unlock Rapid Heal.' },
        { level: 22, description: 'Unlock Stone Guard.' },
        { level: 25, description: 'Unlock Surging Might.' },
        { level: 25, description: 'Unlock Protect Item.' },
        { level: 28, description: 'Unlock Keen Edge.' },
        { level: 31, description: 'Unlock Sure Shot.' },
        { level: 34, description: 'Unlock Weaver\'s Mind.' },
        { level: 43, description: 'Unlock Aegis Form.' },
        { level: 46, description: 'Unlock Titan\'s Vigor.' },
        { level: 49, description: 'Unlock Blade Master.' },
        { level: 52, description: 'Unlock Deadeye.' },
        { level: 55, description: 'Unlock Archon\'s Insight.' },
        { level: 58, description: "Unlock Protect from Magic. Unlocked by 'The Sorcerer\'s Trial'.", questId: 'the_sorcerers_trial' },
        { level: 61, description: "Unlock Protect from Ranged. Unlocked by 'The Great Hunt'.", questId: 'the_great_hunt' },
        { level: 65, description: "Unlock Protect from Melee. Unlocked by 'The Trial of War'.", questId: 'the_trial_of_war' },
        { level: 70, description: 'Unlock Adamant Skin.' },
        { level: 73, description: 'Unlock Divine Strength.' },
        { level: 76, description: 'Unlock Unrelenting Focus.' },
        { level: 79, description: 'Unlock Celestial Sight.' },
        { level: 82, description: 'Unlock Arcane Mastery.' },
    ].sort((a, b) => a.level - b.level),
    [SkillName.Woodcutting]: [
        { level: 1, description: 'Chop normal Trees. Use Bronze or Iron Axe.', itemId: 'logs' },
        { level: 5, description: 'Chop Driftwood Trees.', itemId: 'driftwood_logs' },
        { level: 6, description: 'Use a Steel Axe.', itemId: 'steel_axe' },
        { level: 15, description: 'Chop Oak Trees.', itemId: 'oak_logs' },
        { level: 21, description: 'Use a Mithril Axe.', itemId: 'mithril_axe' },
        { level: 30, description: 'Chop Willow Trees.', itemId: 'willow_logs' },
        { level: 31, description: 'Use an Adamantite Axe.', itemId: 'adamantite_axe' },
        { level: 41, description: 'Use a Runic Axe.', itemId: 'runic_axe' },
        { level: 45, description: 'Chop Maple Trees.', itemId: 'maple_logs' },
        { level: 50, description: 'Chop Mahogany Trees.', itemId: 'mahogany_logs' },
        { level: 55, description: 'Chop Feywood Trees.', itemId: 'feywood_logs' },
        { level: 65, description: 'Chop Yew Trees.', itemId: 'yew_logs' },
    ].sort((a, b) => a.level - b.level),
    [SkillName.Fletching]: [
        { level: 1, description: 'Fletch Arrow Shafts from logs.', itemId: 'arrow_shaft' },
        { level: 1, description: 'Attach feathers to create Headless Arrows.', itemId: 'headless_arrow' },
        { level: 1, description: 'Fletch Bronze arrows & bolts.', itemId: 'bronze_arrow' },
        { level: 1, description: 'Fletch a Shortbow.', itemId: 'shortbow' },
        { level: 5, description: 'Fletch a Longbow.', itemId: 'longbow' },
        { level: 9, description: 'Fletch a Bronze Crossbow.', itemId: 'bronze_crossbow' },
        { level: 15, description: 'Fletch Iron arrows & bolts.', itemId: 'iron_arrow' },
        { level: 20, description: 'Fletch an Oak Shortbow.', itemId: 'oak_shortbow' },
        { level: 24, description: 'Fletch an Iron Crossbow.', itemId: 'iron_crossbow' },
        { level: 25, description: 'Fletch an Oak Longbow.', itemId: 'oak_longbow' },
        { level: 30, description: 'Fletch Steel arrows & bolts.', itemId: 'steel_arrow' },
        { level: 35, description: 'Fletch a Willow Shortbow.', itemId: 'willow_shortbow' },
        { level: 39, description: 'Fletch a Steel Crossbow.', itemId: 'steel_crossbow' },
        { level: 40, description: 'Fletch a Willow Longbow.', itemId: 'willow_longbow' },
        { level: 45, description: 'Fletch Mithril arrows.', itemId: 'mithril_arrow' },
        { level: 50, description: 'Fletch a Feywood Shortbow.', itemId: 'feywood_shortbow' },
        { level: 50, description: 'Fletch Mithril bolts.', itemId: 'mithril_bolts' },
        { level: 54, description: 'Fletch a Mithril Crossbow.', itemId: 'mithril_crossbow' },
        { level: 55, description: 'Fletch a Feywood Longbow.', itemId: 'feywood_longbow' },
        { level: 60, description: 'Fletch Adamantite arrows.', itemId: 'adamantite_arrow' },
        { level: 65, description: 'Fletch a Yew Shortbow.', itemId: 'yew_shortbow' },
        { level: 65, description: 'Fletch Adamantite bolts.', itemId: 'adamantite_bolts' },
        { level: 69, description: 'Fletch an Adamantite Crossbow.', itemId: 'adamantite_crossbow' },
        { level: 70, description: 'Fletch a Yew Longbow.', itemId: 'yew_longbow' },
        { level: 75, description: 'Fletch Runic arrows.', itemId: 'runic_arrow' },
        { level: 80, description: 'Fletch Runic bolts.', itemId: 'runic_bolts' },
        { level: 84, description: 'Fletch a Runic Crossbow.', itemId: 'runic_crossbow' },
    ],
    [SkillName.Firemaking]: [
        { level: 1, description: 'Light normal logs.', itemId: 'logs' },
        { level: 5, description: 'Light driftwood logs.', itemId: 'driftwood_logs' },
        { level: 15, description: 'Light oak logs.', itemId: 'oak_logs' },
        { level: 30, description: 'Light willow logs.', itemId: 'willow_logs' },
        { level: 45, description: 'Light maple logs.', itemId: 'maple_logs' },
        { level: 50, description: 'Light mahogany logs.', itemId: 'mahogany_logs' },
        { level: 60, description: 'Light yew logs.', itemId: 'yew_logs' },
        { level: 75, description: 'Light feywood logs.', itemId: 'feywood_logs' },
    ].sort((a, b) => a.level - b.level),
    [SkillName.Fishing]: [
        { level: 1, description: 'Catch Shrimp with a Small Fishing Net.', itemId: 'raw_shrimp' },
        { level: 5, description: 'Catch Sardines with a Fishing Rod and bait.', itemId: 'raw_sardine' },
        { level: 10, description: 'Catch Herring with a Fishing Rod and bait.', itemId: 'raw_herring' },
        { level: 20, description: 'Catch Trout with a Fly Fishing Rod and feathers.', itemId: 'raw_trout' },
        { level: 30, description: 'Catch Pike with a Fly Fishing Rod and feathers.', itemId: 'raw_pike' },
        { level: 38, description: 'Catch Eels with a Basket Trap.', itemId: 'raw_eel' },
        { level: 40, description: 'Catch Tuna with a Harpoon.', itemId: 'raw_tuna' },
        { level: 50, description: 'Catch Lobsters with an Ocean Box Trap.', itemId: 'raw_lobster' },
        { level: 53, description: 'Catch Molten Eels in the Volcanic Steam Vents.', itemId: 'molten_eel' },
        { level: 62, description: 'Catch Swordfish with a Harpoon.', itemId: 'raw_swordfish' },
        { level: 76, description: 'Catch Sharks with a Harpoon.', itemId: 'raw_shark' },
    ].sort((a, b) => a.level - b.level),
    [SkillName.Cooking]: [
        { level: 1, description: 'Cook Shrimp.', itemId: 'cooked_shrimp' },
        { level: 1, description: 'Bake Bread (Flour + Water -> Dough).', itemId: 'bread' },
        { level: 1, description: 'Cook a Rat Kebab.', itemId: 'rat_kebab_cooked' },
        { level: 1, description: 'Cook Scrambled Eggs.', itemId: 'scrambled_eggs' },
        { level: 3, description: 'Cook Chicken.', itemId: 'cooked_chicken' },
        { level: 5, description: 'Cook Beef.', itemId: 'cooked_beef' },
        { level: 5, description: 'Cook Sardines.', itemId: 'cooked_sardine' },
        { level: 8, description: 'Cook Giant Crab Meat.', itemId: 'cooked_crab_meat' },
        { level: 10, description: 'Cook Boar Meat.', itemId: 'cooked_boar_meat' },
        { level: 10, description: 'Cook Herring.', itemId: 'cooked_herring' },
        { level: 10, description: 'Bake Berry Pie (Pie Shell + Berries).', itemId: 'berry_pie' },
        { level: 20, description: 'Cook Trout.', itemId: 'cooked_trout' },
        { level: 20, description: 'Bake Meat Pie (Pie Shell + Cooked Meat).', itemId: 'meat_pie' },
        { level: 26, description: 'Churn Milk into Cheese at a Windmill.', itemId: 'cheese' },
        { level: 30, description: 'Cook Pike.', itemId: 'cooked_pike' },
        { level: 30, description: 'Bake Apple Pie (Pie Shell + Apple).', itemId: 'apple_pie' },
        { level: 35, description: 'Bake Plain Pizza (Pizza Base + Tomato + Cheese).', itemId: 'plain_pizza' },
        { level: 35, description: 'Make Meat Pizza (Cooked Pizza + Cooked Meat).', itemId: 'meat_pizza' },
        { level: 38, description: 'Cook Eel.', itemId: 'cooked_eel' },
        { level: 40, description: 'Cook Tuna.', itemId: 'cooked_tuna' },
        { level: 40, description: 'Bake Cake (Flour + Egg + Milk + Cake Tin).', itemId: 'cake' },
        { level: 40, description: 'Make Anchovy Pizza (Cooked Pizza + Cooked Anchovy).', itemId: 'anchovy_pizza' },
        { level: 47, description: 'Bake Fish Pie (Pie Shell + Trout/Pike).', itemId: 'fish_pie' },
        { level: 50, description: 'Cook Lobster.', itemId: 'cooked_lobster' },
        { level: 50, description: 'Cook Serpent Omelet.', itemId: 'serpent_omelet_cooked' },
        { level: 50, description: 'Make Pineapple Pizza (Cooked Pizza + Pineapple).', itemId: 'pineapple_pizza' },
        { level: 62, description: 'Cook Swordfish.', itemId: 'cooked_swordfish' },
        { level: 76, description: 'Cook Shark.', itemId: 'cooked_shark' },
    ].sort((a, b) => a.level - b.level),
    [SkillName.Crafting]: [
        { level: 1, description: 'Spin Wool into Balls of Wool.', itemId: 'ball_of_wool' },
        { level: 1, description: 'Craft Leather Gloves.', itemId: 'leather_gloves' },
        { level: 3, description: 'Craft Leather Boots.', itemId: 'leather_boots' },
        { level: 5, description: 'Craft Leather Vambraces.', itemId: 'leather_vambraces' },
        { level: 6, description: 'Craft Leather Cowls.', itemId: 'leather_cowl' },
        { level: 7, description: 'Craft Leather Chaps.', itemId: 'leather_chaps' },
        { level: 9, description: 'Craft Leather Bodies.', itemId: 'leather_body' },
        { level: 9, description: 'Craft Boar Hide armour.', itemId: 'boar_hide_body' },
        { level: 10, description: 'Spin Flax into a Bow String.', itemId: 'bow_string' },
        { level: 10, description: 'Craft a Tome of Warding.', itemId: 'tome_of_warding' },
        { level: 15, description: 'Craft Rope from Flax.', itemId: 'rope' },
        { level: 18, description: 'Craft Wolf Pelt armour.', itemId: 'wolf_pelt_body' },
        { level: 20, description: 'Cut Sapphires with a Chisel.', itemId: 'sapphire' },
        { level: 20, description: 'Craft a Sapphire Ring.', itemId: 'sapphire_ring' },
        { level: 20, description: 'Craft a Tome of Focus.', itemId: 'tome_of_focus' },
        { level: 26, description: 'Craft a Sapphire Necklace.', itemId: 'sapphire_necklace' },
        { level: 27, description: 'Cut Emeralds with a Chisel.', itemId: 'emerald' },
        { level: 27, description: 'Craft an Emerald Ring.', itemId: 'emerald_ring' },
        { level: 29, description: 'Craft an Emerald Necklace.', itemId: 'emerald_necklace' },
        { level: 30, description: 'Craft a Tome of Power.', itemId: 'tome_of_power' },
        { level: 31, description: 'Craft an Emerald Amulet.', itemId: 'emerald_amulet_u' },
        { level: 32, description: 'Craft Bear Hide armour.', itemId: 'bear_hide_body' },
        { level: 32, description: 'Craft a Sapphire Amulet.', itemId: 'sapphire_amulet_u' },
        { level: 34, description: 'Cut Rubies with a Chisel.', itemId: 'ruby' },
        { level: 34, description: 'Craft a Ruby Ring.', itemId: 'ruby_ring' },
        { level: 40, description: 'Craft a Ruby Necklace.', itemId: 'ruby_necklace' },
        { level: 40, description: 'Craft a Tome of the Arcane.', itemId: 'tome_of_the_arcane' },
        { level: 43, description: 'Cut Diamonds with a Chisel.', itemId: 'diamond' },
        { level: 43, description: 'Craft a Diamond Ring.', itemId: 'diamond_ring' },
        { level: 50, description: 'Craft a Ruby Amulet.', itemId: 'ruby_amulet_u' },
        { level: 50, description: 'Craft a Tome of the Master.', itemId: 'tome_of_the_master' },
        { level: 52, description: 'Craft Grovehide armour.', itemId: 'grovehide_body' },
        { level: 55, description: 'Cut Sunstones with a Chisel.', itemId: 'sunstone' },
        { level: 55, description: 'Craft a Sunstone Ring.', itemId: 'sunstone_ring' },
        { level: 56, description: 'Craft a Diamond Necklace.', itemId: 'diamond_necklace' },
        { level: 63, description: 'Craft Frosthide armour.', itemId: 'frosthide_body' },
        { level: 67, description: 'Cut Tenebrites with a Chisel.', itemId: 'tenebrite' },
        { level: 70, description: 'Craft a Diamond Amulet.', itemId: 'diamond_amulet_u' },
        { level: 70, description: 'Craft a Sunstone Necklace.', itemId: 'sunstone_necklace' },
        { level: 74, description: 'Craft Emberscale armour.', itemId: 'emberscale_body' },
        { level: 80, description: 'Craft a Sunstone Amulet.', itemId: 'sunstone_amulet_u' },
        { level: 82, description: 'Craft Deathscythe armour.', itemId: 'deathscythe_body' },
    ],
    [SkillName.Mining]: [
        { level: 1, description: 'Mine Copper and Tin ore. Use Bronze or Iron Pickaxe.', itemId: 'copper_ore' },
        { level: 6, description: 'Use a Steel Pickaxe.', itemId: 'steel_pickaxe' },
        { level: 15, description: 'Mine Iron ore.', itemId: 'iron_ore' },
        { level: 20, description: 'Mine Silver ore.', itemId: 'silver_ore' },
        { level: 21, description: 'Use a Mithril Pickaxe.', itemId: 'mithril_pickaxe' },
        { level: 30, description: 'Mine Coal.', itemId: 'coal' },
        { level: 31, description: 'Use an Adamantite Pickaxe.', itemId: 'adamantite_pickaxe' },
        { level: 40, description: 'Mine Gold Ore.', itemId: 'gold_ore' },
        { level: 41, description: 'Use a Runic Pickaxe.', itemId: 'runic_pickaxe' },
        { level: 45, description: 'Mine Brimstone.', itemId: 'brimstone' },
        { level: 50, description: 'Mine Mithril ore.', itemId: 'mithril_ore' },
        { level: 41, description: 'Use a Crystal Tipped Runic Pickaxe.', itemId: 'crystal_tipped_runic_pickaxe' },
        { level: 65, description: 'Mine Adamantite ore.', itemId: 'adamantite_ore' },
        { level: 75, description: 'Mine Titanium ore.', itemId: 'titanium_ore' },
    ].sort((a, b) => a.level - b.level),
    [SkillName.Smithing]: [
        { level: 1, description: 'Smelt Bronze Bars.', itemId: 'bronze_bar' },
        { level: 1, description: 'Smith Bronze items.', itemId: 'bronze_sword' },
        { level: 3, description: 'Smith Bronze Warhammers.', itemId: 'bronze_warhammer'},
        { level: 15, description: 'Smelt Iron Bars.', itemId: 'iron_bar' },
        { level: 15, description: 'Smith Iron items.', itemId: 'iron_sword' },
        { level: 18, description: 'Smith Iron Warhammers.', itemId: 'iron_warhammer'},
        { level: 20, description: 'Smelt Silver Bars.', itemId: 'silver_bar' },
        { level: 30, description: 'Smelt Steel Bars.', itemId: 'steel_bar' },
        { level: 30, description: 'Smith Steel items.', itemId: 'steel_sword' },
        { level: 33, description: 'Smith Steel Warhammers.', itemId: 'steel_warhammer'},
        { level: 40, description: 'Smelt Gold Bars.', itemId: 'gold_bar' },
        { level: 50, description: 'Smelt Mithril Bars.', itemId: 'mithril_bar' },
        { level: 50, description: 'Smith Mithril items.', itemId: 'mithril_sword' },
        { level: 53, description: 'Smith Mithril Warhammers.', itemId: 'mithril_warhammer'},
        { level: 65, description: 'Smelt Adamantite Bars.', itemId: 'adamantite_bar' },
        { level: 65, description: 'Smith Adamantite items.', itemId: 'adamantite_sword' },
        { level: 68, description: 'Smith Adamantite Warhammers.', itemId: 'adamantite_warhammer'},
        { level: 80, description: 'Smelt Runic Bars.', itemId: 'runic_bar' },
        { level: 80, description: 'Smith Runic items.', itemId: 'runic_sword' },
        { level: 83, description: 'Smith Runic Warhammers.', itemId: 'runic_warhammer'},
    ].sort((a, b) => a.level - b.level),
    [SkillName.Herblore]: [
        // This is a special case handled by the HerbloreGuide component
    ],
    [SkillName.Runecrafting]: [
        { level: 1, description: 'Craft Gust Runes.', itemId: 'gust_rune' },
        { level: 2, description: 'Craft Binding Runes.', itemId: 'binding_rune' },
        { level: 5, description: 'Craft Stone Runes.', itemId: 'stone_rune' },
        { level: 8, description: 'Multiple Runes: Every 8 levels past the unlock requirement for a rune, gain 1 additional rune per essence.' },
        { level: 9, description: 'Craft Aqua Runes.', itemId: 'aqua_rune' },
        { level: 14, description: 'Craft Ember Runes.', itemId: 'ember_rune' },
        { level: 20, description: 'Craft Flux Runes.', itemId: 'flux_rune' },
        { level: 27, description: 'Craft Verdant Runes.', itemId: 'verdant_rune' },
        { level: 35, description: 'Craft Astral Runes.', itemId: 'astral_rune' },
        { level: 44, description: 'Craft Hex Runes.', itemId: 'hex_rune' },
        { level: 50, description: 'Craft Passage Runes.', itemId: 'passage_rune' },
        { level: 55, description: 'Craft Nexus Runes.', itemId: 'nexus_rune' },
        { level: 72, description: 'Craft Anima Runes.', itemId: 'anima_rune' },
        { level: 85, description: 'Craft Aether Runes.', itemId: 'aether_rune' },
    ],
    [SkillName.Slayer]: [
        { level: 1, description: 'Visit Kaelen, the Slayer Master, in Silverhaven to receive tasks.' },
        { level: 50, description: 'Unlock access to the Slayer Blimp in Silverhaven.' },
    ],
    [SkillName.Thieving]: [],
    [SkillName.Agility]: [
        { level: 1, description: 'Start the Meadowdale Rooftop Course.' },
        { level: 12, description: "Start the Oakhaven Artisan's Run." },
        { level: 25, description: 'Start the Verdant Fields Traverse.' },
        { level: 30, description: 'Start the Salt Flats Skeleton Run.' },
        { level: 35, description: 'Start the Fouthia Rooftop Run.' },
        { level: 46, description: 'Start the Sanctity Cathedral Climb.' },
        { level: 55, description: 'Start the Shipwreck Graveyard Leap.' },
        { level: 65, description: 'Start the Crystalline Isles Traverse.' },
        { level: 70, description: 'Start the Silverhaven Castle Run.' },
        { level: 75, description: 'Start the Wyrmwood Treetop Run.' },
        { level: 80, description: 'Start the Gale-Swept Peaks Ridge Walk.' },
        { level: 90, description: 'Start the Volcanic Brimstone Run.' },
    ],
};