import { Item, EquipmentSlot, SkillName } from '../../types';

export const armor: Item[] = [
    // Bronze
    { id: 'bronze_full_helm', name: 'Bronze Full Helm', description: 'A helmet that covers the entire head.', stackable: false, value: 25, iconUrl: 'https://api.iconify.design/game-icons:crested-helmet.svg', material: 'bronze', equipment: { slot: EquipmentSlot.Head, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: -3, stabDefence: 9, slashDefence: 8, crushDefence: 7, rangedDefence: 2, magicDefence: -1, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 1 }], } },
    { id: 'bronze_platebody', name: 'Bronze Platebody', description: 'Provides excellent protection for the torso.', stackable: false, value: 60, iconUrl: 'https://api.iconify.design/game-icons:breastplate.svg', material: 'bronze', equipment: { slot: EquipmentSlot.Body, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: -10, stabDefence: 20, slashDefence: 18, crushDefence: 15, rangedDefence: 5, magicDefence: -5, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 1 }], } },
    { id: 'bronze_platelegs', name: 'Bronze Platelegs', description: 'Sturdy platelegs made from bronze.', stackable: false, value: 40, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'bronze', equipment: { slot: EquipmentSlot.Legs, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: -5, stabDefence: 10, slashDefence: 9, crushDefence: 8, rangedDefence: 3, magicDefence: -3, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 1 }], } },
    { id: 'bronze_kiteshield', name: 'Bronze Kiteshield', description: 'A large, sturdy shield.', stackable: false, value: 35, iconUrl: 'https://api.iconify.design/game-icons:shield.svg', material: 'bronze', equipment: { slot: EquipmentSlot.Shield, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: -5, stabDefence: 12, slashDefence: 11, crushDefence: 10, rangedDefence: 5, magicDefence: 0, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 1 }], } },
    // Iron
    { id: 'iron_full_helm', name: 'Iron Full Helm', description: 'A sturdy iron helmet.', stackable: false, value: 150, iconUrl: 'https://api.iconify.design/game-icons:crested-helmet.svg', material: 'iron', equipment: { slot: EquipmentSlot.Head, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: -2, magicAttack: -3, stabDefence: 15, slashDefence: 14, crushDefence: 13, rangedDefence: 5, magicDefence: -2, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 5 }], } },
    { id: 'iron_platebody', name: 'Iron Platebody', description: 'Provides good protection for the torso.', stackable: false, value: 400, iconUrl: 'https://api.iconify.design/game-icons:breastplate.svg', material: 'iron', equipment: { slot: EquipmentSlot.Body, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: -10, magicAttack: -15, stabDefence: 35, slashDefence: 33, crushDefence: 30, rangedDefence: 10, magicDefence: -10, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 5 }], } },
    { id: 'iron_platelegs', name: 'Iron Platelegs', description: 'Sturdy platelegs made from iron.', stackable: false, value: 220, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'iron', equipment: { slot: EquipmentSlot.Legs, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: -5, magicAttack: -7, stabDefence: 25, slashDefence: 23, crushDefence: 20, rangedDefence: 7, magicDefence: -6, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 5 }], } },
    { id: 'iron_kiteshield', name: 'Iron Kiteshield', description: 'A large, sturdy iron shield.', stackable: false, value: 210, iconUrl: 'https://api.iconify.design/game-icons:shield.svg', material: 'iron', equipment: { slot: EquipmentSlot.Shield, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: -8, stabDefence: 20, slashDefence: 18, crushDefence: 16, rangedDefence: 10, magicDefence: -1, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 5 }], } },
    // Steel
    { id: 'steel_full_helm', name: 'Steel Full Helm', description: 'A sturdy steel helmet.', stackable: false, value: 360, iconUrl: 'https://api.iconify.design/game-icons:crested-helmet.svg', material: 'steel', equipment: { slot: EquipmentSlot.Head, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: -3, magicAttack: -4, stabDefence: 22, slashDefence: 21, crushDefence: 19, rangedDefence: 8, magicDefence: -4, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 10 }], } },
    { id: 'steel_platebody', name: 'Steel Platebody', description: 'Provides excellent protection for the torso.', stackable: false, value: 950, iconUrl: 'https://api.iconify.design/game-icons:breastplate.svg', material: 'steel', equipment: { slot: EquipmentSlot.Body, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: -15, magicAttack: -20, stabDefence: 50, slashDefence: 48, crushDefence: 44, rangedDefence: 15, magicDefence: -15, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 10 }], } },
    { id: 'steel_platelegs', name: 'Steel Platelegs', description: 'Sturdy platelegs made from steel.', stackable: false, value: 540, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'steel', equipment: { slot: EquipmentSlot.Legs, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: -7, magicAttack: -10, stabDefence: 38, slashDefence: 36, crushDefence: 32, rangedDefence: 12, magicDefence: -9, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 10 }], } },
    { id: 'steel_kiteshield', name: 'Steel Kiteshield', description: 'A large, sturdy steel shield.', stackable: false, value: 500, iconUrl: 'https://api.iconify.design/game-icons:shield.svg', material: 'steel', equipment: { slot: EquipmentSlot.Shield, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: -10, stabDefence: 30, slashDefence: 28, crushDefence: 25, rangedDefence: 15, magicDefence: -2, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 10 }], } },
    // Mithril
    { id: 'mithril_full_helm', name: 'Mithril Full Helm', description: 'A sturdy mithril helmet.', stackable: false, value: 900, iconUrl: 'https://api.iconify.design/game-icons:crested-helmet.svg', material: 'mithril', equipment: { slot: EquipmentSlot.Head, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: -3, magicAttack: -4, stabDefence: 26, slashDefence: 25, crushDefence: 23, rangedDefence: 10, magicDefence: -6, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 20 }], } },
    { id: 'mithril_platebody', name: 'Mithril Platebody', description: 'Provides excellent protection for the torso.', stackable: false, value: 2375, iconUrl: 'https://api.iconify.design/game-icons:breastplate.svg', material: 'mithril', equipment: { slot: EquipmentSlot.Body, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: -15, magicAttack: -20, stabDefence: 58, slashDefence: 55, crushDefence: 50, rangedDefence: 18, magicDefence: -18, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 20 }], } },
    { id: 'mithril_platelegs', name: 'Mithril Platelegs', description: 'Sturdy platelegs made from mithril.', stackable: false, value: 1350, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'mithril', equipment: { slot: EquipmentSlot.Legs, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: -8, magicAttack: -12, stabDefence: 42, slashDefence: 40, crushDefence: 36, rangedDefence: 15, magicDefence: -11, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 20 }], } },
    { id: 'mithril_kiteshield', name: 'Mithril Kiteshield', description: 'A large, sturdy mithril shield.', stackable: false, value: 1250, iconUrl: 'https://api.iconify.design/game-icons:shield.svg', material: 'mithril', equipment: { slot: EquipmentSlot.Shield, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: -10, stabDefence: 35, slashDefence: 33, crushDefence: 30, rangedDefence: 18, magicDefence: -3, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 20 }], } },
    // Adamantite
    { id: 'adamantite_full_helm', name: 'Adamantite Full Helm', description: 'A sturdy adamantite helmet.', stackable: false, value: 1800, iconUrl: 'https://api.iconify.design/game-icons:crested-helmet.svg', material: 'adamantite', equipment: { slot: EquipmentSlot.Head, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: -4, magicAttack: -5, stabDefence: 32, slashDefence: 30, crushDefence: 28, rangedDefence: 12, magicDefence: -7, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 30 }], } },
    { id: 'adamantite_platebody', name: 'Adamantite Platebody', description: 'Provides excellent protection for the torso.', stackable: false, value: 4750, iconUrl: 'https://api.iconify.design/game-icons:breastplate.svg', material: 'adamantite', equipment: { slot: EquipmentSlot.Body, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: -20, magicAttack: -25, stabDefence: 65, slashDefence: 62, crushDefence: 58, rangedDefence: 22, magicDefence: -22, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 30 }], } },
    { id: 'adamantite_platelegs', name: 'Adamantite Platelegs', description: 'Sturdy platelegs made from adamantite.', stackable: false, value: 2700, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'adamantite', equipment: { slot: EquipmentSlot.Legs, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: -10, magicAttack: -15, stabDefence: 50, slashDefence: 48, crushDefence: 44, rangedDefence: 18, magicDefence: -13, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 30 }], } },
    { id: 'adamantite_kiteshield', name: 'Adamantite Kiteshield', description: 'A large, sturdy adamantite shield.', stackable: false, value: 2500, iconUrl: 'https://api.iconify.design/game-icons:shield.svg', material: 'adamantite', equipment: { slot: EquipmentSlot.Shield, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: -12, stabDefence: 42, slashDefence: 40, crushDefence: 38, rangedDefence: 20, magicDefence: -4, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 30 }], } },
    // Runic
    { id: 'runic_full_helm', name: 'Runic Full Helm', description: 'A sturdy runic helmet.', stackable: false, value: 3600, iconUrl: 'https://api.iconify.design/game-icons:crested-helmet.svg', material: 'runic', equipment: { slot: EquipmentSlot.Head, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: -5, magicAttack: -6, stabDefence: 42, slashDefence: 40, crushDefence: 38, rangedDefence: 15, magicDefence: -8, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 40 }], } },
    { id: 'runic_platebody', name: 'Runic Platebody', description: 'Provides excellent protection for the torso.', stackable: false, value: 9500, iconUrl: 'https://api.iconify.design/game-icons:breastplate.svg', material: 'runic', equipment: { slot: EquipmentSlot.Body, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: -25, magicAttack: -30, stabDefence: 80, slashDefence: 78, crushDefence: 72, rangedDefence: 28, magicDefence: -25, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 40 }], } },
    { id: 'runic_platelegs', name: 'Runic Platelegs', description: 'Sturdy platelegs made from runic metal.', stackable: false, value: 5400, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'runic', equipment: { slot: EquipmentSlot.Legs, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: -12, magicAttack: -18, stabDefence: 60, slashDefence: 58, crushDefence: 55, rangedDefence: 22, magicDefence: -15, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 40 }], } },
    { id: 'runic_kiteshield', name: 'Runic Kiteshield', description: 'A large, sturdy runic shield.', stackable: false, value: 5000, iconUrl: 'https://api.iconify.design/game-icons:shield.svg', material: 'runic', equipment: { slot: EquipmentSlot.Shield, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: -15, stabDefence: 52, slashDefence: 50, crushDefence: 48, rangedDefence: 25, magicDefence: -5, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 40 }], } },
    // Aquatite
    { id: 'aquatite_full_helm', name: 'Aquatite Full Helm', description: 'A helmet forged from Aquatite. Provides excellent protection, especially against projectiles.', stackable: false, value: 60000, iconUrl: 'https://api.iconify.design/game-icons:crested-helmet.svg', material: 'aquatite', equipment: { slot: EquipmentSlot.Head, stabAttack: 0, slashAttack: 0, crushAttack: 0, magicAttack: -10, rangedAttack: -5, stabDefence: 40, slashDefence: 42, crushDefence: 38, magicDefence: 0, rangedDefence: 45, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 60 }], } },
    { id: 'aquatite_platebody', name: 'Aquatite Platebody', description: 'Provides powerful protection for the torso, especially against ranged attacks.', stackable: false, value: 150000, iconUrl: 'https://api.iconify.design/game-icons:breastplate.svg', material: 'aquatite', equipment: { slot: EquipmentSlot.Body, stabAttack: 0, slashAttack: 0, crushAttack: 0, magicAttack: -30, rangedAttack: -15, stabDefence: 95, slashDefence: 92, crushDefence: 88, magicDefence: -5, rangedDefence: 100, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 60 }], } },
    { id: 'aquatite_platelegs', name: 'Aquatite Platelegs', description: 'Sturdy platelegs made from Aquatite. Excellent against arrows.', stackable: false, value: 95000, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'aquatite', equipment: { slot: EquipmentSlot.Legs, stabAttack: 0, slashAttack: 0, crushAttack: 0, magicAttack: -21, rangedAttack: -7, stabDefence: 65, slashDefence: 62, crushDefence: 60, magicDefence: -3, rangedDefence: 68, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 60 }], } },
    { id: 'aquatite_kiteshield', name: 'Aquatite Kiteshield', description: 'A large, sturdy shield made from Aquatite.', stackable: false, value: 90000, iconUrl: 'https://api.iconify.design/game-icons:shield.svg', material: 'aquatite', equipment: { slot: EquipmentSlot.Shield, stabAttack: 0, slashAttack: 0, crushAttack: 0, magicAttack: -12, rangedAttack: -8, stabDefence: 60, slashDefence: 62, crushDefence: 58, magicDefence: -2, rangedDefence: 65, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 60 }], } },
    // --- Leather & Hide ---
    { id: 'leather_body', name: 'Leather Body', description: 'Provides minor protection.', stackable: false, value: 30, iconUrl: 'https://api.iconify.design/game-icons:leather-vest.svg', material: 'leather', equipment: { slot: EquipmentSlot.Body, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 4, magicAttack: -5, stabDefence: 5, slashDefence: 8, crushDefence: 7, rangedDefence: 6, magicDefence: 4, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 1 }], } },
    { id: 'leather_gloves', name: 'Leather Gloves', description: 'Simple leather gloves.', stackable: false, value: 15, iconUrl: 'https://api.iconify.design/game-icons:gloves.svg', material: 'leather', equipment: { slot: EquipmentSlot.Gloves, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 1, magicAttack: 0, stabDefence: 1, slashDefence: 1, crushDefence: 1, rangedDefence: 1, magicDefence: 0, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 1 }], } },
    { id: 'leather_boots', name: 'Leather Boots', description: 'Simple leather boots.', stackable: false, value: 15, iconUrl: 'https://api.iconify.design/game-icons:leather-boot.svg', material: 'leather', equipment: { slot: EquipmentSlot.Boots, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 0, stabDefence: 1, slashDefence: 1, crushDefence: 1, rangedDefence: 1, magicDefence: 0, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 1 }], } },
    { id: 'leather_cowl', name: 'Leather Cowl', description: 'A simple leather hood.', stackable: false, value: 20, iconUrl: 'https://api.iconify.design/game-icons:light-helm.svg', material: 'leather', equipment: { slot: EquipmentSlot.Head, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 1, magicAttack: -1, stabDefence: 1, slashDefence: 2, crushDefence: 2, rangedDefence: 1, magicDefence: 1, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [ { skill: SkillName.Defence, level: 1 }, { skill: SkillName.Ranged, level: 1 }, ], } },
    { id: 'leather_vambraces', name: 'Leather Vambraces', description: 'Sturdy leather arm guards.', stackable: false, value: 25, iconUrl: 'https://api.iconify.design/game-icons:bracers.svg', material: 'leather', equipment: { slot: EquipmentSlot.Gloves, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 2, magicAttack: -1, stabDefence: 1, slashDefence: 2, crushDefence: 1, rangedDefence: 1, magicDefence: 1, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [ { skill: SkillName.Defence, level: 1 }, { skill: SkillName.Ranged, level: 1 }, ], } },
    { id: 'leather_chaps', name: 'Leather Chaps', description: 'Protective leather leg coverings.', stackable: false, value: 25, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'leather', equipment: { slot: EquipmentSlot.Legs, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 2, magicAttack: -2, stabDefence: 2, slashDefence: 4, crushDefence: 3, rangedDefence: 3, magicDefence: 2, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 1 }], } },
    // Boar Hide (Level 9)
    { id: 'boar_hide_cowl', name: 'Boar Hide Cowl', description: 'A sturdy cowl made from boar hide.', stackable: false, value: 40, iconUrl: 'https://api.iconify.design/game-icons:light-helm.svg', material: 'leather', equipment: { slot: EquipmentSlot.Head, requiredLevels: [{ skill: SkillName.Defence, level: 1 }, { skill: SkillName.Ranged, level: 5 }], rangedAttack: 1, stabDefence: 2, slashDefence: 3, crushDefence: 3, rangedDefence: 2, stabAttack: 0, slashAttack: 0, crushAttack: 0, magicAttack: -1, magicDefence: 2, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'boar_hide_body', name: 'Boar Hide Body', description: 'A tough body armor made from boar hide.', stackable: false, value: 100, iconUrl: 'https://api.iconify.design/game-icons:leather-vest.svg', material: 'leather', equipment: { slot: EquipmentSlot.Body, requiredLevels: [{ skill: SkillName.Defence, level: 5 }, { skill: SkillName.Ranged, level: 5 }], rangedAttack: 4, stabDefence: 12, slashDefence: 14, crushDefence: 15, rangedDefence: 10, stabAttack: 0, slashAttack: 0, crushAttack: 0, magicAttack: -7, magicDefence: 6, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'boar_hide_chaps', name: 'Boar Hide Chaps', description: 'Protective chaps made from boar hide.', stackable: false, value: 60, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'leather', equipment: { slot: EquipmentSlot.Legs, requiredLevels: [{ skill: SkillName.Defence, level: 1 }, { skill: SkillName.Ranged, level: 5 }], rangedAttack: 2, stabDefence: 6, slashDefence: 8, crushDefence: 9, rangedDefence: 5, stabAttack: 0, slashAttack: 0, crushAttack: 0, magicAttack: -3, magicDefence: 4, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'boar_hide_vambraces', name: 'Boar Hide Vambraces', description: 'Vambraces made from tough boar hide.', stackable: false, value: 40, iconUrl: 'https://api.iconify.design/game-icons:bracers.svg', material: 'leather', equipment: { slot: EquipmentSlot.Gloves, requiredLevels: [{ skill: SkillName.Defence, level: 1 }, { skill: SkillName.Ranged, level: 5 }], rangedAttack: 3, stabDefence: 1, slashDefence: 2, crushDefence: 2, rangedDefence: 1, stabAttack: 0, slashAttack: 0, crushAttack: 0, magicAttack: -2, magicDefence: 2, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    // Wolf Pelt (Level 18)
    { id: 'wolf_pelt_cowl', name: 'Wolf Pelt Cowl', description: 'A cowl made from wolf fur.', stackable: false, value: 80, iconUrl: 'https://api.iconify.design/game-icons:light-helm.svg', material: 'leather', equipment: { slot: EquipmentSlot.Head, requiredLevels: [{ skill: SkillName.Defence, level: 1 }, { skill: SkillName.Ranged, level: 10 }], rangedAttack: 2, stabDefence: 4, slashDefence: 5, crushDefence: 5, rangedDefence: 3, stabAttack: 0, slashAttack: 0, crushAttack: 0, magicAttack: -2, magicDefence: 3, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'wolf_pelt_body', name: 'Wolf Pelt Body', description: 'A body armor made from wolf fur, offering a strength bonus.', stackable: false, value: 200, iconUrl: 'https://api.iconify.design/game-icons:leather-vest.svg', material: 'leather', equipment: { slot: EquipmentSlot.Body, requiredLevels: [{ skill: SkillName.Defence, level: 10 }, { skill: SkillName.Ranged, level: 10 }], rangedAttack: 8, stabDefence: 18, slashDefence: 22, crushDefence: 20, rangedDefence: 15, strengthBonus: 1, stabAttack: 0, slashAttack: 0, crushAttack: 0, magicAttack: -8, magicDefence: 8, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'wolf_pelt_chaps', name: 'Wolf Pelt Chaps', description: 'Chaps made from wolf fur.', stackable: false, value: 120, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'leather', equipment: { slot: EquipmentSlot.Legs, requiredLevels: [{ skill: SkillName.Defence, level: 1 }, { skill: SkillName.Ranged, level: 10 }], rangedAttack: 4, stabDefence: 10, slashDefence: 13, crushDefence: 11, rangedDefence: 8, stabAttack: 0, slashAttack: 0, crushAttack: 0, magicAttack: -4, magicDefence: 5, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'wolf_pelt_vambraces', name: 'Wolf Pelt Vambraces', description: 'Vambraces made from wolf fur, offering a strength bonus.', stackable: false, value: 80, iconUrl: 'https://api.iconify.design/game-icons:bracers.svg', material: 'leather', equipment: { slot: EquipmentSlot.Gloves, requiredLevels: [{ skill: SkillName.Defence, level: 1 }, { skill: SkillName.Ranged, level: 10 }], rangedAttack: 5, stabDefence: 3, slashDefence: 4, crushDefence: 3, rangedDefence: 2, strengthBonus: 1, stabAttack: 0, slashAttack: 0, crushAttack: 0, magicAttack: -1, magicDefence: 3, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'wolf_pelt_cloak', name: 'Wolf Pelt Cloak', description: 'A warm cloak made from the pelt of a wolf.', stackable: false, value: 150, iconUrl: 'https://api.iconify.design/game-icons:cloak.svg', material: 'leather', equipment: { slot: EquipmentSlot.Cape, requiredLevels: [{ skill: SkillName.Defence, level: 1 }], rangedAttack: 0, stabDefence: 1, slashDefence: 2, crushDefence: 2, rangedDefence: 1, stabAttack: 0, slashAttack: 0, crushAttack: 0, magicAttack: -1, magicDefence: 1, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    // Bear Hide (Level 32)
    { id: 'bear_hide_cowl', name: 'Bear Hide Cowl', description: 'A thick cowl made from bear hide.', stackable: false, value: 150, iconUrl: 'https://api.iconify.design/game-icons:light-helm.svg', material: 'leather', equipment: { slot: EquipmentSlot.Head, requiredLevels: [{ skill: SkillName.Defence, level: 1 }, { skill: SkillName.Ranged, level: 20 }], rangedAttack: 3, stabDefence: 6, slashDefence: 7, crushDefence: 6, rangedDefence: 5, stabAttack: 0, slashAttack: 0, crushAttack: 0, magicAttack: -2, magicDefence: 4, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'bear_hide_body', name: 'Bear Hide Body', description: 'A heavy body armor made from bear hide.', stackable: false, value: 350, iconUrl: 'https://api.iconify.design/game-icons:leather-vest.svg', material: 'leather', equipment: { slot: EquipmentSlot.Body, requiredLevels: [{ skill: SkillName.Defence, level: 20 }, { skill: SkillName.Ranged, level: 20 }], rangedAttack: 12, stabDefence: 26, slashDefence: 30, crushDefence: 28, rangedDefence: 22, stabAttack: 0, slashAttack: 0, crushAttack: 0, magicAttack: -12, magicDefence: 10, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'bear_hide_chaps', name: 'Bear Hide Chaps', description: 'Thick chaps made from bear hide.', stackable: false, value: 250, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'leather', equipment: { slot: EquipmentSlot.Legs, requiredLevels: [{ skill: SkillName.Defence, level: 1 }, { skill: SkillName.Ranged, level: 20 }], rangedAttack: 6, stabDefence: 15, slashDefence: 18, crushDefence: 16, rangedDefence: 12, stabAttack: 0, slashAttack: 0, crushAttack: 0, magicAttack: -7, magicDefence: 6, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'bear_hide_vambraces', name: 'Bear Hide Vambraces', description: 'Heavy vambraces made from bear hide.', stackable: false, value: 150, iconUrl: 'https://api.iconify.design/game-icons:bracers.svg', material: 'leather', equipment: { slot: EquipmentSlot.Gloves, requiredLevels: [{ skill: SkillName.Defence, level: 1 }, { skill: SkillName.Ranged, level: 20 }], rangedAttack: 7, stabDefence: 5, slashDefence: 6, crushDefence: 5, rangedDefence: 4, stabAttack: 0, slashAttack: 0, crushAttack: 0, magicAttack: -2, magicDefence: 4, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    // Jewelry
    { id: 'silver_ring', name: 'Silver Ring', description: 'A simple silver ring.', stackable: false, value: 600, iconUrl: 'https://api.iconify.design/game-icons:ring.svg', material: 'silver', equipment: { slot: EquipmentSlot.Ring, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 0, stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 0, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, } },
    { id: 'silver_necklace', name: 'Silver Necklace', description: 'A simple silver necklace.', stackable: false, value: 675, iconUrl: 'https://api.iconify.design/game-icons:necklace.svg', material: 'silver', equipment: { slot: EquipmentSlot.Necklace, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 0, stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 0, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, } },
    { id: 'silver_amulet', name: 'Silver Amulet', description: 'A simple silver amulet on a string.', stackable: false, value: 800, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'silver', equipment: { slot: EquipmentSlot.Necklace, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 0, stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 0, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, } },
    { id: 'gold_ring', name: 'Gold Ring', description: 'A simple gold ring.', stackable: false, value: 700, iconUrl: 'https://api.iconify.design/game-icons:ring.svg', material: 'gold', equipment: { slot: EquipmentSlot.Ring, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 0, stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 1, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, } },
    { id: 'gold_necklace', name: 'Gold Necklace', description: 'A simple gold necklace.', stackable: false, value: 800, iconUrl: 'https://api.iconify.design/game-icons:necklace.svg', material: 'gold', equipment: { slot: EquipmentSlot.Necklace, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 0, stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 2, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, } },
    { id: 'gold_amulet', name: 'Gold Amulet', description: 'A gold amulet on a string.', stackable: false, value: 900, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'gold', equipment: { slot: EquipmentSlot.Necklace, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 0, stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 3, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, } },
    // Gold Amulets (u)
    { id: 'gold_amulet_u', name: 'Gold Amulet (u)', description: 'An unstrung gold amulet. It needs a string.', stackable: false, value: 880, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'gold' },
    { id: 'sapphire_amulet_u', name: 'Sapphire Amulet (u)', description: 'An unstrung sapphire amulet.', stackable: false, value: 1500, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'sapphire' },
    { id: 'emerald_amulet_u', name: 'Emerald Amulet (u)', description: 'An unstrung emerald amulet.', stackable: false, value: 2500, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'emerald' },
    { id: 'ruby_amulet_u', name: 'Ruby Amulet (u)', description: 'An unstrung ruby amulet.', stackable: false, value: 4500, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'ruby' },
    { id: 'diamond_amulet_u', name: 'Diamond Amulet (u)', description: 'An unstrung diamond amulet.', stackable: false, value: 10000, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'diamond' },
    // Gemmed Rings
    { id: 'sapphire_ring', name: 'Sapphire Ring', description: 'A gold ring set with a beautiful sapphire.', stackable: false, value: 1750, iconUrl: 'https://api.iconify.design/game-icons:ring.svg', material: 'sapphire', equipment: { slot: EquipmentSlot.Ring, magicAttack: 2, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 2, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'emerald_ring', name: 'Emerald Ring', description: 'A gold ring set with a brilliant emerald.', stackable: false, value: 2750, iconUrl: 'https://api.iconify.design/game-icons:ring.svg', material: 'emerald', equipment: { slot: EquipmentSlot.Ring, rangedAttack: 2, stabAttack: 0, slashAttack: 0, crushAttack: 0, magicAttack: 0, stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 2, magicDefence: 0, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'ruby_ring', name: 'Ruby Ring', description: 'A gold ring set with a deep red ruby.', stackable: false, value: 4750, iconUrl: 'https://api.iconify.design/game-icons:ring.svg', material: 'ruby', equipment: { slot: EquipmentSlot.Ring, strengthBonus: 2, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 0, stabDefence: 2, slashDefence: 2, crushDefence: 2, rangedDefence: 0, magicDefence: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'diamond_ring', name: 'Diamond Ring', description: 'A gold ring set with a flawless diamond.', stackable: false, value: 12000, iconUrl: 'https://api.iconify.design/game-icons:ring.svg', material: 'diamond', equipment: { slot: EquipmentSlot.Ring, stabAttack: 2, slashAttack: 2, crushAttack: 2, rangedAttack: 2, magicAttack: 2, stabDefence: 2, slashDefence: 2, crushDefence: 2, rangedDefence: 2, magicDefence: 2, strengthBonus: 2, rangedStrength: 0, magicDamageBonus: 0 } },
    // Gemmed Necklaces
    { id: 'sapphire_necklace', name: 'Sapphire Necklace', description: 'A gold necklace with a beautiful sapphire.', stackable: false, value: 1850, iconUrl: 'https://api.iconify.design/game-icons:necklace.svg', material: 'sapphire', equipment: { slot: EquipmentSlot.Necklace, magicAttack: 4, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 4, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'emerald_necklace', name: 'Emerald Necklace', description: 'A gold necklace with a brilliant emerald.', stackable: false, value: 2850, iconUrl: 'https://api.iconify.design/game-icons:necklace.svg', material: 'emerald', equipment: { slot: EquipmentSlot.Necklace, rangedAttack: 4, stabAttack: 0, slashAttack: 0, crushAttack: 0, magicAttack: 0, stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 4, magicDefence: 0, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'ruby_necklace', name: 'Ruby Necklace', description: 'A gold necklace with a deep red ruby.', stackable: false, value: 4850, iconUrl: 'https://api.iconify.design/game-icons:necklace.svg', material: 'ruby', equipment: { slot: EquipmentSlot.Necklace, strengthBonus: 4, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 0, stabDefence: 4, slashDefence: 4, crushDefence: 4, rangedDefence: 0, magicDefence: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'diamond_necklace', name: 'Diamond Necklace', description: 'A gold necklace with a brilliant diamond.', stackable: false, value: 13000, iconUrl: 'https://api.iconify.design/game-icons:necklace.svg', material: 'diamond', equipment: { slot: EquipmentSlot.Necklace, stabAttack: 4, slashAttack: 4, crushAttack: 4, rangedAttack: 4, magicAttack: 4, stabDefence: 4, slashDefence: 4, crushDefence: 4, rangedDefence: 4, magicDefence: 4, strengthBonus: 4, rangedStrength: 0, magicDamageBonus: 0 } },
    // Gemmed Amulets (strung)
    { id: 'sapphire_amulet', name: 'Sapphire Amulet', description: 'A beautiful sapphire amulet.', stackable: false, value: 2000, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'sapphire', equipment: { slot: EquipmentSlot.Necklace, magicAttack: 5, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 5, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'emerald_amulet', name: 'Emerald Amulet', description: 'A beautiful emerald amulet.', stackable: false, value: 4000, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'emerald', equipment: { slot: EquipmentSlot.Necklace, rangedAttack: 5, stabAttack: 0, slashAttack: 0, crushAttack: 0, magicAttack: 0, stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 5, magicDefence: 0, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'ruby_amulet', name: 'Ruby Amulet', description: 'A beautiful ruby amulet.', stackable: false, value: 8000, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'ruby', equipment: { slot: EquipmentSlot.Necklace, strengthBonus: 5, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 0, stabDefence: 5, slashDefence: 5, crushDefence: 5, rangedDefence: 0, magicDefence: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'diamond_amulet', name: 'Diamond Amulet', description: 'A beautiful diamond amulet.', stackable: false, value: 15000, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'diamond', equipment: { slot: EquipmentSlot.Necklace, stabAttack: 5, slashAttack: 5, crushAttack: 5, rangedAttack: 5, magicAttack: 5, stabDefence: 5, slashDefence: 5, crushDefence: 5, rangedDefence: 5, magicDefence: 5, strengthBonus: 5, rangedStrength: 0, magicDamageBonus: 0 } },
    // Other
    { id: 'wooden_shield', name: 'Wooden Shield', description: 'A simple wooden shield.', stackable: false, value: 15, iconUrl: 'https://api.iconify.design/game-icons:round-shield.svg', material: 'wood-normal', equipment: { slot: EquipmentSlot.Shield, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 0, stabDefence: 4, slashDefence: 5, crushDefence: 3, rangedDefence: 2, magicDefence: 1, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 1 }], } },
    { id: 'goblin_mail', name: 'Goblin Mail', description: 'Crude but effective armor made by goblins.', stackable: false, value: 15, iconUrl: 'https://api.iconify.design/game-icons:mail-shirt.svg', equipment: { slot: EquipmentSlot.Body, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 0, stabDefence: 4, slashDefence: 6, crushDefence: 8, rangedDefence: 0, magicDefence: -4, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, } },
    { id: 'spiked_cape', name: 'Spiked Cape', description: 'A tough leather cape reinforced with sharp iron spikes. Has a chance to damage melee attackers.', stackable: false, value: 800, iconUrl: 'https://api.iconify.design/game-icons:spiked-armor.svg', equipment: { slot: EquipmentSlot.Cape, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 0, stabDefence: 1, slashDefence: 2, crushDefence: 2, rangedDefence: 1, magicDefence: 1, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Defence, level: 20 }], } },
    // Runecrafting Tiaras
    { id: 'silver_tiara', name: 'Silver Tiara', description: 'A beautiful tiara made of silver. It hums with a faint magical potential.', stackable: false, value: 500, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'silver', equipment: { slot: EquipmentSlot.Head, stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 2, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 0, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'gust_tiara', name: 'Gust Tiara', description: 'A silver tiara infused with the power of air. Allows runecrafting without a talisman.', stackable: false, value: 600, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-gust', equipment: { slot: EquipmentSlot.Head, runeType: 'gust_rune', stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 3, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 1, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'binding_tiara', name: 'Binding Tiara', description: 'A silver tiara infused with binding energies. Allows runecrafting without a talisman.', stackable: false, value: 600, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-binding', equipment: { slot: EquipmentSlot.Head, runeType: 'binding_rune', stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 3, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 1, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'stone_tiara', name: 'Stone Tiara', description: 'A silver tiara infused with the power of earth. Allows runecrafting without a talisman.', stackable: false, value: 600, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-stone', equipment: { slot: EquipmentSlot.Head, runeType: 'stone_rune', stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 3, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 1, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'aqua_tiara', name: 'Aqua Tiara', description: 'A silver tiara infused with the power of water. Allows runecrafting without a talisman.', stackable: false, value: 600, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-aqua', equipment: { slot: EquipmentSlot.Head, runeType: 'aqua_rune', stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 3, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 1, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'ember_tiara', name: 'Ember Tiara', description: 'A silver tiara infused with the power of fire. Allows runecrafting without a talisman.', stackable: false, value: 600, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-ember', equipment: { slot: EquipmentSlot.Head, runeType: 'ember_rune', stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 3, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 1, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'flux_tiara', name: 'Flux Tiara', description: 'A silver tiara infused with chaotic energy. Allows runecrafting without a talisman.', stackable: false, value: 700, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-flux', equipment: { slot: EquipmentSlot.Head, runeType: 'flux_rune', stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 3, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 2, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'verdant_tiara', name: 'Verdant Tiara', description: 'A silver tiara infused with the power of nature. Allows runecrafting without a talisman.', stackable: false, value: 700, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-verdant', equipment: { slot: EquipmentSlot.Head, runeType: 'verdant_rune', stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 3, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 2, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'nexus_tiara', name: 'Nexus Tiara', description: 'A silver tiara infused with deathly energies. Allows runecrafting without a talisman.', stackable: false, value: 800, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-nexus', equipment: { slot: EquipmentSlot.Head, runeType: 'nexus_rune', stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 4, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 3, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'hex_tiara', name: 'Hex Tiara', description: 'A silver tiara infused with cursing magic. Allows runecrafting without a talisman.', stackable: false, value: 800, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-hex', equipment: { slot: EquipmentSlot.Head, runeType: 'hex_rune', stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 4, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 3, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'passage_tiara', name: 'Passage Tiara', description: 'A silver tiara infused with the magic of movement. Allows runecrafting without a talisman.', stackable: false, value: 900, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-passage', equipment: { slot: EquipmentSlot.Head, runeType: 'passage_rune', stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 4, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 3, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'anima_tiara', name: 'Anima Tiara', description: 'A silver tiara infused with life force. Allows runecrafting without a talisman.', stackable: false, value: 1000, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-anima', equipment: { slot: EquipmentSlot.Head, runeType: 'anima_rune', stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 5, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 4, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'astral_tiara', name: 'Astral Tiara', description: 'A silver tiara infused with cosmic power. Allows runecrafting without a talisman.', stackable: false, value: 1000, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-astral', equipment: { slot: EquipmentSlot.Head, runeType: 'astral_rune', stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 5, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 4, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },
    { id: 'aether_tiara', name: 'Aether Tiara', description: 'A silver tiara infused with the power of souls. Allows runecrafting without a talisman.', stackable: false, value: 1200, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-aether', equipment: { slot: EquipmentSlot.Head, runeType: 'aether_rune', stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 5, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 4, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0 } },

    // --- MAGIC ARMOR ---
    // Wizard Robes (Lvl 1)
    { id: 'wizard_hat', name: 'Wizard Hat', description: 'A pointy hat for a novice mage.', stackable: false, value: 50, iconUrl: 'https://api.iconify.design/game-icons:pointy-hat.svg', material: 'wizard-blue', equipment: { slot: EquipmentSlot.Head, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 2, stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 2, magicDefence: 2, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Magic, level: 1 }], } },
    { id: 'wizard_robe_top', name: 'Wizard Robe Top', description: 'A simple robe top.', stackable: false, value: 100, iconUrl: 'https://api.iconify.design/game-icons:robe.svg', material: 'wizard-blue', equipment: { slot: EquipmentSlot.Body, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 4, stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 4, magicDefence: 4, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Magic, level: 1 }], } },
    { id: 'wizard_robe_skirt', name: 'Wizard Robe Skirt', description: 'A simple robe skirt.', stackable: false, value: 80, iconUrl: 'https://api.iconify.design/game-icons:skirt.svg', material: 'wizard-blue', equipment: { slot: EquipmentSlot.Legs, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 3, stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 3, magicDefence: 3, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Magic, level: 1 }], } },
    { id: 'wizard_boots', name: 'Wizard Boots', description: 'Pointy-toed boots.', stackable: false, value: 40, iconUrl: 'https://api.iconify.design/game-icons:sonic-shoes.svg', material: 'wizard-blue', equipment: { slot: EquipmentSlot.Boots, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 1, stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 1, magicDefence: 1, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Magic, level: 1 }], } },
    // Affinity Robes (Lvl 30)
    { id: 'affinity_hat', name: 'Affinity Hat', description: 'A hat that hums with magical energy.', stackable: false, value: 2000, iconUrl: 'https://api.iconify.design/game-icons:pointy-hat.svg', material: 'rune-nexus', equipment: { slot: EquipmentSlot.Head, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 6, stabDefence: 2, slashDefence: 2, crushDefence: 2, rangedDefence: 6, magicDefence: 6, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 1, requiredLevels: [{ skill: SkillName.Magic, level: 30 }], } },
    { id: 'affinity_top', name: 'Affinity Top', description: 'A robe top woven with arcane threads.', stackable: false, value: 4000, iconUrl: 'https://api.iconify.design/game-icons:robe.svg', material: 'rune-nexus', equipment: { slot: EquipmentSlot.Body, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 12, stabDefence: 5, slashDefence: 5, crushDefence: 5, rangedDefence: 12, magicDefence: 12, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 2, requiredLevels: [{ skill: SkillName.Magic, level: 30 }], } },
    { id: 'affinity_bottoms', name: 'Affinity Bottoms', description: 'Robe bottoms that crackle with power.', stackable: false, value: 3000, iconUrl: 'https://api.iconify.design/game-icons:pleated-skirt.svg', material: 'rune-nexus', equipment: { slot: EquipmentSlot.Legs, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 8, stabDefence: 3, slashDefence: 3, crushDefence: 3, rangedDefence: 8, magicDefence: 8, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 1, requiredLevels: [{ skill: SkillName.Magic, level: 30 }], } },
    { id: 'affinity_gloves', name: 'Affinity Gloves', description: 'Gloves that make your hands tingle with magic.', stackable: false, value: 1500, iconUrl: 'https://api.iconify.design/game-icons:gloves.svg', material: 'rune-nexus', equipment: { slot: EquipmentSlot.Gloves, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 3, stabDefence: 1, slashDefence: 1, crushDefence: 1, rangedDefence: 3, magicDefence: 3, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Magic, level: 30 }], } },
    { id: 'affinity_boots', name: 'Affinity Boots', description: 'Boots that seem to float slightly above the ground.', stackable: false, value: 1500, iconUrl: 'https://api.iconify.design/game-icons:witch-boot.svg', material: 'rune-nexus', equipment: { slot: EquipmentSlot.Boots, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 3, stabDefence: 1, slashDefence: 1, crushDefence: 1, rangedDefence: 3, magicDefence: 3, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 0, requiredLevels: [{ skill: SkillName.Magic, level: 30 }], } },
    // Robes of Power (Lvl 50)
    { id: 'robe_of_power_hat', name: 'Robe of Power Hat', description: 'A hat that radiates immense magical power.', stackable: false, value: 15000, iconUrl: 'https://api.iconify.design/game-icons:pope-crown.svg', material: 'rune-aether', equipment: { slot: EquipmentSlot.Head, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 10, stabDefence: 4, slashDefence: 4, crushDefence: 4, rangedDefence: 10, magicDefence: 10, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 3, requiredLevels: [{ skill: SkillName.Magic, level: 50 }], } },
    { id: 'robe_of_power_top', name: 'Robe of Power Top', description: 'A robe top that seems woven from pure energy.', stackable: false, value: 30000, iconUrl: 'https://api.iconify.design/game-icons:robe.svg', material: 'rune-aether', equipment: { slot: EquipmentSlot.Body, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 20, stabDefence: 8, slashDefence: 8, crushDefence: 8, rangedDefence: 20, magicDefence: 20, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 5, requiredLevels: [{ skill: SkillName.Magic, level: 50 }], } },
    { id: 'robe_of_power_bottoms', name: 'Robe of Power Bottoms', description: 'Robe bottoms that crackle with untamed power.', stackable: false, value: 20000, iconUrl: 'https://api.iconify.design/game-icons:pleated-skirt.svg', material: 'rune-aether', equipment: { slot: EquipmentSlot.Legs, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 15, stabDefence: 6, slashDefence: 6, crushDefence: 6, rangedDefence: 15, magicDefence: 15, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 4, requiredLevels: [{ skill: SkillName.Magic, level: 50 }], } },
    // Tomes (Craftable)
    { id: 'tome_of_warding', name: 'Tome of Warding', description: 'A book of basic defensive magic.', stackable: false, value: 200, iconUrl: 'https://api.iconify.design/game-icons:book-cover.svg', material: 'leather', equipment: { slot: EquipmentSlot.Shield, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 4, stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 6, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 1, requiredLevels: [{ skill: SkillName.Magic, level: 10 }], } },
    { id: 'tome_of_focus', name: 'Tome of Focus', description: 'A book that helps focus arcane energies.', stackable: false, value: 1000, iconUrl: 'https://api.iconify.design/game-icons:book-cover.svg', material: 'leather', equipment: { slot: EquipmentSlot.Shield, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 8, stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 8, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 2, requiredLevels: [{ skill: SkillName.Magic, level: 20 }], } },
    { id: 'tome_of_power', name: 'Tome of Power', description: 'A book filled with offensive incantations.', stackable: false, value: 2500, iconUrl: 'https://api.iconify.design/game-icons:book-cover.svg', material: 'leather', equipment: { slot: EquipmentSlot.Shield, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 12, stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 10, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 3, requiredLevels: [{ skill: SkillName.Magic, level: 30 }], } },
    { id: 'tome_of_the_arcane', name: 'Tome of the Arcane', description: 'A compendium of advanced magical theory.', stackable: false, value: 6000, iconUrl: 'https://api.iconify.design/game-icons:book-cover.svg', material: 'leather', equipment: { slot: EquipmentSlot.Shield, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 16, stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 12, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 4, requiredLevels: [{ skill: SkillName.Magic, level: 40 }], } },
    { id: 'tome_of_the_master', name: 'Tome of the Master', description: 'A legendary tome containing the secrets of a master mage.', stackable: false, value: 15000, iconUrl: 'https://api.iconify.design/game-icons:book-cover.svg', material: 'leather', equipment: { slot: EquipmentSlot.Shield, stabAttack: 0, slashAttack: 0, crushAttack: 0, rangedAttack: 0, magicAttack: 20, stabDefence: 0, slashDefence: 0, crushDefence: 0, rangedDefence: 0, magicDefence: 15, strengthBonus: 0, rangedStrength: 0, magicDamageBonus: 5, requiredLevels: [{ skill: SkillName.Magic, level: 50 }], } },
];