
import { Item, EquipmentSlot, SkillName } from '../../types';

export const armor: Item[] = [
    // Dragonfire Shield
    { id: 'dragonfire_shield', name: 'Dragonfire Shield', description: 'A shield imbued with magical properties that protect against dragonfire.', stackable: false, value: 500000, iconUrl: 'https://api.iconify.design/game-icons:dragon-shield.svg', material: 'steel', equipment: { slot: EquipmentSlot.Shield, stabDefence: 140, slashDefence: 145, crushDefence: 135, rangedDefence: 130, magicDefence: 30, strengthBonus: 14, requiredLevels: [{ skill: SkillName.Defence, level: 65 }], resistsDragonfire: 0.2 } },
    { id: 'fire_resistant_shield', name: 'Fire-Resistant Shield', description: 'A shield treated to resist dragonfire, though not as effectively as a true dragonfire shield.', stackable: false, value: 200, iconUrl: 'https://api.iconify.design/game-icons:roman-shield.svg', material: 'copper', equipment: { slot: EquipmentSlot.Shield, stabDefence: 7, slashDefence: 9, crushDefence: 6, rangedDefence: 8, magicDefence: 3, requiredLevels: [{ skill: SkillName.Defence, level: 1 }], resistsDragonfire: 0.4 } },
    // Bronze
    { id: 'bronze_full_helm', name: 'Bronze Full Helm', description: 'A helmet that covers the entire head.', stackable: false, value: 44, iconUrl: 'https://api.iconify.design/game-icons:crested-helmet.svg', material: 'bronze', equipment: { slot: EquipmentSlot.Head, magicAttack: -3, stabDefence: 9, slashDefence: 8, crushDefence: 7, rangedDefence: 2, magicDefence: -1, requiredLevels: [{ skill: SkillName.Defence, level: 1 }], } },
    { id: 'bronze_platebody', name: 'Bronze Platebody', description: 'Provides a little protection for the torso.', stackable: false, value: 160, iconUrl: 'https://api.iconify.design/game-icons:breastplate.svg', material: 'bronze', equipment: { slot: EquipmentSlot.Body, magicAttack: -10, stabDefence: 20, slashDefence: 18, crushDefence: 15, rangedDefence: 5, magicDefence: -5, requiredLevels: [{ skill: SkillName.Defence, level: 1 }], } },
    { id: 'bronze_platelegs', name: 'Bronze Platelegs', description: 'Sturdy platelegs made from bronze.', stackable: false, value: 80, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'bronze', equipment: { slot: EquipmentSlot.Legs, magicAttack: -5, stabDefence: 10, slashDefence: 9, crushDefence: 8, rangedDefence: 3, magicDefence: -3, requiredLevels: [{ skill: SkillName.Defence, level: 1 }], } },
    { id: 'bronze_kiteshield', name: 'Bronze Kiteshield', description: 'A large, sturdy shield.', stackable: false, value: 80, iconUrl: 'https://api.iconify.design/game-icons:shield.svg', material: 'bronze', equipment: { slot: EquipmentSlot.Shield, magicAttack: -5, stabDefence: 12, slashDefence: 11, crushDefence: 10, rangedDefence: 5, requiredLevels: [{ skill: SkillName.Defence, level: 1 }], } },
    // Iron
    { id: 'iron_full_helm', name: 'Iron Full Helm', description: 'A sturdy iron helmet.', stackable: false, value: 154, iconUrl: 'https://api.iconify.design/game-icons:crested-helmet.svg', material: 'iron', equipment: { slot: EquipmentSlot.Head, rangedAttack: -2, magicAttack: -3, stabDefence: 15, slashDefence: 14, crushDefence: 13, rangedDefence: 5, magicDefence: -2, requiredLevels: [{ skill: SkillName.Defence, level: 5 }], } },
    { id: 'iron_platebody', name: 'Iron Platebody', description: 'Provides good protection for the torso.', stackable: false, value: 560, iconUrl: 'https://api.iconify.design/game-icons:breastplate.svg', material: 'iron', equipment: { slot: EquipmentSlot.Body, rangedAttack: -10, magicAttack: -15, stabDefence: 35, slashDefence: 33, crushDefence: 30, rangedDefence: 10, magicDefence: -10, requiredLevels: [{ skill: SkillName.Defence, level: 5 }], } },
    { id: 'iron_platelegs', name: 'Iron Platelegs', description: 'Sturdy platelegs made from iron.', stackable: false, value: 280, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'iron', equipment: { slot: EquipmentSlot.Legs, rangedAttack: -5, magicAttack: -7, stabDefence: 25, slashDefence: 23, crushDefence: 20, rangedDefence: 7, magicDefence: -6, requiredLevels: [{ skill: SkillName.Defence, level: 5 }], } },
    { id: 'iron_kiteshield', name: 'Iron Kiteshield', description: 'A large, sturdy iron shield.', stackable: false, value: 238, iconUrl: 'https://api.iconify.design/game-icons:shield.svg', material: 'iron', equipment: { slot: EquipmentSlot.Shield, magicAttack: -8, stabDefence: 20, slashDefence: 18, crushDefence: 16, rangedDefence: 10, magicDefence: -1, requiredLevels: [{ skill: SkillName.Defence, level: 5 }], } },
    // Steel
    { id: 'steel_full_helm', name: 'Steel Full Helm', description: 'A sturdy steel helmet.', stackable: false, value: 550, iconUrl: 'https://api.iconify.design/game-icons:crested-helmet.svg', material: 'steel', equipment: { slot: EquipmentSlot.Head, rangedAttack: -3, magicAttack: -4, stabDefence: 22, slashDefence: 21, crushDefence: 19, rangedDefence: 8, magicDefence: -4, requiredLevels: [{ skill: SkillName.Defence, level: 10 }], } },
    { id: 'steel_platebody', name: 'Steel Platebody', description: 'Provides good protection for the torso.', stackable: false, value: 2000, iconUrl: 'https://api.iconify.design/game-icons:breastplate.svg', material: 'steel', equipment: { slot: EquipmentSlot.Body, rangedAttack: -15, magicAttack: -20, stabDefence: 50, slashDefence: 48, crushDefence: 44, rangedDefence: 15, magicDefence: -15, requiredLevels: [{ skill: SkillName.Defence, level: 10 }], } },
    { id: 'steel_platelegs', name: 'Steel Platelegs', description: 'Sturdy platelegs made from steel.', stackable: false, value: 1000, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'steel', equipment: { slot: EquipmentSlot.Legs, rangedAttack: -7, magicAttack: -10, stabDefence: 38, slashDefence: 36, crushDefence: 32, rangedDefence: 12, magicDefence: -9, requiredLevels: [{ skill: SkillName.Defence, level: 10 }], } },
    { id: 'steel_kiteshield', name: 'Steel Kiteshield', description: 'A large, sturdy steel shield.', stackable: false, value: 850, iconUrl: 'https://api.iconify.design/game-icons:shield.svg', material: 'steel', equipment: { slot: EquipmentSlot.Shield, magicAttack: -10, stabDefence: 30, slashDefence: 28, crushDefence: 25, rangedDefence: 15, magicDefence: -2, requiredLevels: [{ skill: SkillName.Defence, level: 10 }], } },
    // Mithril
    { id: 'mithril_full_helm', name: 'Mithril Full Helm', description: 'A sturdy mithril helmet.', stackable: false, value: 1430, iconUrl: 'https://api.iconify.design/game-icons:crested-helmet.svg', material: 'mithril', equipment: { slot: EquipmentSlot.Head, rangedAttack: -3, magicAttack: -4, stabDefence: 26, slashDefence: 25, crushDefence: 23, rangedDefence: 10, magicDefence: -6, requiredLevels: [{ skill: SkillName.Defence, level: 20 }], } },
    { id: 'mithril_platebody', name: 'Mithril Platebody', description: 'Provides great protection for the torso.', stackable: false, value: 5200, iconUrl: 'https://api.iconify.design/game-icons:breastplate.svg', material: 'mithril', equipment: { slot: EquipmentSlot.Body, rangedAttack: -15, magicAttack: -20, stabDefence: 58, slashDefence: 55, crushDefence: 50, rangedDefence: 18, magicDefence: -18, requiredLevels: [{ skill: SkillName.Defence, level: 20 }], } },
    { id: 'mithril_platelegs', name: 'Mithril Platelegs', description: 'Sturdy platelegs made from mithril.', stackable: false, value: 2600, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'mithril', equipment: { slot: EquipmentSlot.Legs, rangedAttack: -8, magicAttack: -12, stabDefence: 42, slashDefence: 40, crushDefence: 36, rangedDefence: 15, magicDefence: -11, requiredLevels: [{ skill: SkillName.Defence, level: 20 }], } },
    { id: 'mithril_kiteshield', name: 'Mithril Kiteshield', description: 'A large, sturdy mithril shield.', stackable: false, value: 2210, iconUrl: 'https://api.iconify.design/game-icons:shield.svg', material: 'mithril', equipment: { slot: EquipmentSlot.Shield, magicAttack: -10, stabDefence: 35, slashDefence: 33, crushDefence: 30, rangedDefence: 18, magicDefence: -3, requiredLevels: [{ skill: SkillName.Defence, level: 20 }], } },
    // Adamantite
    { id: 'adamantite_full_helm', name: 'Adamantite Full Helm', description: 'A sturdy adamantite helmet.', stackable: false, value: 3520, iconUrl: 'https://api.iconify.design/game-icons:crested-helmet.svg', material: 'adamantite', equipment: { slot: EquipmentSlot.Head, rangedAttack: -4, magicAttack: -5, stabDefence: 32, slashDefence: 30, crushDefence: 28, rangedDefence: 12, magicDefence: -7, requiredLevels: [{ skill: SkillName.Defence, level: 30 }], } },
    { id: 'adamantite_platebody', name: 'Adamantite Platebody', description: 'Provides excellent protection for the torso.', stackable: false, value: 16640, iconUrl: 'https://api.iconify.design/game-icons:breastplate.svg', material: 'adamantite', equipment: { slot: EquipmentSlot.Body, rangedAttack: -20, magicAttack: -25, stabDefence: 65, slashDefence: 62, crushDefence: 58, rangedDefence: 22, magicDefence: -22, requiredLevels: [{ skill: SkillName.Defence, level: 30 }], } },
    { id: 'adamantite_platelegs', name: 'Adamantite Platelegs', description: 'Sturdy platelegs made from adamantite.', stackable: false, value: 2700, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'adamantite', equipment: { slot: EquipmentSlot.Legs, rangedAttack: -10, magicAttack: -15, stabDefence: 50, slashDefence: 48, crushDefence: 44, rangedDefence: 18, magicDefence: -13, requiredLevels: [{ skill: SkillName.Defence, level: 30 }], } },
    { id: 'adamantite_kiteshield', name: 'Adamantite Kiteshield', description: 'A large, sturdy adamantite shield.', stackable: false, value: 6400, iconUrl: 'https://api.iconify.design/game-icons:shield.svg', material: 'adamantite', equipment: { slot: EquipmentSlot.Shield, magicAttack: -12, stabDefence: 42, slashDefence: 40, crushDefence: 38, rangedDefence: 20, magicDefence: -4, requiredLevels: [{ skill: SkillName.Defence, level: 30 }], } },
    // Runic
    { id: 'runic_full_helm', name: 'Runic Full Helm', description: 'A sturdy runic helmet.', stackable: false, value: 35200, iconUrl: 'https://api.iconify.design/game-icons:crested-helmet.svg', material: 'runic', equipment: { slot: EquipmentSlot.Head, rangedAttack: -5, magicAttack: -6, stabDefence: 42, slashDefence: 40, crushDefence: 38, rangedDefence: 15, magicDefence: -8, requiredLevels: [{ skill: SkillName.Defence, level: 40 }], } },
    { id: 'runic_platebody', name: 'Runic Platebody', description: 'Provides excellent protection for the torso.', stackable: false, value: 65000, iconUrl: 'https://api.iconify.design/game-icons:breastplate.svg', material: 'runic', equipment: { slot: EquipmentSlot.Body, rangedAttack: -25, magicAttack: -30, stabDefence: 80, slashDefence: 78, crushDefence: 72, rangedDefence: 28, magicDefence: -25, requiredLevels: [{ skill: SkillName.Defence, level: 40 }], } },
    { id: 'runic_platelegs', name: 'Runic Platelegs', description: 'Sturdy platelegs made from runic metal.', stackable: false, value: 60000, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'runic', equipment: { slot: EquipmentSlot.Legs, rangedAttack: -12, magicAttack: -18, stabDefence: 60, slashDefence: 58, crushDefence: 55, rangedDefence: 22, magicDefence: -15, requiredLevels: [{ skill: SkillName.Defence, level: 40 }], } },
    { id: 'runic_kiteshield', name: 'Runic Kiteshield', description: 'A large, sturdy runic shield.', stackable: false, value: 54400, iconUrl: 'https://api.iconify.design/game-icons:shield.svg', material: 'runic', equipment: { slot: EquipmentSlot.Shield, magicAttack: -15, stabDefence: 52, slashDefence: 50, crushDefence: 48, rangedDefence: 25, magicDefence: -5, requiredLevels: [{ skill: SkillName.Defence, level: 40 }], } },
    // Aquatite
    { id: 'aquatite_full_helm', name: 'Aquatite Full Helm', description: 'A helmet forged from Aquatite. Provides excellent protection, especially against projectiles.', stackable: false, value: 60000, iconUrl: 'https://api.iconify.design/game-icons:crested-helmet.svg', material: 'aquatite', equipment: { slot: EquipmentSlot.Head, magicAttack: -10, rangedAttack: -5, stabDefence: 40, slashDefence: 42, crushDefence: 38, rangedDefence: 45, requiredLevels: [{ skill: SkillName.Defence, level: 60 }], } },
    { id: 'aquatite_platebody', name: 'Aquatite Platebody', description: 'Provides powerful protection for the torso, especially against ranged attacks.', stackable: false, value: 150000, iconUrl: 'https://api.iconify.design/game-icons:breastplate.svg', material: 'aquatite', equipment: { slot: EquipmentSlot.Body, magicAttack: -30, rangedAttack: -15, stabDefence: 95, slashDefence: 92, crushDefence: 88, magicDefence: -5, rangedDefence: 100, requiredLevels: [{ skill: SkillName.Defence, level: 60 }], } },
    { id: 'aquatite_platelegs', name: 'Aquatite Platelegs', description: 'Sturdy platelegs made from Aquatite. Excellent against arrows.', stackable: false, value: 95000, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'aquatite', equipment: { slot: EquipmentSlot.Legs, magicAttack: -21, rangedAttack: -7, stabDefence: 65, slashDefence: 62, crushDefence: 60, magicDefence: -3, rangedDefence: 68, requiredLevels: [{ skill: SkillName.Defence, level: 60 }], } },
    { id: 'aquatite_kiteshield', name: 'Aquatite Kiteshield', description: 'A large, sturdy shield made from Aquatite.', stackable: false, value: 90000, iconUrl: 'https://api.iconify.design/game-icons:shield.svg', material: 'aquatite', equipment: { slot: EquipmentSlot.Shield, magicAttack: -12, rangedAttack: -8, stabDefence: 60, slashDefence: 62, crushDefence: 58, magicDefence: -2, rangedDefence: 65, requiredLevels: [{ skill: SkillName.Defence, level: 60 }], } },
    // --- Leather & Hide ---
    { id: 'leather_body', name: 'Leather Body', description: 'Provides minor protection.', stackable: false, value: 30, iconUrl: 'https://api.iconify.design/game-icons:leather-vest.svg', material: 'leather', equipment: { slot: EquipmentSlot.Body, rangedAttack: 4, magicAttack: -5, stabDefence: 5, slashDefence: 8, crushDefence: 7, rangedDefence: 6, magicDefence: 4, requiredLevels: [{ skill: SkillName.Defence, level: 1 }], } },
    { id: 'leather_gloves', name: 'Leather Gloves', description: 'Simple leather gloves.', stackable: false, value: 15, iconUrl: 'https://api.iconify.design/game-icons:gloves.svg', material: 'leather', equipment: { slot: EquipmentSlot.Gloves, rangedAttack: 1, stabDefence: 1, slashDefence: 1, crushDefence: 1, rangedDefence: 1, requiredLevels: [{ skill: SkillName.Defence, level: 1 }], } },
    { id: 'leather_boots', name: 'Leather Boots', description: 'Simple leather boots.', stackable: false, value: 15, iconUrl: 'https://api.iconify.design/game-icons:boots.svg', material: 'leather', equipment: { slot: EquipmentSlot.Boots, stabDefence: 1, slashDefence: 1, crushDefence: 1, rangedDefence: 1, requiredLevels: [{ skill: SkillName.Defence, level: 1 }], } },
    { id: 'leather_cowl', name: 'Leather Cowl', description: 'A simple leather hood.', stackable: false, value: 20, iconUrl: 'https://api.iconify.design/game-icons:light-helm.svg', material: 'leather', equipment: { slot: EquipmentSlot.Head, rangedAttack: 1, magicAttack: -1, stabDefence: 1, slashDefence: 2, crushDefence: 2, rangedDefence: 1, magicDefence: 1, requiredLevels: [ { skill: SkillName.Defence, level: 1 }, { skill: SkillName.Ranged, level: 1 }, ], } },
    { id: 'leather_vambraces', name: 'Leather Vambraces', description: 'Sturdy leather arm guards.', stackable: false, value: 25, iconUrl: 'https://api.iconify.design/game-icons:bracers.svg', material: 'leather', equipment: { slot: EquipmentSlot.Gloves, rangedAttack: 2, magicAttack: -1, stabDefence: 1, slashDefence: 2, crushDefence: 1, rangedDefence: 1, magicDefence: 1, requiredLevels: [ { skill: SkillName.Defence, level: 1 }, { skill: SkillName.Ranged, level: 1 }, ], } },
    { id: 'leather_chaps', name: 'Leather Chaps', description: 'Protective leather leg coverings.', stackable: false, value: 25, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'leather', equipment: { slot: EquipmentSlot.Legs, rangedAttack: 2, magicAttack: -2, stabDefence: 2, slashDefence: 4, crushDefence: 3, rangedDefence: 3, magicDefence: 2, requiredLevels: [{ skill: SkillName.Defence, level: 1 }], } },
    // Boar Hide (Level 9)
    { id: 'boar_hide_cowl', name: 'Boar Hide Cowl', description: 'A sturdy cowl made from boar hide.', stackable: false, value: 40, iconUrl: 'https://api.iconify.design/game-icons:light-helm.svg', material: 'leather', equipment: { slot: EquipmentSlot.Head, requiredLevels: [{ skill: SkillName.Defence, level: 1 }, { skill: SkillName.Ranged, level: 5 }], rangedAttack: 1, stabDefence: 2, slashDefence: 3, crushDefence: 3, rangedDefence: 2, magicAttack: -1, magicDefence: 2 } },
    { id: 'boar_hide_body', name: 'Boar Hide Body', description: 'A tough body armor made from boar hide.', stackable: false, value: 100, iconUrl: 'https://api.iconify.design/game-icons:leather-vest.svg', material: 'leather', equipment: { slot: EquipmentSlot.Body, requiredLevels: [{ skill: SkillName.Defence, level: 5 }, { skill: SkillName.Ranged, level: 5 }], rangedAttack: 4, stabDefence: 12, slashDefence: 14, crushDefence: 15, rangedDefence: 10, magicAttack: -7, magicDefence: 6 } },
    { id: 'boar_hide_chaps', name: 'Boar Hide Chaps', description: 'Protective chaps made from boar hide.', stackable: false, value: 60, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'leather', equipment: { slot: EquipmentSlot.Legs, requiredLevels: [{ skill: SkillName.Defence, level: 1 }, { skill: SkillName.Ranged, level: 5 }], rangedAttack: 2, stabDefence: 6, slashDefence: 8, crushDefence: 9, rangedDefence: 5, magicAttack: -3, magicDefence: 4 } },
    { id: 'boar_hide_vambraces', name: 'Boar Hide Vambraces', description: 'Vambraces made from tough boar hide.', stackable: false, value: 40, iconUrl: 'https://api.iconify.design/game-icons:bracers.svg', material: 'leather', equipment: { slot: EquipmentSlot.Gloves, requiredLevels: [{ skill: SkillName.Defence, level: 1 }, { skill: SkillName.Ranged, level: 5 }], rangedAttack: 3, stabDefence: 1, slashDefence: 2, crushDefence: 2, rangedDefence: 1, magicAttack: -2, magicDefence: 2 } },
    // Wolf Pelt (Level 18)
    { id: 'wolf_pelt_cowl', name: 'Wolf Pelt Cowl', description: 'A cowl made from wolf fur.', stackable: false, value: 80, iconUrl: 'https://api.iconify.design/game-icons:light-helm.svg', material: 'leather', equipment: { slot: EquipmentSlot.Head, requiredLevels: [{ skill: SkillName.Defence, level: 1 }, { skill: SkillName.Ranged, level: 10 }], rangedAttack: 2, stabDefence: 4, slashDefence: 5, crushDefence: 5, rangedDefence: 3, magicAttack: -2, magicDefence: 3 } },
    { id: 'wolf_pelt_body', name: 'Wolf Pelt Body', description: 'A body armor made from wolf fur, offering a strength bonus.', stackable: false, value: 200, iconUrl: 'https://api.iconify.design/game-icons:leather-vest.svg', material: 'leather', equipment: { slot: EquipmentSlot.Body, requiredLevels: [{ skill: SkillName.Defence, level: 10 }, { skill: SkillName.Ranged, level: 10 }], rangedAttack: 8, stabDefence: 18, slashDefence: 22, crushDefence: 20, rangedDefence: 15, strengthBonus: 1, magicAttack: -8, magicDefence: 8 } },
    { id: 'wolf_pelt_chaps', name: 'Wolf Pelt Chaps', description: 'Chaps made from wolf fur.', stackable: false, value: 120, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'leather', equipment: { slot: EquipmentSlot.Legs, requiredLevels: [{ skill: SkillName.Defence, level: 1 }, { skill: SkillName.Ranged, level: 10 }], rangedAttack: 4, stabDefence: 10, slashDefence: 13, crushDefence: 11, rangedDefence: 8, magicAttack: -4, magicDefence: 5 } },
    { id: 'wolf_pelt_vambraces', name: 'Wolf Pelt Vambraces', description: 'Vambraces made from wolf fur, offering a strength bonus.', stackable: false, value: 80, iconUrl: 'https://api.iconify.design/game-icons:bracers.svg', material: 'leather', equipment: { slot: EquipmentSlot.Gloves, requiredLevels: [{ skill: SkillName.Defence, level: 1 }, { skill: SkillName.Ranged, level: 10 }], rangedAttack: 5, stabDefence: 3, slashDefence: 4, crushDefence: 3, rangedDefence: 2, strengthBonus: 1, magicAttack: -1, magicDefence: 3 } },
    { id: 'wolf_pelt_cloak', name: 'Wolf Pelt Cloak', description: 'A warm cloak made from the pelt of a wolf.', stackable: false, value: 150, iconUrl: 'https://api.iconify.design/game-icons:cloak.svg', material: 'leather', equipment: { slot: EquipmentSlot.Cape, requiredLevels: [{ skill: SkillName.Defence, level: 1 }], stabDefence: 1, slashDefence: 2, crushDefence: 2, rangedDefence: 1, magicAttack: -1, magicDefence: 1 } },
    // Bear Hide (Level 32)
    { id: 'bear_hide_cowl', name: 'Bear Hide Cowl', description: 'A thick cowl made from bear hide.', stackable: false, value: 150, iconUrl: 'https://api.iconify.design/game-icons:light-helm.svg', material: 'leather', equipment: { slot: EquipmentSlot.Head, requiredLevels: [{ skill: SkillName.Defence, level: 1 }, { skill: SkillName.Ranged, level: 20 }], rangedAttack: 3, stabDefence: 6, slashDefence: 7, crushDefence: 6, rangedDefence: 5, magicAttack: -2, magicDefence: 4 } },
    { id: 'bear_hide_body', name: 'Bear Hide Body', description: 'A heavy body armor made from bear hide.', stackable: false, value: 350, iconUrl: 'https://api.iconify.design/game-icons:leather-vest.svg', material: 'leather', equipment: { slot: EquipmentSlot.Body, requiredLevels: [{ skill: SkillName.Defence, level: 20 }, { skill: SkillName.Ranged, level: 20 }], rangedAttack: 12, stabDefence: 26, slashDefence: 30, crushDefence: 28, rangedDefence: 22, magicAttack: -12, magicDefence: 10 } },
    { id: 'bear_hide_chaps', name: 'Bear Hide Chaps', description: 'Thick chaps made from bear hide.', stackable: false, value: 250, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'leather', equipment: { slot: EquipmentSlot.Legs, requiredLevels: [{ skill: SkillName.Defence, level: 1 }, { skill: SkillName.Ranged, level: 20 }], rangedAttack: 6, stabDefence: 15, slashDefence: 18, crushDefence: 16, rangedDefence: 12, magicAttack: -7, magicDefence: 6 } },
    { id: 'bear_hide_vambraces', name: 'Bear Hide Vambraces', description: 'Heavy vambraces made from bear hide.', stackable: false, value: 150, iconUrl: 'https://api.iconify.design/game-icons:bracers.svg', material: 'leather', equipment: { slot: EquipmentSlot.Gloves, requiredLevels: [{ skill: SkillName.Defence, level: 1 }, { skill: SkillName.Ranged, level: 20 }], rangedAttack: 7, stabDefence: 5, slashDefence: 6, crushDefence: 5, rangedDefence: 4, magicAttack: -2, magicDefence: 4 } },
    
    // Dragonhide
    { id: 'grovehide_coif', name: 'Grove Hide Coif', description: 'A coif made from the hide of a Grove Dragon.', stackable: false, value: 1800, iconUrl: 'https://api.iconify.design/game-icons:light-helm.svg', material: 'emerald', equipment: { slot: EquipmentSlot.Head, requiredLevels: [{ skill: SkillName.Ranged, level: 40 }], rangedAttack: 4, stabDefence: 7, slashDefence: 8, crushDefence: 7, rangedDefence: 6, magicDefence: 5 } },
    { id: 'grovehide_body', name: 'Grove Hide Body', description: 'A body made from the hide of a Grove Dragon.', stackable: false, value: 4500, iconUrl: 'https://api.iconify.design/game-icons:leather-vest.svg', material: 'emerald', equipment: { slot: EquipmentSlot.Body, requiredLevels: [{ skill: SkillName.Ranged, level: 40 }, { skill: SkillName.Defence, level: 40 }], rangedAttack: 15, stabDefence: 30, slashDefence: 35, crushDefence: 32, rangedDefence: 38, magicDefence: 10 } },
    { id: 'grovehide_legs', name: 'Grove Hide Legs', description: 'Chaps made from the hide of a Grove Dragon.', stackable: false, value: 3000, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'emerald', equipment: { slot: EquipmentSlot.Legs, requiredLevels: [{ skill: SkillName.Ranged, level: 40 }], rangedAttack: 8, stabDefence: 18, slashDefence: 22, crushDefence: 20, rangedDefence: 25, magicDefence: 8 } },
    { id: 'grovehide_vambs', name: 'Grove Hide Vambraces', description: 'Vambraces made from the hide of a Grove Dragon.', stackable: false, value: 1500, iconUrl: 'https://api.iconify.design/game-icons:bracers.svg', material: 'emerald', equipment: { slot: EquipmentSlot.Gloves, requiredLevels: [{ skill: SkillName.Ranged, level: 40 }], rangedAttack: 8, stabDefence: 4, slashDefence: 5, crushDefence: 4, rangedDefence: 6, magicDefence: 4 } },
    { id: 'frosthide_coif', name: 'Frost Hide Coif', description: 'A coif made from the hide of a Frosthide Dragon.', stackable: false, value: 2400, iconUrl: 'https://api.iconify.design/game-icons:light-helm.svg', material: 'sapphire', equipment: { slot: EquipmentSlot.Head, requiredLevels: [{ skill: SkillName.Ranged, level: 50 }], rangedAttack: 5, stabDefence: 8, slashDefence: 9, crushDefence: 8, rangedDefence: 7, magicDefence: 6 } },
    { id: 'frosthide_body', name: 'Frost Hide Body', description: 'A body made from the hide of a Frosthide Dragon.', stackable: false, value: 6000, iconUrl: 'https://api.iconify.design/game-icons:leather-vest.svg', material: 'sapphire', equipment: { slot: EquipmentSlot.Body, requiredLevels: [{ skill: SkillName.Ranged, level: 50 }, { skill: SkillName.Defence, level: 40 }], rangedAttack: 20, stabDefence: 35, slashDefence: 40, crushDefence: 38, rangedDefence: 45, magicDefence: 15 } },
    { id: 'frosthide_legs', name: 'Frost Hide Legs', description: 'Chaps made from the hide of a Frosthide Dragon.', stackable: false, value: 4000, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'sapphire', equipment: { slot: EquipmentSlot.Legs, requiredLevels: [{ skill: SkillName.Ranged, level: 50 }], rangedAttack: 11, stabDefence: 22, slashDefence: 26, crushDefence: 24, rangedDefence: 30, magicDefence: 10 } },
    { id: 'frosthide_vambs', name: 'Frost Hide Vambraces', description: 'Vambraces made from the hide of a Frosthide Dragon.', stackable: false, value: 2000, iconUrl: 'https://api.iconify.design/game-icons:bracers.svg', material: 'sapphire', equipment: { slot: EquipmentSlot.Gloves, requiredLevels: [{ skill: SkillName.Ranged, level: 50 }], rangedAttack: 9, stabDefence: 5, slashDefence: 6, crushDefence: 5, rangedDefence: 7, magicDefence: 5 } },
    { id: 'emberscale_coif', name: 'Emberscale Coif', description: 'A coif made from the hide of an Emberscale Dragon.', stackable: false, value: 3200, iconUrl: 'https://api.iconify.design/game-icons:light-helm.svg', material: 'ruby', equipment: { slot: EquipmentSlot.Head, requiredLevels: [{ skill: SkillName.Ranged, level: 60 }], rangedAttack: 6, stabDefence: 9, slashDefence: 10, crushDefence: 9, rangedDefence: 8, magicDefence: 7 } },
    { id: 'emberscale_body', name: 'Emberscale Body', description: 'A body made from the hide of an Emberscale Dragon.', stackable: false, value: 8000, iconUrl: 'https://api.iconify.design/game-icons:leather-vest.svg', material: 'ruby', equipment: { slot: EquipmentSlot.Body, requiredLevels: [{ skill: SkillName.Ranged, level: 60 }, { skill: SkillName.Defence, level: 40 }], rangedAttack: 25, stabDefence: 40, slashDefence: 45, crushDefence: 42, rangedDefence: 52, magicDefence: 20 } },
    { id: 'emberscale_legs', name: 'Emberscale Legs', description: 'Chaps made from the hide of an Emberscale Dragon.', stackable: false, value: 5400, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'ruby', equipment: { slot: EquipmentSlot.Legs, requiredLevels: [{ skill: SkillName.Ranged, level: 60 }], rangedAttack: 14, stabDefence: 26, slashDefence: 30, crushDefence: 28, rangedDefence: 35, magicDefence: 12 } },
    { id: 'emberscale_vambs', name: 'Emberscale Vambraces', description: 'Vambraces made from the hide of an Emberscale Dragon.', stackable: false, value: 2700, iconUrl: 'https://api.iconify.design/game-icons:bracers.svg', material: 'ruby', equipment: { slot: EquipmentSlot.Gloves, requiredLevels: [{ skill: SkillName.Ranged, level: 60 }], rangedAttack: 10, stabDefence: 6, slashDefence: 7, crushDefence: 6, rangedDefence: 8, magicDefence: 6 } },
    { id: 'deathscythe_coif', name: 'Deathscythe Coif', description: 'A coif made from the hide of a Deathscythe.', stackable: false, value: 4500, iconUrl: 'https://api.iconify.design/game-icons:light-helm.svg', material: 'burnt', equipment: { slot: EquipmentSlot.Head, requiredLevels: [{ skill: SkillName.Ranged, level: 70 }], rangedAttack: 7, stabDefence: 10, slashDefence: 12, crushDefence: 11, rangedDefence: 9, magicDefence: 8 } },
    { id: 'deathscythe_body', name: 'Deathscythe Body', description: 'A body made from the hide of a Deathscythe.', stackable: false, value: 11000, iconUrl: 'https://api.iconify.design/game-icons:leather-vest.svg', material: 'burnt', equipment: { slot: EquipmentSlot.Body, requiredLevels: [{ skill: SkillName.Ranged, level: 70 }, { skill: SkillName.Defence, level: 40 }], rangedAttack: 30, stabDefence: 45, slashDefence: 50, crushDefence: 48, rangedDefence: 60, magicDefence: 25 } },
    { id: 'deathscythe_legs', name: 'Deathscythe Legs', description: 'Chaps made from the hide of a Deathscythe.', stackable: false, value: 7500, iconUrl: 'https://api.iconify.design/game-icons:armored-pants.svg', material: 'burnt', equipment: { slot: EquipmentSlot.Legs, requiredLevels: [{ skill: SkillName.Ranged, level: 70 }], rangedAttack: 17, stabDefence: 30, slashDefence: 35, crushDefence: 32, rangedDefence: 40, magicDefence: 15 } },
    { id: 'deathscythe_vambs', name: 'Deathscythe Vambraces', description: 'Vambraces made from the hide of a Deathscythe.', stackable: false, value: 3800, iconUrl: 'https://api.iconify.design/game-icons:bracers.svg', material: 'burnt', equipment: { slot: EquipmentSlot.Gloves, requiredLevels: [{ skill: SkillName.Ranged, level: 70 }], rangedAttack: 11, stabDefence: 7, slashDefence: 8, crushDefence: 7, rangedDefence: 9, magicDefence: 7 } },

    // Jewelry
    { id: 'silver_ring', name: 'Silver Ring', description: 'A simple silver ring.', stackable: false, value: 80, iconUrl: 'https://api.iconify.design/game-icons:ring.svg', material: 'silver', equipment: { slot: EquipmentSlot.Ring } },
    { id: 'silver_necklace', name: 'Silver Necklace', description: 'A simple silver necklace.', stackable: false, value: 90, iconUrl: 'https://api.iconify.design/game-icons:necklace.svg', material: 'silver', equipment: { slot: EquipmentSlot.Necklace } },
    { id: 'silver_amulet', name: 'Silver Amulet', description: 'A simple silver amulet on a string.', stackable: false, value: 90, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'silver', equipment: { slot: EquipmentSlot.Necklace } },
    { id: 'gold_ring', name: 'Gold Ring', description: 'A simple gold ring.', stackable: false, value: 150, iconUrl: 'https://api.iconify.design/game-icons:ring.svg', material: 'gold', equipment: { slot: EquipmentSlot.Ring } },
    { id: 'gold_necklace', name: 'Gold Necklace', description: 'A simple gold necklace.', stackable: false, value: 180, iconUrl: 'https://api.iconify.design/game-icons:necklace.svg', material: 'gold', equipment: { slot: EquipmentSlot.Necklace } },
    { id: 'gold_amulet', name: 'Gold Amulet', description: 'A gold amulet on a string.', stackable: false, value: 190, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'gold', equipment: { slot: EquipmentSlot.Necklace } },
    // Gold Amulets (u)
    { id: 'gold_amulet_u', name: 'Gold Amulet (u)', description: 'An unstrung gold amulet. It needs a string.', stackable: false, value: 180, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'gold' },
    { id: 'sapphire_amulet_u', name: 'Sapphire Amulet (u)', description: 'An unstrung sapphire amulet.', stackable: false, value: 690, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'sapphire' },
    { id: 'emerald_amulet_u', name: 'Emerald Amulet (u)', description: 'An unstrung emerald amulet.', stackable: false, value: 1290, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'emerald' },
    { id: 'ruby_amulet_u', name: 'Ruby Amulet (u)', description: 'An unstrung ruby amulet.', stackable: false, value: 1940, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'ruby' },
    { id: 'diamond_amulet_u', name: 'Diamond Amulet (u)', description: 'An unstrung diamond amulet.', stackable: false, value: 2690, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'diamond' },
    { id: 'sunstone_amulet_u', name: 'Sunstone Amulet (u)', description: 'An unstrung sunstone amulet.', stackable: false, value: 28990, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'sunstone' },
    // Gemmed Rings
    { id: 'sapphire_ring', name: 'Sapphire Ring', description: 'A gold ring set with a beautiful sapphire.', stackable: false, value: 600, iconUrl: 'https://api.iconify.design/game-icons:ring.svg', material: 'sapphire', equipment: { slot: EquipmentSlot.Ring } },
    { id: 'emerald_ring', name: 'Emerald Ring', description: 'A gold ring set with a brilliant emerald.', stackable: false, value: 1200, iconUrl: 'https://api.iconify.design/game-icons:ring.svg', material: 'emerald', equipment: { slot: EquipmentSlot.Ring } },
    { id: 'ruby_ring', name: 'Ruby Ring', description: 'A gold ring set with a deep red ruby.', stackable: false, value: 1850, iconUrl: 'https://api.iconify.design/game-icons:ring.svg', material: 'ruby', equipment: { slot: EquipmentSlot.Ring } },
    { id: 'diamond_ring', name: 'Diamond Ring', description: 'A gold ring set with a flawless diamond.', stackable: false, value: 2600, iconUrl: 'https://api.iconify.design/game-icons:ring.svg', material: 'diamond', equipment: { slot: EquipmentSlot.Ring } },
    { id: 'sunstone_ring', name: 'Sunstone Ring', description: 'A gold ring set with a flawless sunstone.', stackable: false, value: 27000, iconUrl: 'https://api.iconify.design/game-icons:ring.svg', material: 'sunstone', equipment: { slot: EquipmentSlot.Ring } },
    // Gemmed Necklaces
    { id: 'sapphire_necklace', name: 'Sapphire Necklace', description: 'A gold necklace with a beautiful sapphire.', stackable: false, value: 700, iconUrl: 'https://api.iconify.design/game-icons:necklace.svg', material: 'sapphire', equipment: { slot: EquipmentSlot.Necklace } },
    { id: 'emerald_necklace', name: 'Emerald Necklace', description: 'A gold necklace with a brilliant emerald.', stackable: false, value: 1300, iconUrl: 'https://api.iconify.design/game-icons:necklace.svg', material: 'emerald', equipment: { slot: EquipmentSlot.Necklace } },
    { id: 'ruby_necklace', name: 'Ruby Necklace', description: 'A gold necklace with a deep red ruby.', stackable: false, value: 1950, iconUrl: 'https://api.iconify.design/game-icons:necklace.svg', material: 'ruby', equipment: { slot: EquipmentSlot.Necklace } },
    { id: 'diamond_necklace', name: 'Diamond Necklace', description: 'A gold necklace with a brilliant diamond.', stackable: false, value: 2700, iconUrl: 'https://api.iconify.design/game-icons:necklace.svg', material: 'diamond', equipment: { slot: EquipmentSlot.Necklace } },
    { id: 'sunstone_necklace', name: 'Sunstone Necklace', description: 'A gold necklace with a brilliant sunstone.', stackable: false, value: 29000, iconUrl: 'https://api.iconify.design/game-icons:necklace.svg', material: 'sunstone', equipment: { slot: EquipmentSlot.Necklace } },
    // Gemmed Amulets (strung)
    { id: 'sapphire_amulet', name: 'Sapphire Amulet', description: 'A beautiful sapphire amulet.', stackable: false, value: 700, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'sapphire', equipment: { slot: EquipmentSlot.Necklace } },
    { id: 'emerald_amulet', name: 'Emerald Amulet', description: 'A beautiful emerald amulet.', stackable: false, value: 1300, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'emerald', equipment: { slot: EquipmentSlot.Necklace } },
    { id: 'ruby_amulet', name: 'Ruby Amulet', description: 'A beautiful ruby amulet.', stackable: false, value: 1950, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'ruby', equipment: { slot: EquipmentSlot.Necklace } },
    { id: 'diamond_amulet', name: 'Diamond Amulet', description: 'A beautiful diamond amulet.', stackable: false, value: 2700, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'diamond', equipment: { slot: EquipmentSlot.Necklace } },
    { id: 'sunstone_amulet', name: 'Sunstone Amulet', description: 'A beautiful sunstone amulet.', stackable: false, value: 29000, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'sunstone', equipment: { slot: EquipmentSlot.Necklace } },
    // Other
    { id: 'wooden_shield', name: 'Wooden Shield', description: 'A simple wooden shield.', stackable: false, value: 15, iconUrl: 'https://api.iconify.design/game-icons:round-shield.svg', material: 'wood-normal', equipment: { slot: EquipmentSlot.Shield, stabDefence: 4, slashDefence: 5, crushDefence: 3, rangedDefence: 2, magicDefence: 1, requiredLevels: [{ skill: SkillName.Defence, level: 1 }], } },
    { id: 'pregais_shield', name: "Pregai's Old Shield", description: 'A sturdy steel shield, weathered by countless battles. It seems to react to the presence of the undead.', stackable: false, value: 3000, iconUrl: 'https://api.iconify.design/game-icons:round-shield.svg', material: 'steel', equipment: { slot: EquipmentSlot.Shield, stabDefence: 22, slashDefence: 24, crushDefence: 20, rangedDefence: 18, magicDefence: 2, requiredLevels: [{ skill: SkillName.Defence, level: 25 }] } },
    { id: 'goblin_mail', name: 'Goblin Mail', description: 'Crude but effective armor made by goblins.', stackable: false, value: 15, iconUrl: 'https://api.iconify.design/game-icons:mail-shirt.svg', equipment: { slot: EquipmentSlot.Body, stabDefence: 4, slashDefence: 6, crushDefence: 8, magicDefence: -4 } },
    { id: 'spiked_cape', name: 'Spiked Cape', description: 'A tough leather cape reinforced with sharp iron spikes. Has a chance to damage melee attackers.', stackable: false, value: 800, iconUrl: 'https://api.iconify.design/game-icons:cloak.svg', equipment: { slot: EquipmentSlot.Cape, stabDefence: 1, slashDefence: 2, crushDefence: 2, rangedDefence: 1, magicDefence: 1, requiredLevels: [{ skill: SkillName.Defence, level: 20 }], } },
    // Runecrafting Tiaras
    { id: 'silver_tiara', name: 'Silver Tiara', description: 'A beautiful tiara made of silver. It hums with a faint magical potential.', stackable: false, value: 100, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'silver', equipment: { slot: EquipmentSlot.Head, magicDefence: 2 } },
    { id: 'gust_tiara', name: 'Gust Tiara', description: 'A silver tiara infused with the power of air. Allows runecrafting without a talisman.', stackable: false, value: 120, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-gust', equipment: { slot: EquipmentSlot.Head, runeType: 'gust_rune', magicDefence: 3, magicAttack: 1 } },
    { id: 'binding_tiara', name: 'Binding Tiara', description: 'A silver tiara infused with binding energies. Allows runecrafting without a talisman.', stackable: false, value: 120, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-binding', equipment: { slot: EquipmentSlot.Head, runeType: 'binding_rune', magicDefence: 3, magicAttack: 1 } },
    { id: 'stone_tiara', name: 'Stone Tiara', description: 'A silver tiara infused with the power of earth. Allows runecrafting without a talisman.', stackable: false, value: 120, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-stone', equipment: { slot: EquipmentSlot.Head, runeType: 'stone_rune', magicDefence: 3, magicAttack: 1 } },
    { id: 'aqua_tiara', name: 'Aqua Tiara', description: 'A silver tiara infused with the power of water. Allows runecrafting without a talisman.', stackable: false, value: 120, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-aqua', equipment: { slot: EquipmentSlot.Head, runeType: 'aqua_rune', magicDefence: 3, magicAttack: 1 } },
    { id: 'ember_tiara', name: 'Ember Tiara', description: 'A silver tiara infused with the power of fire. Allows runecrafting without a talisman.', stackable: false, value: 120, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-ember', equipment: { slot: EquipmentSlot.Head, runeType: 'ember_rune', magicDefence: 3, magicAttack: 1 } },
    { id: 'flux_tiara', name: 'Flux Tiara', description: 'A silver tiara infused with chaotic energy. Allows runecrafting without a talisman.', stackable: false, value: 150, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-flux', equipment: { slot: EquipmentSlot.Head, runeType: 'flux_rune', magicDefence: 3, magicAttack: 2 } },
    { id: 'verdant_tiara', name: 'Verdant Tiara', description: 'A silver tiara infused with the power of nature. Allows runecrafting without a talisman.', stackable: false, value: 150, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-verdant', equipment: { slot: EquipmentSlot.Head, runeType: 'verdant_rune', magicDefence: 3, magicAttack: 2 } },
    { id: 'nexus_tiara', name: 'Nexus Tiara', description: 'A silver tiara infused with deathly energies. Allows runecrafting without a talisman.', stackable: false, value: 200, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'burnt', equipment: { slot: EquipmentSlot.Head, runeType: 'nexus_rune', magicDefence: 4, magicAttack: 3 } },
    { id: 'hex_tiara', name: 'Hex Tiara', description: 'A silver tiara infused with cursing magic. Allows runecrafting without a talisman.', stackable: false, value: 200, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-hex', equipment: { slot: EquipmentSlot.Head, runeType: 'hex_rune', magicDefence: 4, magicAttack: 3 } },
    { id: 'passage_tiara', name: 'Passage Tiara', description: 'A silver tiara infused with the magic of movement. Allows runecrafting without a talisman.', stackable: false, value: 200, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-passage', equipment: { slot: EquipmentSlot.Head, runeType: 'passage_rune', magicDefence: 4, magicAttack: 3 } },
    { id: 'anima_tiara', name: 'Anima Tiara', description: 'A silver tiara infused with life force. Allows runecrafting without a talisman.', stackable: false, value: 200, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-anima', equipment: { slot: EquipmentSlot.Head, runeType: 'anima_rune', magicDefence: 5, magicAttack: 4 } },
    { id: 'astral_tiara', name: 'Astral Tiara', description: 'A silver tiara infused with cosmic power. Allows runecrafting without a talisman.', stackable: false, value: 250, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-astral', equipment: { slot: EquipmentSlot.Head, runeType: 'astral_rune', magicDefence: 5, magicAttack: 4 } },
    { id: 'aether_tiara', name: 'Aether Tiara', description: 'A silver tiara infused with the power of souls. Allows runecrafting without a talisman.', stackable: false, value: 250, iconUrl: 'https://api.iconify.design/game-icons:tiara.svg', material: 'rune-aether', equipment: { slot: EquipmentSlot.Head, runeType: 'aether_rune', magicDefence: 5, magicAttack: 4 } },

    // --- MAGIC ARMOR ---
    // Wizard Robes (Lvl 1)
    { id: 'wizard_hat', name: 'Wizard Hat', description: 'A pointy hat for a novice mage.', stackable: false, value: 50, iconUrl: 'https://api.iconify.design/game-icons:pointy-hat.svg', material: 'wizard-blue', equipment: { slot: EquipmentSlot.Head, magicAttack: 2, magicDefence: 2, requiredLevels: [{ skill: SkillName.Magic, level: 1 }], } },
    { id: 'wizard_robe_top', name: 'Wizard Robe Top', description: 'A simple robe top.', stackable: false, value: 100, iconUrl: 'https://api.iconify.design/game-icons:robe.svg', material: 'wizard-blue', equipment: { slot: EquipmentSlot.Body, magicAttack: 4, magicDefence: 4, requiredLevels: [{ skill: SkillName.Magic, level: 1 }], } },
    { id: 'wizard_robe_skirt', name: 'Wizard Robe Skirt', description: 'A simple robe skirt.', stackable: false, value: 80, iconUrl: 'https://api.iconify.design/game-icons:skirt.svg', material: 'wizard-blue', equipment: { slot: EquipmentSlot.Legs, magicAttack: 3, magicDefence: 3, requiredLevels: [{ skill: SkillName.Magic, level: 1 }], } },
    { id: 'wizard_boots', name: 'Wizard Boots', description: 'Pointy-toed boots.', stackable: false, value: 40, iconUrl: 'https://api.iconify.design/game-icons:sonic-shoes.svg', material: 'wizard-blue', equipment: { slot: EquipmentSlot.Boots, magicAttack: 2, magicDefence: 2, requiredLevels: [{ skill: SkillName.Magic, level: 1 }], } },
    { id: 'wizard_gloves', name: 'Wizard Gloves', description: 'Vibrant blue gloves worn by mages.', stackable: false, value: 40, iconUrl: 'https://api.iconify.design/game-icons:gloves.svg', material: 'wizard-blue', equipment: { slot: EquipmentSlot.Gloves, magicAttack: 2, magicDefence: 2, requiredLevels: [{ skill: SkillName.Magic, level: 1 }], } },
    // Affinity Robes (Lvl 30)
    { id: 'affinity_hat', name: 'Affinity Hat', description: 'A hat that hums with magical energy.', stackable: false, value: 2000, iconUrl: 'https://api.iconify.design/game-icons:pointy-hat.svg', material: 'tenebrite', equipment: { slot: EquipmentSlot.Head, magicAttack: 6, magicDefence: 6, requiredLevels: [{ skill: SkillName.Magic, level: 30 }], } },
    { id: 'affinity_top', name: 'Affinity Top', description: 'A robe top woven with arcane threads.', stackable: false, value: 4000, iconUrl: 'https://api.iconify.design/game-icons:robe.svg', material: 'tenebrite', equipment: { slot: EquipmentSlot.Body, magicAttack: 12, magicDefence: 12, magicDamageBonus: 1, requiredLevels: [{ skill: SkillName.Magic, level: 30 }], } },
    { id: 'affinity_bottoms', name: 'Affinity Bottoms', description: 'Robe bottoms that crackle with power.', stackable: false, value: 3000, iconUrl: 'https://api.iconify.design/game-icons:skirt.svg', material: 'tenebrite', equipment: { slot: EquipmentSlot.Legs, magicAttack: 8, magicDefence: 8, magicDamageBonus: 1, requiredLevels: [{ skill: SkillName.Magic, level: 30 }], } },
    { id: 'affinity_gloves', name: 'Affinity Gloves', description: 'Gloves that make your hands tingle with magic.', stackable: false, value: 1500, iconUrl: 'https://api.iconify.design/game-icons:gloves.svg', material: 'tenebrite', equipment: { slot: EquipmentSlot.Gloves, magicAttack: 3, magicDefence: 3, requiredLevels: [{ skill: SkillName.Magic, level: 30 }], } },
    { id: 'affinity_boots', name: 'Affinity Boots', description: 'Boots that seem to float slightly above the ground.', stackable: false, value: 1500, iconUrl: 'https://api.iconify.design/game-icons:sonic-shoes.svg', material: 'tenebrite', equipment: { slot: EquipmentSlot.Boots, magicAttack: 3, magicDefence: 3, requiredLevels: [{ skill: SkillName.Magic, level: 30 }], } },
    // Robes of Power (Lvl 50)
    { id: 'robe_of_power_hat', name: 'Robe of Power Hat', description: 'A hat that radiates immense magical power.', stackable: false, value: 15000, iconUrl: 'https://api.iconify.design/game-icons:pope-crown.svg', material: 'rune-aether', equipment: { slot: EquipmentSlot.Head, magicAttack: 10, magicDefence: 10, magicDamageBonus: 1, requiredLevels: [{ skill: SkillName.Magic, level: 50 }], } },
    { id: 'robe_of_power_top', name: 'Robe of Power Top', description: 'A robe top that seems woven from pure energy.', stackable: false, value: 30000, iconUrl: 'https://api.iconify.design/game-icons:robe.svg', material: 'rune-aether', equipment: { slot: EquipmentSlot.Body, magicAttack: 20, magicDefence: 20, magicDamageBonus: 3, requiredLevels: [{ skill: SkillName.Magic, level: 50 }], } },
    { id: 'robe_of_power_bottoms', name: 'Robe of Power Bottoms', description: 'Robe bottoms that crackle with untamed power.', stackable: false, value: 20000, iconUrl: 'https://api.iconify.design/game-icons:skirt.svg', material: 'rune-aether', equipment: { slot: EquipmentSlot.Legs, magicAttack: 15, magicDefence: 15, magicDamageBonus: 2, requiredLevels: [{ skill: SkillName.Magic, level: 50 }], } },
    // Tomes (Craftable)
    { id: 'tome_of_warding', name: 'Tome of Warding', description: 'A book of basic defensive magic.', stackable: false, value: 200, iconUrl: 'https://api.iconify.design/game-icons:book-cover.svg', material: 'leather', equipment: { slot: EquipmentSlot.Shield, magicAttack: 4, magicDefence: 6, magicDamageBonus: 1, requiredLevels: [{ skill: SkillName.Magic, level: 10 }], } },
    { id: 'tome_of_focus', name: 'Tome of Focus', description: 'A book that helps focus arcane energies.', stackable: false, value: 1000, iconUrl: 'https://api.iconify.design/game-icons:book-cover.svg', material: 'leather', equipment: { slot: EquipmentSlot.Shield, magicAttack: 8, magicDefence: 8, magicDamageBonus: 2, requiredLevels: [{ skill: SkillName.Magic, level: 20 }], } },
    { id: 'tome_of_power', name: 'Tome of Power', description: 'A book filled with offensive incantations.', stackable: false, value: 2500, iconUrl: 'https://api.iconify.design/game-icons:book-cover.svg', material: 'leather', equipment: { slot: EquipmentSlot.Shield, magicAttack: 12, magicDefence: 10, magicDamageBonus: 3, requiredLevels: [{ skill: SkillName.Magic, level: 30 }], } },
    { id: 'tome_of_the_arcane', name: 'Tome of the Arcane', description: 'A compendium of advanced magical theory.', stackable: false, value: 6000, iconUrl: 'https://api.iconify.design/game-icons:book-cover.svg', material: 'leather', equipment: { slot: EquipmentSlot.Shield, magicAttack: 16, magicDefence: 12, magicDamageBonus: 4, requiredLevels: [{ skill: SkillName.Magic, level: 40 }], } },
    { id: 'tome_of_the_master', name: 'Tome of the Master', description: 'A legendary tome containing the secrets of a master mage.', stackable: false, value: 15000, iconUrl: 'https://api.iconify.design/game-icons:book-cover.svg', material: 'leather', equipment: { slot: EquipmentSlot.Shield, magicAttack: 20, magicDefence: 15, magicDamageBonus: 5, requiredLevels: [{ skill: SkillName.Magic, level: 50 }], } },
    
    // --- CHARGED JEWELRY ---
    // Amulets
    { id: 'amulet_of_magic', name: 'Amulet of Magic', description: 'An enchanted Sapphire Amulet, fully charged with magical energy.', stackable: false, value: 900, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'rune-aqua', equipment: { slot: EquipmentSlot.Necklace, magicAttack: 10, magicDefence: 10, magicDamageBonus: 2 } },
    { id: 'amulet_of_ranging', name: 'Amulet of Ranging', description: 'An enchanted Emerald Amulet, humming with the power of the hunt.', stackable: false, value: 1600, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'rune-verdant', equipment: { slot: EquipmentSlot.Necklace, rangedAttack: 10, rangedDefence: 10, rangedStrength: 2 } },
    { id: 'amulet_of_strength', name: 'Amulet of Strength', description: 'An enchanted Ruby Amulet, radiating with raw physical power.', stackable: false, value: 2625, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'rune-ember', equipment: { slot: EquipmentSlot.Necklace, strengthBonus: 8, stabDefence: 7, slashDefence: 7, crushDefence: 7 } },
    { id: 'amulet_of_power', name: 'Amulet of Power', description: 'An enchanted Diamond Amulet, imbued with overwhelming power.', stackable: false, value: 4200, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'rune-astral', equipment: { slot: EquipmentSlot.Necklace, stabAttack: 6, slashAttack: 6, crushAttack: 6, rangedAttack: 6, magicAttack: 6, stabDefence: 9, slashDefence: 9, crushDefence: 9, rangedDefence: 9, magicDefence: 9, strengthBonus: 6 } },
    { id: 'amulet_of_fate', name: 'Amulet of Fate', description: 'An enchanted Sunstone Amulet that offers teleports to powerful altars and seems to influence the discovery of precious gems.', stackable: false, value: 32000, iconUrl: 'https://api.iconify.design/game-icons:gem-pendant.svg', material: 'sunstone', charges: 4, destroyOnEmpty: false, equipment: { slot: EquipmentSlot.Necklace, stabAttack: 12, slashAttack: 12, crushAttack: 12, rangedAttack: 12, magicAttack: 12, stabDefence: 15, slashDefence: 15, crushDefence: 15, rangedDefence: 15, magicDefence: 15, strengthBonus: 10 }, consumable: { teleportOptions: [ { label: 'Passage Altar', poiId: 'sp_passage_altar' }, { label: 'Nexus Altar', poiId: 'laby_central_altar' }, { label: 'Anima Altar', poiId: 'anima_altar', disabled: true }, { label: 'Astral Altar', poiId: 'ms_f5_astral_altar' } ] } },
    // Rings (charged)
    { id: 'ring_of_prospecting', name: 'Ring of Prospecting', description: 'A charged Sapphire Ring that seems to hum gently in the presence of rare minerals.', stackable: false, value: 800, iconUrl: 'https://api.iconify.design/game-icons:ring.svg', material: 'rune-aqua', charges: 100, equipment: { slot: EquipmentSlot.Ring } },
    { id: 'ring_of_the_woodsman', name: 'Ring of the Woodsman', description: 'A charged Emerald Ring that feels connected to the heart of the forest.', stackable: false, value: 1500, iconUrl: 'https://api.iconify.design/game-icons:ring.svg', material: 'rune-verdant', charges: 150, equipment: { slot: EquipmentSlot.Ring } },
    { id: 'ring_of_the_forge', name: 'Ring of the Forge', description: 'A charged Ruby Ring that radiates a gentle heat, sometimes preserving materials at the anvil.', stackable: false, value: 2525, iconUrl: 'https://api.iconify.design/game-icons:ring.svg', material: 'rune-ember', charges: 200, equipment: { slot: EquipmentSlot.Ring } },
    { id: 'ring_of_mastery', name: 'Ring of Mastery', description: 'A charged Diamond Ring that sharpens the focus and steadies the hand, sometimes granting a flash of insight for extra experience.', stackable: false, value: 4100, iconUrl: 'https://api.iconify.design/game-icons:ring.svg', material: 'rune-astral', charges: 250, equipment: { slot: EquipmentSlot.Ring } },
    { id: 'ring_of_greed', name: 'Ring of Greed', description: 'A ring that hums with avarice. It magically attracts all coin drops from monsters directly into your money pouch and allows teleportation to major bank locations.', stackable: false, value: 30000, iconUrl: 'https://api.iconify.design/game-icons:ring.svg', material: 'sunstone', charges: 4, destroyOnEmpty: false, equipment: { slot: EquipmentSlot.Ring }, consumable: { teleportOptions: [ { label: 'Silverhaven Bank', poiId: 'silverhaven_bank' }, { label: 'Fouthia Bank', poiId: 'fouthia_bank' }, { label: 'Meadowdale Bank', poiId: 'meadowdale_bank' } ] } },
    // Necklaces (charged)
    { id: 'necklace_of_binding', name: 'Necklace of Binding', description: 'A charged Sapphire Necklace that resonates with the flow of magical essence, guaranteeing an extra rune per essence crafted.', stackable: false, value: 900, iconUrl: 'https://api.iconify.design/game-icons:necklace.svg', material: 'rune-astral', charges: 6, equipment: { slot: EquipmentSlot.Necklace } },
    { id: 'necklace_of_the_angler', name: 'Necklace of the Angler', description: 'A charged Emerald Necklace that seems to attract rare fish. Grants a 30% increased fishing success chance.', stackable: false, value: 1600, iconUrl: 'https://api.iconify.design/game-icons:necklace.svg', material: 'rune-verdant', charges: 600, equipment: { slot: EquipmentSlot.Necklace } },
    { id: 'necklace_of_pyromancy', name: 'Necklace of Pyromancy', description: 'A charged Ruby Necklace that draws out hidden potential from burning logs. Has a chance to yield extra resources when firemaking.', stackable: false, value: 2625, iconUrl: 'https://api.iconify.design/game-icons:necklace.svg', material: 'rune-ember', charges: 120, equipment: { slot: EquipmentSlot.Necklace } },
    { id: 'necklace_of_shadows', name: 'Necklace of Shadows', description: 'A charged Diamond Necklace that can bend light around the wearer, rendering them invisible to aggressive monsters.', stackable: false, value: 4200, iconUrl: 'https://api.iconify.design/game-icons:necklace.svg', material: 'burnt', charges: 100, equipment: { slot: EquipmentSlot.Necklace } },
    { id: 'necklace_of_fortune', name: 'Necklace of Fortune', description: 'A charged Sunstone Necklace attuned to remote resource locations. It is said to improve the wearer\'s luck.', stackable: false, value: 32000, iconUrl: 'https://api.iconify.design/game-icons:necklace.svg', material: 'sunstone', charges: 4, destroyOnEmpty: false, equipment: { slot: EquipmentSlot.Necklace }, consumable: { teleportOptions: [ { label: 'Gale Swept Peaks', poiId: 'ancient_ruins_summit' }, { label: 'Volcanic Steam Vents', poiId: 'vsv_cinder_cone_peak' }, { label: 'Wyrmwood Grove', poiId: 'wg_dragon_peak' } ] } },
    
    // NEW QUEST REWARDS
    { id: 'cape_of_verdant_growth', name: 'Cape of Verdant Growth', description: 'A cape woven from living leaves that seems to speed up natural processes.', stackable: false, value: 10000, iconUrl: 'https://api.iconify.design/game-icons:cloak.svg', material: 'rune-verdant', equipment: { slot: EquipmentSlot.Cape, stabDefence: 6, slashDefence: 6, crushDefence: 6, rangedDefence: 6, magicDefence: 6 } },
    { id: 'cape_of_the_hex-binder', name: 'Cape of the Hex-binder', description: 'A dark cape that seems to absorb light, humming with an ancient intent.', stackable: false, value: 10000, iconUrl: 'https://api.iconify.design/game-icons:cloak.svg', material: 'rune-hex', equipment: { slot: EquipmentSlot.Cape, stabDefence: 6, slashDefence: 6, crushDefence: 6, rangedDefence: 6, magicDefence: 6 } },
    { id: 'cape_of_the_abyssal_nexus', name: 'Cape of the Abyssal Nexus', description: 'A heavy cape that feels cold to the touch, seemingly woven from solidified shadows.', stackable: false, value: 10000, iconUrl: 'https://api.iconify.design/game-icons:cloak.svg', material: 'rune-nexus', equipment: { slot: EquipmentSlot.Cape, stabDefence: 6, slashDefence: 6, crushDefence: 6, rangedDefence: 6, magicDefence: 6 } },
    { id: 'ring_of_preservation', name: 'Ring of Preservation', description: "A magical ring that belonged to Fitzwilliam's wife. It has a small chance to save a secondary ingredient when mixing potions.", stackable: false, value: 2500, iconUrl: 'https://api.iconify.design/game-icons:ring.svg', material: 'emerald', equipment: { slot: EquipmentSlot.Ring, magicDefence: 2 } },
];
