import { Item, EquipmentSlot, SkillName } from '../../types';

export const armor_two: Item[] = [
    { id: 'reflective_ivory_buckler', name: 'Reflective Ivory Buckler', description: 'A small, tough shield made from polished ivory that seems to reflect light in strange ways.', stackable: false, value: 12000, iconUrl: 'https://api.iconify.design/game-icons:round-shield.svg', material: 'steel', equipment: { slot: EquipmentSlot.Shield, stabDefence: 15, slashDefence: 20, crushDefence: 18, rangedDefence: 25, magicDefence: 5, requiredLevels: [{ skill: SkillName.Defence, level: 45 }], } },
    { id: 'wraithwalkers', name: 'Wraithwalkers', description: 'Eerily silent boots that seem to muffle the sound of your footsteps.', stackable: false, value: 25000, iconUrl: 'https://api.iconify.design/game-icons:leather-boot.svg', material: 'runic', equipment: { slot: EquipmentSlot.Boots, stabDefence: 4, slashDefence: 4, crushDefence: 4, rangedDefence: 4, magicDefence: 8, requiredLevels: [{ skill: SkillName.Defence, level: 50 }], } },
    { id: 'voidsilk_hood', name: 'Voidsilk Hood', description: 'A hood woven from threads that seem to absorb light. It hums with latent magical energy.', stackable: false, value: 45000, iconUrl: 'https://api.iconify.design/game-icons:hood.svg', material: 'rune-hex', equipment: { slot: EquipmentSlot.Head, magicAttack: 8, stabDefence: 5, slashDefence: 5, crushDefence: 5, rangedDefence: 5, magicDefence: 12, requiredLevels: [{ skill: SkillName.Defence, level: 55 }, { skill: SkillName.Magic, level: 55 }], } },
    { id: 'verdant_crest', name: 'Verdant Crest', description: 'A helmet fashioned from the hardened, leaf-like plates of a powerful beast.', stackable: false, value: 8000, iconUrl: 'https://api.iconify.design/game-icons:crested-helmet.svg', material: 'adamantite', equipment: { slot: EquipmentSlot.Head, stabDefence: 22, slashDefence: 24, crushDefence: 20, rangedDefence: 22, magicDefence: -2, strengthBonus: 2, requiredLevels: [{ skill: SkillName.Defence, level: 50 }], } },
    { id: 'ghostweave_chain', name: 'Ghostweave Chain', description: 'A chainbody woven from ethereal threads, offering excellent magical resistance.', stackable: false, value: 60000, iconUrl: 'https://api.iconify.design/game-icons:mail-shirt.svg', material: 'rune-astral', equipment: { slot: EquipmentSlot.Body, stabDefence: 30, slashDefence: 30, crushDefence: 30, rangedDefence: 40, magicDefence: 55, requiredLevels: [{ skill: SkillName.Defence, level: 60 }], } },

    // Weightless Agility Outfit
    { id: 'weightless_hood', name: 'Weightless Hood', description: "A hood made from an exceptionally light material. Part of the Weightless outfit.", stackable: false, value: 0, iconUrl: 'https://api.iconify.design/game-icons:hood.svg', material: 'raw-fish', equipment: { slot: EquipmentSlot.Head, stabDefence: 2, slashDefence: 2, crushDefence: 1, rangedDefence: 4, magicDefence: 1, magicAttack: -2, stabAttack: -2, slashAttack: -2, crushAttack: -2, requiredLevels: [{ skill: SkillName.Agility, level: 20 }], } },
    { id: 'weightless_tunic', name: 'Weightless Tunic', description: "A tunic made from an exceptionally light material. Part of the Weightless outfit.", stackable: false, value: 0, iconUrl: 'https://api.iconify.design/game-icons:leather-vest.svg', material: 'raw-fish', equipment: { slot: EquipmentSlot.Body, stabDefence: 8, slashDefence: 8, crushDefence: 5, rangedDefence: 12, magicDefence: 4, magicAttack: -5, stabAttack: -5, slashAttack: -5, crushAttack: -5, requiredLevels: [{ skill: SkillName.Agility, level: 20 }], } },
    { id: 'weightless_trousers', name: 'Weightless Trousers', description: "Trousers made from an exceptionally light material. Part of the Weightless outfit.", stackable: false, value: 0, iconUrl: 'https://api.iconify.design/game-icons:leg-armor.svg', material: 'raw-fish', equipment: { slot: EquipmentSlot.Legs, stabDefence: 5, slashDefence: 5, crushDefence: 3, rangedDefence: 8, magicDefence: 2, magicAttack: -3, stabAttack: -3, slashAttack: -3, crushAttack: -3, requiredLevels: [{ skill: SkillName.Agility, level: 20 }], } },
    { id: 'weightless_gloves', name: 'Weightless Gloves', description: "Gloves made from an exceptionally light material. Part of the Weightless outfit.", stackable: false, value: 0, iconUrl: 'https://api.iconify.design/game-icons:gloves.svg', material: 'raw-fish', equipment: { slot: EquipmentSlot.Gloves, stabDefence: 1, slashDefence: 1, crushDefence: 1, rangedDefence: 2, magicDefence: 1, requiredLevels: [{ skill: SkillName.Agility, level: 20 }], } },
    { id: 'weightless_boots', name: 'Weightless Boots', description: "Boots made from an exceptionally light material. Part of the Weightless outfit.", stackable: false, value: 0, iconUrl: 'https://api.iconify.design/game-icons:leather-boot.svg', material: 'raw-fish', equipment: { slot: EquipmentSlot.Boots, stabDefence: 1, slashDefence: 1, crushDefence: 1, rangedDefence: 2, magicDefence: 1, requiredLevels: [{ skill: SkillName.Agility, level: 20 }], } },
];
