import { Item } from '../../types';

export const resources: Item[] = [
    // Ores
    { id: 'copper_ore', name: 'Copper Ore', description: 'A lump of copper ore.', stackable: false, value: 4, iconUrl: 'https://api.iconify.design/game-icons:ore.svg', material: 'copper' },
    { id: 'tin_ore', name: 'Tin Ore', description: 'A lump of tin ore.', stackable: false, value: 4, iconUrl: 'https://api.iconify.design/game-icons:ore.svg', material: 'tin' },
    { id: 'iron_ore', name: 'Iron Ore', description: 'A lump of iron ore, requires level 15 Mining.', stackable: false, value: 10, iconUrl: 'https://api.iconify.design/game-icons:ore.svg', material: 'iron-ore' },
    { id: 'coal', name: 'Coal', description: 'A lump of coal, essential for smelting high-grade metals.', stackable: false, value: 25, iconUrl: 'https://api.iconify.design/game-icons:coal-wagon.svg', material: 'burnt' },
    { id: 'silver_ore', name: 'Silver Ore', description: 'A chunk of rock containing veins of silver.', stackable: false, value: 40, iconUrl: 'https://api.iconify.design/game-icons:ore.svg', material: 'silver' },
    { id: 'gold_ore', name: 'Gold Ore', description: 'A lump of gold ore.', stackable: false, value: 70, iconUrl: 'https://api.iconify.design/game-icons:ore.svg', material: 'gold' },
    { id: 'mithril_ore', name: 'Mithril Ore', description: 'A chunk of raw, silvery-blue mithril ore.', stackable: false, value: 50, iconUrl: 'https://api.iconify.design/game-icons:ore.svg', material: 'mithril-ore' },
    { id: 'adamantite_ore', name: 'Adamantite Ore', description: 'A chunk of raw, dark green adamantite ore.', stackable: false, value: 80, iconUrl: 'https://api.iconify.design/game-icons:ore.svg', material: 'adamantite-ore' },
    { id: 'titanium_ore', name: 'Titanium Ore', description: 'A chunk of incredibly rare, purplish titanium ore.', stackable: false, value: 120, iconUrl: 'https://api.iconify.design/game-icons:ore.svg', material: 'titanium-ore' },
    { id: 'rune_essence', name: 'Rune Essence', description: 'A fragment of rock containing pure magical energy.', stackable: false, value: 2, iconUrl: 'https://api.iconify.design/game-icons:rock.svg', material: 'mithril' },

    // Bars
    { id: 'bronze_bar', name: 'Bronze Bar', description: 'A bar of bronze, ready for smithing.', stackable: false, value: 15, iconUrl: 'https://api.iconify.design/game-icons:metal-bar.svg', material: 'bronze' },
    { id: 'iron_bar', name: 'Iron Bar', description: 'A bar of iron, ready for smithing.', stackable: false, value: 40, iconUrl: 'https://api.iconify.design/game-icons:metal-bar.svg', material: 'iron' },
    { id: 'steel_bar', name: 'Steel Bar', description: 'A bar of steel, ready for smithing.', stackable: false, value: 100, iconUrl: 'https://api.iconify.design/game-icons:metal-bar.svg', material: 'steel' },
    { id: 'silver_bar', name: 'Silver Bar', description: 'A bar of pure silver.', stackable: false, value: 80, iconUrl: 'https://api.iconify.design/game-icons:gold-bar.svg', material: 'silver' },
    { id: 'gold_bar', name: 'Gold Bar', description: 'A bar of pure gold.', stackable: false, value: 100, iconUrl: 'https://api.iconify.design/game-icons:gold-bar.svg', material: 'gold' },
    { id: 'mithril_bar', name: 'Mithril Bar', description: 'A bar of refined mithril.', stackable: false, value: 150, iconUrl: 'https://api.iconify.design/game-icons:metal-bar.svg', material: 'mithril' },
    { id: 'adamantite_bar', name: 'Adamantite Bar', description: 'A bar of refined adamantite.', stackable: false, value: 250, iconUrl: 'https://api.iconify.design/game-icons:metal-bar.svg', material: 'adamantite' },
    { id: 'runic_bar', name: 'Runic Bar', description: 'A bar of refined, durable runic metal.', stackable: false, value: 400, iconUrl: 'https://api.iconify.design/game-icons:metal-bar.svg', material: 'runic' },
    
    // Logs
    { id: 'logs', name: 'Logs', description: 'Standard logs from a tree.', stackable: false, value: 2, iconUrl: 'https://api.iconify.design/game-icons:wood-pile.svg', material: 'wood-normal' },
    { id: 'oak_logs', name: 'Oak Logs', description: 'Sturdy logs from a mighty oak tree.', stackable: false, value: 15, iconUrl: 'https://api.iconify.design/game-icons:wood-pile.svg', material: 'wood-oak' },
    { id: 'willow_logs', name: 'Willow Logs', description: 'Flexible logs from a willow tree.', stackable: false, value: 40, iconUrl: 'https://api.iconify.design/game-icons:wood-pile.svg', material: 'wood-willow' },
    { id: 'maple_logs', name: 'Maple Logs', description: 'Hard logs from a maple tree, excellent for strong bows.', stackable: false, value: 60, iconUrl: 'https://api.iconify.design/game-icons:wood-pile.svg', material: 'wood-oak' },
    { id: 'feywood_logs', name: 'Feywood Logs', description: 'Logs from a Feywood tree. They shimmer with a faint, magical light.', stackable: false, value: 90, iconUrl: 'https://api.iconify.design/game-icons:wood-pile.svg', material: 'wood-feywood' },
    { id: 'yew_logs', name: 'Yew Logs', description: 'Logs from an ancient yew tree, perfect for powerful bows.', stackable: false, value: 120, iconUrl: 'https://api.iconify.design/game-icons:wood-pile.svg', material: 'wood-yew' },
    { id: 'driftwood_logs', name: 'Driftwood Logs', description: 'Weathered logs, hardened by the sea.', stackable: false, value: 5, iconUrl: 'https://api.iconify.design/game-icons:wood-pile.svg', material: 'wood-driftwood' },
    { id: 'mahogany_logs', name: 'Mahogany Logs', description: 'Rich, dark red logs from a tropical tree.', stackable: false, value: 150, iconUrl: 'https://api.iconify.design/game-icons:wood-pile.svg', material: 'wood-mahogany' },
    
    // Gems
    { id: 'uncut_sapphire', name: 'Uncut Sapphire', description: 'A raw, uncut sapphire. Could be cut with a chisel.', stackable: false, value: 50, iconUrl: 'https://api.iconify.design/game-icons:emerald.svg', material: 'uncut-sapphire' },
    { id: 'sapphire', name: 'Sapphire', description: 'A beautiful blue gemstone.', stackable: false, value: 100, iconUrl: 'https://api.iconify.design/game-icons:rupee.svg', material: 'sapphire' },
    { id: 'uncut_emerald', name: 'Uncut Emerald', description: 'A raw, uncut emerald. Could be cut with a chisel.', stackable: false, value: 100, iconUrl: 'https://api.iconify.design/game-icons:emerald.svg', material: 'uncut-emerald' },
    { id: 'emerald', name: 'Emerald', description: 'A brilliant green gemstone.', stackable: false, value: 200, iconUrl: 'https://api.iconify.design/game-icons:rupee.svg', material: 'emerald' },
    { id: 'uncut_ruby', name: 'Uncut Ruby', description: 'A raw, uncut ruby. Could be cut with a chisel.', stackable: false, value: 200, iconUrl: 'https://api.iconify.design/game-icons:emerald.svg', material: 'uncut-ruby' },
    { id: 'ruby', name: 'Ruby', description: 'A deep red gemstone.', stackable: false, value: 400, iconUrl: 'https://api.iconify.design/game-icons:rupee.svg', material: 'ruby' },
    { id: 'uncut_diamond', name: 'Uncut Diamond', description: 'A raw, uncut diamond. Could be cut with a chisel.', stackable: false, value: 1000, iconUrl: 'https://api.iconify.design/game-icons:emerald.svg', material: 'uncut-diamond' },
    { id: 'diamond', name: 'Diamond', description: 'A brilliant, clear gemstone.', stackable: false, value: 2000, iconUrl: 'https://api.iconify.design/game-icons:rupee.svg', material: 'diamond' },

    // Monster Drops & Crafting Materials
    { id: 'goblin_hide', name: 'Goblin Hide', description: 'Tough hide from a goblin.', stackable: false, value: 5, iconUrl: 'https://api.iconify.design/game-icons:animal-hide.svg' },
    { id: 'rat_tail', name: 'Rat Tail', description: 'A grim trophy from a slain rodent.', stackable: false, value: 1, iconUrl: 'https://api.iconify.design/game-icons:rat.svg' },
    { id: 'spider_silk', name: 'Spider Silk', description: 'Tough, sticky silk from a giant spider.', stackable: false, value: 8, iconUrl: 'https://api.iconify.design/game-icons:spider-web.svg' },
    { id: 'wool', name: 'Wool', description: 'Raw, unspun wool from a sheep.', stackable: false, value: 2, iconUrl: 'https://api.iconify.design/game-icons:fluffy-cloud.svg' },
    { id: 'ball_of_wool', name: 'Ball of Wool', description: 'A ball of fluffy wool, ready for crafting.', stackable: false, value: 3, iconUrl: 'https://api.iconify.design/game-icons:wool.svg' },
    { id: 'bones', name: 'Bones', description: 'A set of ordinary bones. Can be buried for Prayer experience.', stackable: false, value: 2, iconUrl: 'https://api.iconify.design/game-icons:crossed-bones.svg', buryable: { prayerXp: 5 } },
    { id: 'big_bones', name: 'Big Bones', description: 'Larger bones from a tougher creature. Can be buried for Prayer experience.', stackable: false, value: 10, iconUrl: 'https://api.iconify.design/game-icons:crossed-bones.svg', buryable: { prayerXp: 15 } },
    { id: 'dragon_bones', name: 'Dragon Bones', description: 'Large, scorched bones from a dragon. Bury them for a large amount of Prayer experience.', stackable: false, value: 200, iconUrl: 'https://api.iconify.design/game-icons:dinosaur-bones.svg', buryable: { prayerXp: 100 } },
    { id: 'dragon_hide', name: 'Dragon Hide', description: 'A tough, scaly hide from a dragon. Tanners cannot work with this material.', stackable: false, value: 500, iconUrl: 'https://api.iconify.design/game-icons:dragon-scale.svg', material: 'leather' },
    { id: 'feathers', name: 'Feathers', description: 'A soft feather of an avian.', stackable: true, value: 1, iconUrl: 'https://api.iconify.design/game-icons:feather.svg' },
    { id: 'eggs', name: 'Chicken Egg', description: 'A fresh egg. A simple cooking ingredient.', stackable: false, value: 2, iconUrl: 'https://api.iconify.design/game-icons:egg-clutch.svg' },
    { id: 'cowhide', name: 'Cowhide', description: 'The unprocessed hide of a cow. It needs to be tanned.', stackable: false, value: 6, iconUrl: 'https://api.iconify.design/game-icons:animal-hide.svg' },
    { id: 'leather', name: 'Leather', description: 'A piece of tanned leather, ready for crafting.', stackable: false, value: 10, iconUrl: 'https://api.iconify.design/game-icons:animal-hide.svg', material: 'leather' },
    { id: 'thread', name: 'Thread', description: 'A spool of sturdy thread.', stackable: true, value: 1, iconUrl: 'https://api.iconify.design/game-icons:sewing-string.svg' },
    { id: 'flax', name: 'Flax', description: 'A plant that can be spun into a bow string.', stackable: false, value: 1, iconUrl: 'https://api.iconify.design/game-icons:flax.svg' },
    { id: 'bow_string', name: 'Bow String', description: 'A string for a bow.', stackable: false, value: 5, iconUrl: 'https://api.iconify.design/game-icons:whiplash.svg' },
    { id: 'rope', name: 'Rope', description: 'A sturdy length of rope.', stackable: false, value: 15, iconUrl: 'https://api.iconify.design/game-icons:rope-coil.svg' },
    { id: 'mystic_page', name: 'Mystic Page', description: 'A page from an arcane text, humming with magical potential.', stackable: true, value: 20, iconUrl: 'https://api.iconify.design/game-icons:written-scroll.svg', material: 'rune-aqua' },
    { id: 'harpy_feather', name: 'Harpy Feather', description: 'A large, sharp feather from a harpy. Could be used in fletching.', stackable: true, value: 50, iconUrl: 'https://api.iconify.design/game-icons:feather.svg', material: 'uncut-sapphire' },
    { id: 'golem_core', name: 'Golem Core', description: 'A faintly glowing stone that was the heart of a stone golem. Can be shattered with a hammer.', stackable: false, value: 500, iconUrl: 'https://api.iconify.design/game-icons:glowing-artifact.svg' },
    { id: 'straw', name: 'Straw', description: 'A bundle of dry straw. It smells faintly of hay and old magic.', stackable: false, value: 1, iconUrl: 'https://api.iconify.design/game-icons:wheat.svg' },
    { id: 'boar_hide', name: 'Boar Hide', description: 'The tough, bristly hide of a wild boar. It needs to be tanned.', stackable: false, value: 8, iconUrl: 'https://api.iconify.design/game-icons:animal-hide.svg' },
    { id: 'boar_leather', name: 'Boar Leather', description: 'Tanned hide from a wild boar, ready for crafting.', stackable: false, value: 12, iconUrl: 'https://api.iconify.design/game-icons:animal-hide.svg', material: 'leather' },
    { id: 'fey_dust', name: 'Fey Dust', description: 'A pinch of glittering, magical dust with a faint lavender scent.', stackable: false, value: 75, iconUrl: 'https://api.iconify.design/game-icons:powder.svg' },
    { id: 'serpent_scale_dust', name: 'Serpent Scale Dust', description: 'Fine, iridescent dust ground from the scales of a powerful swamp serpent.', stackable: false, value: 150, iconUrl: 'https://api.iconify.design/game-icons:powder.svg' },
    { id: 'giant_crab_claw', name: 'Giant Crab Claw', description: 'A massive claw from a giant crab. It could probably take a finger off.', stackable: false, value: 20, iconUrl: 'https://api.iconify.design/game-icons:crab-claw.svg' },
    { id: 'enchanted_bark', name: 'Enchanted Bark', description: 'Bark from a Feywood tree that hums with a faint magical energy.', stackable: false, value: 60, iconUrl: 'https://api.iconify.design/game-icons:planks.svg' },
    { id: 'brimstone', name: 'Brimstone', description: 'A chunk of yellow, sulfuric rock that is warm to the touch.', stackable: false, value: 180, iconUrl: 'https://api.iconify.design/game-icons:rock.svg', material: 'gold' },
    { id: 'wolf_pelt', name: 'Wolf Pelt', description: 'The fur of a wolf. It needs to be tanned.', stackable: false, value: 25, iconUrl: 'https://api.iconify.design/game-icons:animal-hide.svg' },
    { id: 'wolf_leather', name: 'Wolf Leather', description: 'Tanned pelt from a wolf, ready for crafting.', stackable: false, value: 35, iconUrl: 'https://api.iconify.design/game-icons:animal-hide.svg', material: 'leather' },
    { id: 'bear_pelt', name: 'Bear Pelt', description: 'The thick fur of a bear. It needs to be tanned.', stackable: false, value: 40, iconUrl: 'https://api.iconify.design/game-icons:animal-hide.svg' },
    { id: 'bear_leather', name: 'Bear Leather', description: 'Tanned pelt from a bear, ready for crafting.', stackable: false, value: 60, iconUrl: 'https://api.iconify.design/game-icons:animal-hide.svg', material: 'leather' },
    { id: 'harpy_talon', name: 'Harpy Talon', description: 'A sharp, resilient talon from a harpy. It seems to resonate with a strange energy.', stackable: false, value: 250, iconUrl: 'https://api.iconify.design/game-icons:bird-claw.svg' },
    { id: 'crystalline_chitin', name: 'Crystalline Chitin', description: 'A fragment of exoskeleton from a Salt Flats creature, encrusted with shimmering salt crystals.', stackable: false, value: 400, iconUrl: 'https://api.iconify.design/game-icons:insect-jaws.svg', material: 'silver' },
    { id: 'eldritch_pearl', name: 'Eldritch Pearl', description: 'A swirling, dark pearl that seems to whisper secrets when held to the ear. It feels ancient.', stackable: false, value: 1200, iconUrl: 'https://api.iconify.design/game-icons:mineral-pearls.svg', material: 'burnt' },
    // New baking resources
    { id: 'wheat', name: 'Wheat', description: 'A stalk of wheat.', stackable: false, value: 1, iconUrl: 'https://api.iconify.design/game-icons:grain-bundle.svg' },
    { id: 'flour', name: 'Sack of Flour', description: 'A sack filled with finely milled flour.', stackable: false, value: 3, iconUrl: 'https://api.iconify.design/game-icons:flour.svg' },
    { id: 'bucket_of_water', name: 'Bucket of Water', description: 'A bucket filled with water.', stackable: false, value: 2, iconUrl: 'https://api.iconify.design/game-icons:full-wood-bucket.svg', emptyable: { emptyItemId: 'bucket' }, material: 'vial-water' },
    { id: 'bucket_of_milk', name: 'Bucket of Milk', description: 'A bucket filled with fresh milk.', stackable: false, value: 4, iconUrl: 'https://api.iconify.design/game-icons:milk-carton.svg', emptyable: { emptyItemId: 'bucket' } },
    // New Salt Flats resources
    { id: 'rock_salt', name: 'Rock Salt', description: 'A sharp, crystalline chunk of salt.', stackable: false, value: 15, iconUrl: 'https://api.iconify.design/game-icons:salt-shaker.svg', material: 'tin' },
    { id: 'brine_crystal', name: 'Brine Crystal', description: 'A perfectly formed crystal, saturated with magical brine.', stackable: false, value: 100, iconUrl: 'https://api.iconify.design/game-icons:crystal-cluster.svg', material: 'sapphire' },
    { id: 'scuttler_shell_fragment', name: 'Scuttler Shell Fragment', description: 'A hard, sharp fragment from a Crystal Scuttler\'s shell.', stackable: false, value: 40, iconUrl: 'https://api.iconify.design/game-icons:sharp-halberd.svg', material: 'steel' },
    { id: 'crystalline_shell_shard', name: 'Crystalline Shell Shard', description: "A shard from a Crystalline Tortoise. It's surprisingly light and sharp.", stackable: false, value: 120, iconUrl: 'https://api.iconify.design/game-icons:oyster.svg', material: 'steel' },
    { id: 'ancient_fossil', name: 'Ancient Fossil', description: 'The fossilized remains of an ancient sea creature.', stackable: false, value: 250, iconUrl: 'https://api.iconify.design/game-icons:ammonite-fossil.svg' },
    // New Crystalline Isles resources
    { id: 'crystal_shard', name: 'Crystal Shard', description: 'A sharp, resonating shard of pure crystal.', stackable: true, value: 75, iconUrl: 'https://api.iconify.design/game-icons:gold-nuggets.svg', material: 'diamond' },
    { id: 'resonating_crystal', name: 'Resonating Crystal', description: 'A larger crystal that hums with a powerful, stored energy.', stackable: false, value: 350, iconUrl: 'https://api.iconify.design/game-icons:crystal-cluster.svg', material: 'diamond' },
    { id: 'glimmer_thread_fiber', name: 'Glimmer-thread Fiber', description: 'A magical fiber harvested from the mane of a Glimmerhorn Stag.', stackable: true, value: 50, iconUrl: 'https://api.iconify.design/game-icons:yarn.svg', material: 'rune-astral' },
    // Dragonhides
    { id: 'grove_hide', name: 'Grove Hide', description: 'A flexible hide cut from a Grove Dragon', stackable: false, value: 300, iconUrl: 'https://api.iconify.design/game-icons:animal-hide.svg', material: 'uncut-emerald' },
    { id: 'frost_hide', name: 'Frost Hide', description: 'A tough hide cut from a Frosthide Dragon', stackable: false, value: 400, iconUrl: 'https://api.iconify.design/game-icons:animal-hide.svg', material: 'uncut-sapphire' },
    { id: 'emberscale_hide', name: 'Emberscale Hide', description: 'A scaley hide cut from a Emberscale Dragon', stackable: false, value: 600, iconUrl: 'https://api.iconify.design/game-icons:animal-hide.svg', material: 'uncut-ruby' },
    { id: 'deathscythe_hide', name: 'Deathscythe Hide', description: 'An ominous hide cut from a Deathscythe Dragon', stackable: false, value: 800, iconUrl: 'https://api.iconify.design/game-icons:animal-hide.svg', material: 'rune-nexus' },
    //Dragon Leather
    { id: 'grove_hide_leather', name: 'Grove Leather', description: 'A tough chunk of leather tanned from a dragon hide', stackable: false, value: 400, iconUrl: 'https://api.iconify.design/game-icons:animal-hide.svg', material: 'emerald' },
    { id: 'frost_hide_leather', name: 'Frosthide Leather', description: 'A tough chunk of leather tanned from a dragon hide', stackable: false, value: 500, iconUrl: 'https://api.iconify.design/game-icons:animal-hide.svg', material: 'sapphire' },
    { id: 'emberscale_hide_leather', name: 'Emberscale Leather', description: 'A tough chunk of leather tanned from a dragon hide', stackable: false, value: 700, iconUrl: 'https://api.iconify.design/game-icons:animal-hide.svg', material: 'ruby' },
    { id: 'deathscythe_hide_leather', name: 'Deathscythe Leather', description: 'A tough chunk of leather tanned from a dragon hide', stackable: false, value: 900, iconUrl: 'https://api.iconify.design/game-icons:animal-hide.svg', material: 'burnt' },
    
];