
import { Item } from '../../types';

export const talismans: Item[] = [
    { id: 'verdant_talisman', name: 'Verdant Talisman', description: 'A mysterious rock fragment that hums with the power of nature.', stackable: false, value: 210, iconUrl: 'https://api.iconify.design/game-icons:wrapped-sweet.svg', divining: { poiId: 'verdant_altar' }, material: 'rune-verdant',},
    { id: 'flux_talisman', name: 'Flux Talisman', description: 'A mysterious rock fragment that hums with chaotic energy.', stackable: false, value: 80, iconUrl: 'https://api.iconify.design/game-icons:wrapped-sweet.svg', divining: { poiId: 'flux_altar' }, material: 'rune-flux',},
    { id: 'gust_talisman', name: 'Gust Talisman', description: 'A mysterious rock fragment that hums with the power of air.', stackable: false, value: 10, iconUrl: 'https://api.iconify.design/game-icons:wrapped-sweet.svg', divining: { poiId: 'gust_altar' }, material: 'rune-gust' },
    { id: 'binding_talisman', name: 'Binding Talisman', description: 'A mysterious rock fragment that hums with binding energies.', stackable: false, value: 10, iconUrl: 'https://api.iconify.design/game-icons:wrapped-sweet.svg', divining: { poiId: 'binding_altar' }, material: 'rune-binding' },
    { id: 'stone_talisman', name: 'Stone Talisman', description: 'A mysterious rock fragment that hums with the power of earth.', stackable: false, value: 10, iconUrl: 'https://api.iconify.design/game-icons:wrapped-sweet.svg', divining: { poiId: 'stone_altar' }, material: 'rune-stone' },
    { id: 'aqua_talisman', name: 'Aqua Talisman', description: 'A mysterious rock fragment that hums with the power of water.', stackable: false, value: 10, iconUrl: 'https://api.iconify.design/game-icons:wrapped-sweet.svg', divining: { poiId: 'aqua_altar' }, material: 'rune-aqua' },
    { id: 'ember_talisman', name: 'Ember Talisman', description: 'A mysterious rock fragment that hums with the power of fire.', stackable: false, value: 10, iconUrl: 'https://api.iconify.design/game-icons:wrapped-sweet.svg', divining: { poiId: 'ruined_watchtower' }, material: 'rune-ember' },
    { id: 'astral_talisman', name: 'Astral Talisman', description: 'A mysterious rock fragment that hums with cosmic energy.', stackable: false, value: 220, iconUrl: 'https://api.iconify.design/game-icons:wrapped-sweet.svg', divining: { poiId: 'astral_altar' }, material: 'rune-astral' },
    { id: 'passage_talisman', name: 'Passage Talisman', description: 'A mysterious rock fragment that hums with restless energy.', stackable: false, value: 450, iconUrl: 'https://api.iconify.design/game-icons:wrapped-sweet.svg', divining: { poiId: 'sp_passage_altar' }, material: 'rune-passage' },
];